### ISSUE TITLE
cors-anywhere.herokuapp.com is unreachable

### ISSUE THREAD

**Issue by irfansyedsasken** [Rob--W/cors-anywhere#100]

**Comment by deQuota** [comment]
Facing the same 
```
Request URL:https://cors-anywhere.herokuapp.com/
Request Method:GET
Status Code:503 Service Unavailable
Remote Address:54.235.102.46:443
Referrer Policy:no-referrer-when-downgrade
```

**Comment by Rob--W** [comment]
I have verified my account and the app is up again. To avoid quota limits again, I have also taken down the cors-anywhere-eu subdomain (this was not publicly advertised anywhere except in some comment in one of the issues, so the impact should be limited).

**Comment by irfansyedsasken** [comment]
again the same issue!!!

**Comment by deQuota** [comment]
Yes, again same issue occurred, but I think now it's working

*Nisal Waduge,*
*3rd Year Undergraduate,*
*Faculty of Information Technology,*
*University of Moratuwa,*
*Sri Lanka.*
*Mobile : +940775860941*
