### ISSUE TITLE
My own cros anywhere, need help ?

### ISSUE THREAD

**Issue by agadirian** [Rob--W/cors-anywhere#101]
I create my own cros anywhere https://fathomless-cliffs-85079.herokuapp.com/ is there any way to make it working only in my domain.

**Comment by Rob--W** [comment]
Set the `CORSANYWHERE_WHITELIST` variable to your origin. This variable is documented at https://github.com/Rob--W/cors-anywhere#demo-server

To set environment variables on Heroku, see https://devcenter.heroku.com/articles/config-vars
