### ISSUE TITLE
Force cors-anywhere to return desktop version of HTML source code

### ISSUE THREAD

**Issue by andreathniah** [Rob--W/cors-anywhere#105]
Noticed that when I'm using my mobile, `cors-anywhere` would return the mobile version of the HTML source code instead of the desktop version. This is despite using the desktop version address (`domain.com `instead of `m.domain.com`).

 Is it possible to force `cors-anywhere` to only return the desktop version of the source code?

**Comment by Rob--W** [comment]
This is probably due to user-agent sniffing. Override the `User-Agent` request header in your web app to change the user agent.
