### ISSUE TITLE
How to make it work with Chromecast

### ISSUE THREAD

**Issue by rangav** [Rob--W/cors-anywhere#107]
Hi,

I am trying to cast youtube live streams in chromecast, i am still getting cors error using crossorigin.me proxy.

Do any know how to make it work with chromecast?

Example live stream
https://www.youtube.com/watch?v=XOacA3RYrXk

Thanks

**Comment by Rob--W** [comment]
This ticket seems misplaced. I'll close this one since you've already opened a new ticket at the right place: https://github.com/technoboy10/crossorigin.me/issues/113
