### ISSUE TITLE
Is it possible to strip headers with the request?

### ISSUE THREAD

**Issue by raRaRa** [Rob--W/cors-anywhere#108]
It would be great if I could send query parameters that specifies which headers should be stripped in the request. I only want to strip certain headers for certain requests.

Is this possible? Thanks.

**Comment by Rob--W** [comment]
That's not supported. By design, the API endpoint is `[CORS Anywhere domain]/[URL here]`. The query parameters are forwarded as-is.

If you want to strip request headers, then you can host CORS Anywhere yourself and configure the `removeHeaders` option.
