### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by wimlibby** [Rob--W/cors-anywhere#109]
Sorry, new to node.js....

I have deployed to Heroku and set up CL.

I do not understand where or how to set up Whitelist.

for example, I can't find documentation to tell me how to use:
export PORT=8080
export CORSANYWHERE_WHITELIST=https://example.com,http://example.com,http://example.com:8080
node server.js

I want to limit to only certain domains, but not don't know where to edit code or input parameters.

Again, sorry, I am a newbie with Node.js and Heroku.

**Comment by Rob--W** [comment]
See https://github.com/Rob--W/cors-anywhere/issues/101#issuecomment-353806977
