### ISSUE TITLE
Setup as a transparent proxy

### ISSUE THREAD

**Issue by hmorneau** [Rob--W/cors-anywhere#115]
Hi,

I have an server application that do not support X-Forwarded-For. Is it possible (and how) to configure this CORS as a transparent proxy (basically spoofing the client IP to the server).

Thanks

**Comment by Rob--W** [comment]
First, if you don't really need CORS, then stop reading - CORS Anywhere should not be used.

Secondly, `X-Forwarded-For` can only be relied upon if the source is an intermediate that you trust. Never trust this value unless you control and trust the client that sends a request with this header.

You cannot spoof the source IP and still have routable packets, unless you control the network infrastructure around the application that ought to receive those packets. Therefore CORS Anywhere will probably not be the answer to your problem.
