### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by indumetroindia** [Rob--W/cors-anywhere#117]
hi,

how can i install it on my centos server?

right now i have installed plesk on it

Is cros anyewhere kind a reserve proxy 

i have some videos on my website IP address protected right now i am using mini proxy https://github.com/joshdick/miniProxy

videos are working fine but problem is can't handle too many users 
please give me the solution

my users need to connect to my ipaddressees  for view the live stream

is cross anywhere going to help me with it

**Comment by Rob--W** [comment]
> how can i install it on my centos server?

Install Node.js, clone this Github repo (or download the zip file) and then do `npm install` to install libraries. Then run `node server.js`.

You can also use this as a library, but given your questions I think that you don't have experience with Node.js development, so I suggest to stick with the above option.

In either case, see https://github.com/Rob--W/cors-anywhere/blob/master/README.md#server

> Is cros anyewhere kind a reserve proxy

CORS Anywhere is a reverse proxy. The README has more details.

> videos are working fine but problem is can't handle too many users

Depending on your number of users and the stream sizes, your bottleneck might be the network bandwidth. Switching to a different proxy application will then not help.

> my users need to connect to my ipaddressees for view the live stream

If you run a proxy on your device with the desired IP address, then the proxied request's source IP is your IP address. That's what a proxy does.
