### ISSUE TITLE
Obtaining proxyRes to modify upstream response

### ISSUE THREAD

**Issue by Shriram-Balaji** [Rob--W/cors-anywhere#119]
Hey,

I'm trying to proxy response back from a server but would like to implement something like a memory-cache on the proxied response. I'd like to know if there is a way to obtain the proxyRes from the underlying `http-proxy` module, so that I can make any necessary modifications. 

The following snippet denotes how I'm currently using the package.

```
req.url = req.url.replace("/proxy/", "/");
httpProxy.emit("request", req, res);
```

I tried listening to something like ```httpProxy.on('proxyRes')``` but I don't think that event is being emitted. Could you please point me to any other ways to get the proxied response.

Thanks,
Shriram

**Comment by Rob--W** [comment]
You could try to create a wrapper around `res` to intercept any responses (headers and body). In that wrapper, you will receive the proxied response, and you can then 1) write the proxied response to the original `res` and 2) cache the response as desired.
