### ISSUE TITLE
 How to configure nginx

### ISSUE THREAD

**Issue by icipiqkm** [Rob--W/cors-anywhere#121]
Everything works fine in the local area, but when using the nginx reverse proxy it prompts No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is thus not Allowed access. The response had HTTP status code 502. I am a novice and do not understand how to configure nginx. Thanks very much for your help.

server {
    listen 2001;
    location / {
        # proxy_set_header X-Real-IP $remote_addr;
        # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # proxy_set_header Host  $http_host;
        # proxy_set_header X-Nginx-Proxy true;
        # proxy_set_header Connection "";
        proxy_pass http://127.0.0.1:2000;
        proxy_redirect default;
         proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        # proxy_set_header 'Access-Control-Allow-Origin' '*';
        
    }
}

As long as it doesn't work well with nginx reverse proxy, I don't understand how nginx should be configured

**Comment by Rob--W** [comment]
Your error message shows port 4200, while the Nginx is configured to listen on port 2001 and forward requests to 2000. Moreover, I don't see how this question is related to my project, hence I'm closing the issue.

If the question actually involves the use of CORS Anywhere, please include the necessary details of your setup. To test whether the server is able to handle requests, use `curl` so you can see the actual response headers and body.
