### ISSUE TITLE
Cors Anywhere - Application Error

### ISSUE THREAD

**Issue by kayleoss** [Rob--W/cors-anywhere#128]
Seems like the application is down: 

https://cors-anywhere.herokuapp.com/
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command

One of my apps depends on cors, I'm wondering if this will be fixed?

**Comment by Rob--W** [comment]
It's up and running again. My server is really busy, I see lots of (radio) streaming sites in the logs.
