### ISSUE TITLE
how to set CORS with mobile mode

### ISSUE THREAD

**Issue by CracKerMe** [Rob--W/cors-anywhere#130]
i've read the related issues about my questions, but i wanna how to think about solving ways.

info: a website need cors provide the navigator as mobile, when i use this `cors-anywhere` ,it's useless.

can you tell me how to change some code to relize this demands

**Comment by Rob--W** [comment]
These days, the fetch specification does not mark `User-Agent` as a forbidden header any more. Firefox (and Edge?) already allow the `User-Agent` header to be overridden (via `setRequestHeader` in XMLHttpRequest; via `headers` in `fetch`). Chrome does not support this feature yet: https://bugs.chromium.org/p/chromium/issues/detail?id=571722

If your application only needs to work in Firefox, just set the `User-Agent` header at the client's side.

If that is not an option, use the `setHeaders` option of CORS Anywhere (as documented at https://github.com/Rob--W/cors-anywhere#server ). If you are lazy, you could fork this project, edit `server.js` and add `setHeaders: {'User-Agent': 'your UA string here'},` to the object parameter of `createServer` in https://github.com/Rob--W/cors-anywhere/blob/master/server.js
