### ISSUE TITLE
Application seems to be down

### ISSUE THREAD

**Issue by Istanful** [Rob--W/cors-anywhere#131]
Hi!

Just wanted to tell you that the application seems to be down. I'm just seeing the Application error screen when accessing it.
<img width="603" alt="skarmavbild 2018-08-26 kl 18 09 48" src="https://user-images.githubusercontent.com/10728852/44630298-5223dc00-a95b-11e8-9759-3cbe2505dee7.png">

Since I have no access to the app I can give you no further information. :)

**Comment by Rob--W** [comment]
I restarted the app.

**Comment by Istanful** [comment]
Sweet. That was swift haha. Thanks 👍
