### ISSUE TITLE
unexpected server response (400) while retrieving pdf 

### ISSUE THREAD

**Issue by Madasamy26** [Rob--W/cors-anywhere#132]
We have deployed our application  in aws , while accessing the from Chrome its work fine but from IE 11 its throwing error 400. meanwhile accessing local build of application from IE 11 and chrome, its working fine, **so can you help me for taking this as build instead of directly running node server.js ????.**

**Comment by Rob--W** [comment]
> from IE 11 its throwing error 400

Likely the same issue as in https://github.com/Rob--W/cors-anywhere/issues/113#issuecomment-384611461

> so can you help me for taking this as build instead of directly running node server.js ????.

I have no idea what you're asking here.
