### ISSUE TITLE
Clone works on local but not on Heroku

### ISSUE THREAD

**Issue by digiboons** [Rob--W/cors-anywhere#135]
Firstly thanks for cors-anywhere .

I install it on local machine it works great but install on heroku it didnt console.log out cors working even cors-anywhere.heroku doesnt work .

this is error when i try cors_anywhere.herokuapp.com

`GET https://cors-anywhere.herokuapp.com/http://www.doviz.com/api/v1/currencies/USD/latest 503 (Service Unavailable)
(anonymous) @ fetch.html:52
fetch.html:1 Failed to load https://cors-anywhere.herokuapp.com/http://www.doviz.com/api/v1/currencies/USD/latest: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:5500' is therefore not allowed access. The response had HTTP status code 503. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
fetch.html:1 Uncaught (in promise) TypeError: Failed to fetch`

is there any other configiration for Heruko ?

Thanks in Advance

**Comment by Rob--W** [comment]
The request fails because the request timed out. This is not an issue with CORS Anywhere but the destination server. Perhaps your website blocks or ignores requests from Heroku servers.
