### ISSUE TITLE
cors-anywhere on a2 hosting server

### ISSUE THREAD

**Issue by saumitra619** [Rob--W/cors-anywhere#136]
i have setup cors-anywhere on heroku and other on a2 hosting server, api/post working fine with heroku server but not with my a2 hosting server.

-- "https://testmycors.herokuapp.com/https://--api-name--6443/api/v2" works great

on a2hosting - "http://--my url--/proxy?url=http://--api-name--:6443/api/v2" 

results in Error: connect ETIMEDOUT x.x.x.x:443

`const express = require('express');
const app = express();
const port = 49405;
const corsAnywhere = require('cors-anywhere');
const httpProxy = require('http-proxy');

let proxy = corsAnywhere.createServer({
   originBlacklist: [],
   originWhitelist: [],
   requireHeader: ['origin', 'x-requested-with'],
   removeHeaders: ['cookie', 'cookie2','x-request-start'],
   setHeaders :{"x-powered-by": "CORS Anywhere"},
   redirectSameOrigin: true,
   httpProxyOptions: {
        secure:true
    },
});

/* Attach our cors proxy to the existing API on the /proxy endpoint. */

app.use('/proxy', (req, res) => {
    req.url = req.url.replace('/?url=','/');
    proxy.emit('request', req, res);
 });

app.get('/', (req, res) => res.send('This API enables cross-origin requests to anywhere.'));

i cannot seems to figure out the issue ..why its not working from my server

**Comment by Rob--W** [comment]
It seems that your search term is incorrect. Replace

```
req.url = req.url.replace('/?url=','/');
```

with

```
req.url = req.url.replace('/proxy?url=', '/');
```
