### ISSUE TITLE
Use SOCKS5 Proxy

### ISSUE THREAD

**Issue by hitmanex** [Rob--W/cors-anywhere#138]
How do I make cors-anywhere use a local socks proxy.

reason being I don't want my local ip leaked when someone uses cors-anywhere

**Comment by Rob--W** [comment]
Only http(s) proxies are supported, via environment variables: https://github.com/Rob--W/proxy-from-env#environment-variables

SOCKS5 proxies are not supported, and I will probably not add support for them.

**Comment by vhermecz** [comment]
Potential workaround is to use Privoxy to do http=>socks dispatching
See: https://superuser.com/a/484212/277157
