### ISSUE TITLE
Heroku App down

### ISSUE THREAD

**Issue by auseika** [Rob--W/cors-anywhere#139]
Hi, looks like heroku proxy is down.

**Comment by Rob--W** [comment]
Looks up and running to me.

**Comment by auseika** [comment]
Ok now, thanks.

**Comment by silui** [comment]
I still have trouble, it was running for a sec now it seems to be down again.

**Comment by Rob--W** [comment]
It is still up here. I have started to pipe logs to a temporary file, please let me know if you experience a failure again. Then I'll check the logs.

**Comment by auseika** [comment]
Yes, it was running and now there's 503 again.
The problems started like 3-4 hours ago or so.

**Comment by auseika** [comment]
Up again, thank you.

**Comment by sheddup** [comment]
down again? (application error, 503)
