### ISSUE TITLE
https://cors-anywhere.herokuapp.com is down

### ISSUE THREAD

**Issue by junjchen** [Rob--W/cors-anywhere#140]

**Comment by takasimiz** [comment]
@junjchen It has been until several hours ago but now seems to be running.

**Comment by Rob--W** [comment]
Over 80% of the requests came from radio streaming sites (#129). I have now blocked these (instead of subjecting them to the standard rate-limiting rules). Hopefully the server load will go back to more reasonable levels if/once these radio sites stop using CORS Anywhere.
