### ISSUE TITLE
CORS ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by milanbk** [Rob--W/cors-anywhere#144]
I tried to call AWSJavascript Cloudsearch method.
Initially, it gave me error saying **"Access to XMLHttpRequest at "" from origin has been blocked by CORS policy.. does not pass access control check..."**
After adding code to run cors anywhere, I am getting error:-

**AppComponent.html:2 ERROR ReferenceError: __dirname is not defined
  at getHandler (cors-anywhere.js:253)**

Please let me know how to fix this.

**Comment by Rob--W** [comment]
This repository contains files for the server. To use it at the client's side, just prepend the location of the CORS Anywhere server, e.g. at shown at https://github.com/Rob--W/cors-anywhere#client
