### ISSUE TITLE
Infinite redirect with website

### ISSUE THREAD

**Issue by NicolaSpreafico** [Rob--W/cors-anywhere#149]
Hello,
first of all thank you for sharing this project, I needed something like this to bypass a CORS implementation.

I was trying with your public server just to understand how it works and I found a problem of infinite redirect:

Here is a simple snippet: https://jsfiddle.net/oaefjkm6/

Here is some additional info from Chrome console:

General:

> Request URL: https://cors-anywhere.herokuapp.com/https://www.unieuro.it/online/
> Request Method: GET
> Status Code: 301 Moved Permanently
> Remote Address: 34.204.208.235:443
> Referrer Policy: no-referrer-when-downgrade

Response Headers:

> Access-Control-Allow-Origin: *
> Access-Control-Expose-Headers: date,server,location,vary,content-language,content-encoding,connection,transfer-encoding,content-type,x-final-url,access-control-allow-origin
> Connection: keep-alive
> Content-Language: it
> Content-Type: text/html;charset=UTF-8
> Date: Sat, 12 Jan 2019 19:41:44 GMT
> Location: https://cors-anywhere.herokuapp.com/https://www.unieuro.it/online/
> Server: Apache
> Transfer-Encoding: chunked
> Vary: User-Agent,Accept-Encoding
> Via: 1.1 vegur
> X-Cors-Redirect-1: 301 https://www.unieuro.it/online/
> X-Cors-Redirect-2: 301 https://www.unieuro.it/online/
> X-Cors-Redirect-3: 301 https://www.unieuro.it/online/
> X-Cors-Redirect-4: 301 https://www.unieuro.it/online/
> X-Cors-Redirect-5: 301 https://www.unieuro.it/online/
> X-Final-Url: https://www.unieuro.it/online/
> X-Request-Url: https://www.unieuro.it/online/

Request Headers:

> Referer: https://fiddle.jshell.net/_display/
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

I tried with many different websites and this is the only one where I'm getting this problem.
Is it a configuration problem of the destination website?

Here you can see the amount of times that the request redirected to itself:
![image](https://user-images.githubusercontent.com/12278553/51077757-fa3c0680-16aa-11e9-87f1-034edb283958.png)

Thanks

**Comment by Rob--W** [comment]
This is not an issue with CORS Anywhere, but probably the website itself.

When I start a local CORS Anywhere server, the request succeeds. So this might be an IP or geo-IP based, site-specific issue.
