### ISSUE TITLE
Just starting

### ISSUE THREAD

**Issue by philb123** [Rob--W/cors-anywhere#151]
Is there a programmer that could help me implement this ?
I am struggling to set this up

**Comment by philb123** [comment]
Got it sorry for the confusion,  I read a little further, saw your section on setting up on heroku.  This looks easier than setting up on my own windows server.  I still have a question on the ratelimit, whitelist , blacklist are these just a file with the such as the 1 5 example.com in it , in the lib folder.  

Thanks for your help

**Comment by Rob--W** [comment]
If you're going to use the default server implementation of CORS Anywhere, then this is the relevant part of the documentation: https://github.com/Rob--W/cors-anywhere#demo-server

More details on the ratelimit syntax is at https://github.com/Rob--W/cors-anywhere/blob/4814647a9d21f14858da282387a4295c17f2851d/lib/rate-limit.js#L3-L20

If the default server is not flexible enough for your needs, then you can create a new server implementation, based on https://github.com/Rob--W/cors-anywhere/blob/4814647a9d21f14858da282387a4295c17f2851d/server.js (the documentation for the server as a library is at https://github.com/Rob--W/cors-anywhere#server)

**Comment by philb123** [comment]
I have looked through the documentation, where do I set the rate limit for deploying to heroku ?  If I was going use your rate limit  100 3  testdomain.com ?   tried runnning the export from the heroku cli,  Sorry for keep asking questions

**Comment by Rob--W** [comment]
Via an environment variable, see https://devcenter.heroku.com/articles/config-vars
