### ISSUE TITLE
Why does proxy server return CORS errors

### ISSUE THREAD

**Issue by Kirill-Ovc** [Rob--W/cors-anywhere#153]
I try to send Post and Get requests with herokuapp proxy, but I get these errors:

```
POST https://cors-escape.herokuapp.com/https://targetsite 404 (Not Found)
Access to fetch at 'https://cors-escape.herokuapp.com/https://targetsite' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
Code on client application is simple:
```
const response = await fetch(url, {
      method: 'POST',
      //mode: 'no-cors',
      body: JSON.stringify(postData),
    })
```

With "mode: 'no-cors' " I also get 404 (Not Found).
"targetsite" is site url I'm trying to get, and I get data from it in demo (https://robwu.nl/cors-anywhere.html)
I tried to run cors-escape.herokuapp on my localhost server, but get same errors.
Why am I getting errors?

**Comment by Rob--W** [comment]
Because it's not "cors-escape", but "cors-anywhere".
