### ISSUE TITLE
Can't make any request through the proxy

### ISSUE THREAD

**Issue by IdleSolution** [Rob--W/cors-anywhere#159]
It worked fine yesterday but now when I'm trying to make a request like this https://cors-anywhere.herokuapp.com/link_to_api it just loads for like a minute and then throws CORS error. When making request through Postman the following response is given: 

<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>

Can somebody help?

**Comment by theo-armour** [comment]
me too

If I enter the following address bar in latest Chrome/FF/Edge on Win10 and on Chromebook:

https://cors-anywhere.herokuapp.com///robwu.nl/dump.php

I get 

Missing required request header. Must specify one of: origin,x-requested-with

BTW, this script is wonderful

**Comment by Rob--W** [comment]
> If I enter the following address bar (.,..) I get
> Missing required request header. Must specify one of: origin,x-requested-with

This is normal, only cross-origin requests (with the Origin header) or requests with the X-Requested-With request header are accepted to avoid direct requests (i.e. visiting via the address bar).

Based on the observation that the server is reachable but gives an error page (HTTP 503), I believe that the server is overloaded. This is tracked in #155.

**Comment by theo-armour** [comment]
@Rob--W 

Thank you for the speedy weekend response.

I understand that visiting via the address bar is to be discouraged. Such visits, however, were working just fine for a very long time. They were a wonderful way of checking quickly that the link just works. This feature stopped working a while ago and this makes me sad. So it goes

And, yes, I also now see the HTTP 503 errors and am reassured that it's a server issue and not a change the underlying workflow. Thanks again.

**Comment by Rob--W** [comment]
> I understand that visiting via the address bar is to be discouraged. Such visits, however, were working just fine for a very long time.

That can't be. Direct visits were already blocked in the very first release of the server many years ago.

**Comment by theo-armour** [comment]
My bad. I wonder what I mis-remembered. ;-)
