### ISSUE TITLE
Error on Post Request

### ISSUE THREAD

**Issue by SP105** [Rob--W/cors-anywhere#16]
Hi, I'm using the proxy for a mobile app with phonegap. I can do the GET request with any problem, but when I'm doing the POST request, the response is the following: "Not found because of proxy error: Error: CERT_HAS_EXPIRED"

The header is this:

![24-11-2014 16-58-40](https://cloud.githubusercontent.com/assets/1672162/5172048/5d056f4c-73fb-11e4-9585-f4739bf479bf.png)

**Comment by darkrole** [comment]
im having the same error but i dont understand where do i need to insert this in the server code "NODE_TLS_REJECT_UNAUTHORIZED=0"

**Comment by rizkhal** [comment]
i have the same problem in vps, i am using jquery for call external API but get the same error, how i can fix it?

**Comment by imsourya** [comment]
I was trying from browser and getting this =>  **Error: unable to get local issuer certificate**
I solved this issue by just one change in the cor-anywhere code 

in file **cors-anywhere.js**  at line 418  Just change the line
 
`process.env.NODE_TLS_REJECT_UNAUTHORIZED !== '0',`

to 

`process.env.NODE_TLS_REJECT_UNAUTHORIZED == '0',`

It worked!

**Comment by Rob--W** [comment]
@imsourya 
You shouldn't be changing the implementation like that, but set the `NODE_TLS_REJECT_UNAUTHORIZED=0` environment variable before starting the library.

**Comment by imsourya** [comment]
> @imsourya You shouldn't be changing the implementation like that, but set the `NODE_TLS_REJECT_UNAUTHORIZED=0` environment variable before starting the library.

Yes @Rob--W , You are right, We shouldn't change the code, Actually I was facing problem in setting environment variable in windows system so tried using this.
