### ISSUE TITLE
cors-anywhere.herokuapp.com isn't working

### ISSUE THREAD

**Issue by Ibit-to** [Rob--W/cors-anywhere#162]
We got a report on https://github.com/Ibit-to/google-unlocked/issues/9 that the proxy is not working anymore. Any ideas?

**Comment by Rob--W** [comment]
This is not an issue with CORS Anywhere. The remote server seems to have blocked access by the CORS Anywhere server, likely because you have triggered too many requests (which doesn't seem to be hard to hit; if I use curl I immediately get a "HTTP 429 Too Many Requests" response).
