### ISSUE TITLE
CORS Anywhere is following an XSL href in a XML file

### ISSUE THREAD

**Issue by MarkStokes-outlook** [Rob--W/cors-anywhere#166]
Hi,

Firstly thanks for the great work with CORS Anywhere.  I am just trying to set up my own server on Azure Web App (using Linux) and have a strange problem. I am trying to load an RSS feed from the BBC. This works in postman, but not on my sever or the live demo server. I am sure it used to work on the demo server until recently, but could be wrong.

In Postman, I am sending a request to the following URL, with the 'origin, x-requested-with' header: https://[snip].azurewebsites.net/feeds.bbci.co.uk/news/rss.xml

![image](https://user-images.githubusercontent.com/17313109/56275096-f4b1ea80-60f7-11e9-9319-45667c1217be.png)

But when I try and do it from the browser (adding the header with a plugin) I get the following error.
![image](https://user-images.githubusercontent.com/17313109/56275236-380c5900-60f8-11e9-82fa-e3c882ffac4f.png)

It appears to be following the href in the XSL stylesheet reference and failing.

I get the same issue when querying the BBC RSS Feed from an Ajax call. Other feeds work fine.

It also fails on the live demo server: https://cors-anywhere.herokuapp.com/feeds.bbci.co.uk/news/rss.xml

I would appreciate any help as I can't work out how I should fix it.  I also have another issue with putting the protocol of the target site in the URL, but I will open a different ticket about that (it appears to be a known issue with Azure normalising URLS).

Thanks

Mark

**Comment by Rob--W** [comment]
>  I am trying to load an RSS feed from the BBC.

How? `fetch`? Loading as a frame?
CORS Anywhere itself is just acting as a proxy. It is your responsibility to make sure that there are no unexpected additional requests.

> It also fails on the live demo server: https://cors-anywhere.herokuapp.com/feeds.bbci.co.uk/news/rss.xml

Works fine for me. I only see 1 request. I tried

```
fetch('https://cors-anywhere.herokuapp.com/feeds.bbci.co.uk/news/rss.xml');
```

and

```
var x = new XMLHttpRequest();
x.open('get', 'https://cors-anywhere.herokuapp.com/feeds.bbci.co.uk/news/rss.xml');
x.send()
```

**Comment by MarkStokes-outlook** [comment]
> > I am trying to load an RSS feed from the BBC.
> 
> How? `fetch`? Loading as a frame?
> CORS Anywhere itself is just acting as a proxy. It is your responsibility to make sure that there are no unexpected additional requests.
> 
> > It also fails on the live demo server: https://cors-anywhere.herokuapp.com/feeds.bbci.co.uk/news/rss.xml
> 
> Works fine for me. I only see 1 request. I tried
> 
> ```
> fetch('https://cors-anywhere.herokuapp.com/feeds.bbci.co.uk/news/rss.xml');
> ```
> and
> 
> ```
> var x = new XMLHttpRequest();
> x.open('get', 'https://cors-anywhere.herokuapp.com/feeds.bbci.co.uk/news/rss.xml');
> x.send()
> ```

**Comment by MarkStokes-outlook** [comment]
Oops! I didn't meant to close the issue.

I am testing with Postman, Chrome browser (with a plugin to add headers) and ultimately with an AJAX Get, which is where my final code will be.

```
$ajq.ajax('https://cors-anywhere.herokuapp.com/feeds.bbci.co.uk/news/rss.xml', {
    accepts: {
        xml: `application/rss+xml`
    },
    headers: {
        'origin': `x-requested-with`
    },
    crossDomain: true,
    dataType: `xml`,
    success: function (data) {
        resolve(data);
    },
    error: function (error) {
        console.log(error);
        logException(`${WidgetName} -> `, false, JSON.stringify(error));
        reject(error);
    }
});
```

**Comment by Rob--W** [comment]
First, don't set the `Origin` header. It is automatically added by web browsers.

Secondly, what jQuery version are you using? With jQuery 3.4.0 I am not getting additional requests. I also tried 2.0.0 without experiencing what you've mentioned.

**Comment by MarkStokes-outlook** [comment]
Interesting.

I just setup another test and using the following I am getting results as I expect:

```
$.ajax('https://[snip].azurewebsites.net/feeds.bbci.co.uk/news/rss.xml', {
    accepts: {
        xml: 'application/rss+xml'
    },
    crossDomain: true,
    dataType: 'xml',
    success: function (data) {
        console.log(data);
    },
    error: function (error) {
        console.log(error);
    }
});
```

Let me plug this back into my main app and see if continues to work.

Thanks

**Comment by MarkStokes-outlook** [comment]
I believe I now have this working.
