### ISSUE TITLE
Error: getaddrinfo ENOTFOUND https https:80

### ISSUE THREAD

**Issue by geovannefduarte** [Rob--W/cors-anywhere#167]
Hi,
Due the limitation of number of requests per period I'm trying to host cors-anywhere on my server.
Since my application runs on 8080, I've changed the port to run on 8888 and proxy passed on nginx (https://my-website.com/cors/).

The issue is that when I put the protocol on the URL I get the following error `Not found because of proxy error: Error: getaddrinfo ENOTFOUND https https:80`

For GET requests works perfectly if I don't put the protocol on the URL, for example:
Returns correctly: `GET - https://my-website.com/cors/api.cartolafc.globo.com/esquemas`
Returns error: `GET - https://my-website.com/cors/https://api.cartolafc.globo.com/esquemas`

Unfortunately I can't use request without the protocol because when I send POST request I receive the error `Not found because of proxy error: Error: getaddrinfo ENOTFOUND https https:80`. Without the protocol, the request are been made using GET, which returns status code 405 since the API expect an POST request.
Returns error: `POST - https://my-website.com/cors/https://api.cartolafc.globo.com/esquemas`
Returns error: `POST - https://my-website.com/cors/api.cartolafc.globo.com/esquemas` (request upgrade to GET)

Do you have any thoughts on what I'm missing?

Thanks in advance

**Comment by Rob--W** [comment]
It seems that your nginx configuration converts double slashes to one slash.
You haven't shown your nginx config, but since it happens very often, I think that your problem can be fixed by following the instructions at https://github.com/Rob--W/cors-anywhere/issues/143#issuecomment-452468128

**Comment by geovannefduarte** [comment]
Indeed, that was the problem
Thank you so much and keep up the great work =)

**Comment by pradeepsathyan** [comment]
Hi,
I am having the same issue on Windows Server which I am using Nodejs run as Reverse Proxy.
Here is the error code : "Not found because of proxy error: Error: getaddrinfo ENOTFOUND https"

I have tried every possible aways couldn't found any solution.

Thanks

**Comment by madhav411** [comment]
Hi,
I am trying to setup the cors-anywhere in my K8s Cluster.I used this docker-image for cors-anywhere setup i.e; *testcab/cors-anywhere* and i don't know what are the variables that i have to set to make it. Can you please help me [I am a newbie to nodejs]

Thanks
