### ISSUE TITLE
Question: How do I get this to work with a VPN firewall?

### ISSUE THREAD

**Issue by ychaker** [Rob--W/cors-anywhere#170]
I have an extreme case where the app that I'm working on takes in a URL to a Solr instance provided by the user and uses that to return search results.
In a previous version I was using `jsonp` to get around the CORS issue, but newer versions of angular changed how `jsonp` works and broke the code I had, so I switched to using you `cors-anywhere` solution (thank you for this btw!).
It works, EXCEPT, when the Solr instance is behind a VPN. In the past the app worked because all of the requests are going through the browser, so they are coming from within the VPN. Now, with the proxy, the calls are coming from the proxy server so they can't go through.

Is there a way around that? 
Or is there a way to implement the proxy "in the browser" instead of on a different server? (I don't know if this even makes sense)

I'm hoping that someone has run into this and found a solution and can share here.
Thanks!

**PS:** This configuration sounds like it would be shady, but it's not. The app that I work on is a tool used by devs to tweak their search engines, so they are willingly providing access to their search engine to the tool, and we don't store anything. (in case someone was wondering)

**Comment by Rob--W** [comment]
> Is there a way around that?

Of course not. A server cannot pretend to be using the VPN of the client.

> Or is there a way to implement the proxy "in the browser" instead of on a different server? (I don't know if this even makes sense)

You could start CORS Anywhere on localhost (`git clone` the repository, `npm install` the dependencies and then `node server.js`) . But if you have sensitive data within your network, you should make sure to set a whitelist of sites, to avoid inadvertently exposing the data to any site. To set up the whitelist, see https://github.com/Rob--W/cors-anywhere/blob/master/README.md#demo-server

You can also use a browser extension that modifies the request to add the necessary CORS headers.
