### ISSUE TITLE
Cors Anywhere is down

### ISSUE THREAD

**Issue by chitianhao** [Rob--W/cors-anywhere#171]
It crashes most of the time and works sometimes.
```
    axios.get(`${'https://cors-anywhere.herokuapp.com/'}https://api.yelp.com/v3/businesses/search`, {
      headers: {
        'Authorization': `Bearer ITSKhNoa4exeX_bVQ5_3q44kTeAvTJWOq05ilkdTkTLK7ShsqVpDWL89_5R5O3e3x7paO7-Ugj-rvLUcivOfLxq8v51-TKKnwSGVCHePcGvied7biNPvF3gpKmayXHYx`
      },
      params: {
        categories: this.state.category_map[this.state.category],
        location: this.state.location,
        term: this.state.keyword,
        open_now: this.state.open_now,
        sort_by: this.state.sort_map[this.state.sort_idx]
      }
    }).then((res) => {
      this.setState({
        result: res.data.businesses
      });
    })
      .catch((err) => {
        console.log(err)
      })
```

<img width="609" alt="Screen Shot 2019-05-01 at 19 43 45" src="https://user-images.githubusercontent.com/8762181/57051917-92093480-6c49-11e9-862a-4a8befc6be5d.png">

**Comment by Rob--W** [comment]
If you see HTTP status code 503 (or no response at all), then that means that CORS Anywhere is down. But in this case, the status in your screenshot is 400 Bad Request, which does not originate from CORS Anywhere itself. It is likely the actual response from Yelp.
