### ISSUE TITLE
How to make an API request to a resource which is available through VPN?

### ISSUE THREAD

**Issue by harishankards** [Rob--W/cors-anywhere#175]
Hi,

Your package perfectly works fine for public APIs. Is it possible to make the request to the resource which can only be available after connecting to the VPN?

i.e Say my system is connected to the VPN. I'm able to make the request through Postman and gets a success response. In browser, using JQuery Ajax, I'm facing CORS issue. When I appended your URL(https://cors-anywhere.herokuapp.com/) in the front followed by the resource URL, it's still facing the same issue.

So, just wanted to check if it's possible. Please let me know.

**Comment by Rob--W** [comment]
If for development purposes only, you could self-host CORS Anywhere locally, and then use localhost instead of the public CORS Anywhere demo.

Otherwise, this is not possible. The public CORS Anywhere demo cannot access the resources that are private behind a VPN.
