### ISSUE TITLE
30 second request timeout error

### ISSUE THREAD

**Issue by MysteryPancake** [Rob--W/cors-anywhere#176]
I am running a CORS Anywhere server on Heroku. All the requests I send are guaranteed to have a response time of over 30 seconds, meaning Heroku always throws this error:

```
heroku[router]: at=error code=H12 desc="Request timeout" method=POST
```
This causes a 503 error on the client, as seen in #20 and #155.

I am trying to get around this by using [http-delayed-response](https://github.com/extrabacon/http-delayed-response).
I keep encountering an interruption error (most likely because I don't know what I'm doing):
```
heroku[router]: sock=client at=warning code=H27 desc="Client Request Interrupted" method=POST
```
This is my current code:
```
const host = process.env.HOST || "0.0.0.0";
const port = process.env.PORT || 443;

const fs = require("fs");
const cors_proxy = require("cors-anywhere");
const DelayedResponse = require("http-delayed-response");

cors_proxy.createServer({
  originWhitelist: ["https://mysterypancake.github.io"],
  requireHeader: ["origin", "x-requested-with"],
  removeHeaders: [
    "cookie",
    "cookie2",
    "x-heroku-queue-wait-time",
    "x-heroku-queue-depth",
    "x-heroku-dynos-in-use",
    "x-request-start",
  ],
  redirectSameOrigin: true,
  httpProxyOptions: {
    xfwd: false,
  },
}).listen(port, host, function() {
  console.log("Running CORS Anywhere on " + host + ":" + port);
}).on('request', function(request, response) { // this is probably completely wrong
    var delayed = new DelayedResponse(request, response);
    delayed.start();
    response.on('end', function() {
      delayed.end();
    });
});
```
Is there a way to avoid the 30 second timeout?

**Comment by Rob--W** [comment]
Heroku expects handlers to close requests within 30 seconds (and at most 55 seconds between responses) - https://devcenter.heroku.com/articles/http-routing#timeouts

The library that you're attempting to use tries to get around this by [writing whitespace](https://github.com/extrabacon/http-delayed-response/blob/66ef607d3a4a9a72c5faa39a16f76b0b7fe4049c/index.js#L124-L125) to the response body. Writing any response body causes the headers to be flushed. When browsers encounter a non-CORS response to a cross-origin request, then the request may be terminated. It seems that the default behavior of your library is to write the first space after 100ms, which is likely before your proxied request was finished.

The library appears to primarily be designed for JSON responses, where leading whitespace is a reasonable choice for heartbeat responses. As explained above, that logic cannot be used with CORS Anywhere.

Try  [to replace the http-delayed-response library's default handler](https://github.com/extrabacon/http-delayed-response/blob/66ef607d3a4a9a72c5faa39a16f76b0b7fe4049c/index.js#L120-L123) by adding a `hearbeat` event handler that calls [`res.writeContinue()`](https://nodejs.org/api/http.html#http_response_writecontinue). `writeContinue()` sends a `HTTP/1.1 100 Continue` response line, which ought to be ignored by clients (but as it's a packet, it should count as something that keeps the connection alive). You'll also need additional logic to ensure that `writeContinue` is not called any more when CORS Anywhere is actually sending a response, maybe via `res.headersSent` property.

I haven't tried it, but if there is anything that would, then the above logic is my guess.

**Comment by MysteryPancake** [comment]
I attempted to use `writeContinue()`, but the error persists. It seems to immediately break the second anything is written to the result.

**Comment by Rob--W** [comment]
To make sure that the Node.js application works as desired (and rule out interference by the Heroku platform), I suggest that you start the server locally to check whether the connection is kept open as expected.

**Comment by gkoberger** [comment]
Heroku always times out at 30 seconds, and there's no way to change this! If you want more time, you'll need to switch platforms.
