### ISSUE TITLE
help on setup my cors-anywhere on heroku.com

### ISSUE THREAD

**Issue by damjang** [Rob--W/cors-anywhere#177]
Sorry to asking here, but I'm not so expert and don't know how to setup my cors-anywhere on heroku.com. I registered on heroku but didn't understand how to setup all to work. Can someone help a little?

**Comment by Rob--W** [comment]
How you can set this up on Heroku is documented at https://github.com/Rob--W/cors-anywhere#demo-server (make sure to follow the links).
