### ISSUE TITLE
redirecting to relative path of local url instead of proxied site

### ISSUE THREAD

**Issue by grkblood13** [Rob--W/cors-anywhere#179]
Im having an issue where when I load a remote media playlist the segments are being redirected to a url pointing to the site attempting the proxy instead of the site hosting the files. For example, consider the site I'm hosting is http://www.local.com, and it's attempting to proxy playlist http://remote.com/playlist.m3u8 via cors-anywhere at http://local.com/proxy/http://remote.com/playlist.m3u8

playlist.m3u8 contains the following:

#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.0,
movieA.ts
#EXTINF:10.0,
movieB.ts

cors-anywhere will successfully proxy the first request, but the relative paths inside of the playlist will be fetched as http://www.local.com/movieA.ts and http://www.local.com/movieB.ts, when the expected result would actually be a fetch of http://www.remote.com/movieA.ts and http://www.remote.com/movieB.ts.

**Comment by Rob--W** [comment]
CORS Anywhere itself does not attempt to resolve URLs in responses. It is your responsibility as a client (web app) to resolve the URLs yourself.

**Comment by grkblood13** [comment]
Any chance you would be willing to mark this as a feature enhancement?

**Comment by Rob--W** [comment]
No. Supporting this means significant complexity to parse and modify the response body, which is outside the scope of this project.

It is the responsibility of the client to resolve those URLs. You should look at your application or library that you're using; Relative URLs are not automagically resolved to the proxy URL. Something in your code is responsible for resolving the URL. If you find how it's done, then you can also modify it to resolve to the proxied URL.

**Comment by grkblood13** [comment]
Roger that. Thanks for the advice.

**Comment by asheroto** [comment]
Hi there,

I'm facing a similar question, but rather want to approach it a bit different way: by modifying the body.

I've been searching for a way to do this, and I understand you can specify [httpProxyOptions](https://github.com/http-party/node-http-proxy#options).

Where exactly should I specify/place the code mentioned for cors-anywhere using the modify body technique? I tried doing...

```
    var option = {
      target: target,
      selfHandleResponse : true
    };
    cors_proxy.on('proxyRes', function (proxyRes, req, res) {
        var body = [];
        proxyRes.on('data', function (chunk) {
            body.push(chunk);
        });
        proxyRes.on('end', function () {
            body = Buffer.concat(body).toString();
            res.end(body.replace("https://","https://URLHERE/https://");
        });
    });
    cors_proxy.web(req, res, option);
```

after `}).listen(port, host, function` but I'm not strong enough with NodeJS to understand what to do here. Thanks for your help and patience with this. I think this will solve the original poster's question as well as mine. :-)

**Comment by asheroto** [comment]
Or can I somehow modify `cors_proxy.createServer` to use the traditional function method such as...

```
cors_proxy.createServer((req, res) => {
```

And modify the body via response there?
