### ISSUE TITLE
Question Fetch

### ISSUE THREAD

**Issue by zandercodes** [Rob--W/cors-anywhere#181]
This works perfectly with XMLHttpRequest but not with Fetch.
Why?

Best regards
ZanderCodes

**Comment by Rob--W** [comment]
It should work with `fetch` as well. Have you set the `mode` flag, to any other value than `"cors"`? Can you provide an example that fails unexpectedly?

**Comment by zandercodes** [comment]
I use vuejs as SPA. I load this in the vue SPA in beforeMount. Debugger also normaly. Make request with fetch and this error: 

> Cross-origin request blocked: The same source rule prohibits reading the external resource on https://www.example.com (Reason: CORS attack failed)

I replace the orginal request Domain.

**Comment by zandercodes** [comment]
I have import the module [xhook](https://www.npmjs.com/package/xhook) and 
`xhook.before((req) => {
  req.url = 'https://cors-anywhere.herokuapp.com/' + req.url
})`
in the beforeMount methode and now replace all urls.

**Comment by Rob--W** [comment]
You should only use CORS Anywhere for cross-origin requests, not for same-origin requests.

The "CORS attach failed" response is not from CORS Anywhere, nor from the browser. Therefore I'll close this issue.

If you're claiming that XHR works but fetch fails, then you need to show the code that constructs the XHR request and the code that calls `fetch`. Without this, there is not much to go on.
