### ISSUE TITLE
Does not work with http:// or https:// prefix and Nginx

### ISSUE THREAD

**Issue by MrXyfir** [Rob--W/cors-anywhere#184]
First of all I want to say I don't think this is an issue with your code but I can't figure this out and maybe you can help.

I'm trying to proxy non-Wikipedia wikis from my app.

-----

**Examples:**

https://app.illuminsight.com/proxy/http://lotr.wikia.com/api.php?action=query&prop=revisions&rvprop=content&maxlag=5&rvslots=main&origin=*&format=json&redirects=true&titles=Dwarves

gives the error `Not found because of proxy error: Error: getaddrinfo ENOTFOUND http`, but

https://app.illuminsight.com/proxy/lotr.wikia.com/api.php?action=query&prop=revisions&rvprop=content&maxlag=5&rvslots=main&origin=*&format=json&redirects=true&titles=Dwarves

works fine. Note the lack of `http://`. Similarly,

https://app.illuminsight.com/proxy/https://lotr.wikia.com/api.php?action=query&prop=revisions&rvprop=content&maxlag=5&rvslots=main&origin=*&format=json&redirects=true&titles=Dwarves

errors, but

https://app.illuminsight.com/proxy/lotr.wikia.com:443/api.php?action=query&prop=revisions&rvprop=content&maxlag=5&rvslots=main&origin=*&format=json&redirects=true&titles=Dwarves

does not. Again, note the lack of `https://`

**nginx config:**

```
location /proxy/ {
  proxy_pass http://localhost:2702/;
  proxy_pass_request_headers on;
  proxy_connect_timeout 1200;
  proxy_send_timeout 1200;
  proxy_read_timeout 1200;
  proxy_set_header Origin 'https://app.illuminsight.com';
  send_timeout 1200;
}
```

**proxy server:**

https://github.com/xyfir/illuminsight/blob/master/server/app.ts#L69

-----

Any ideas?

**Comment by Rob--W** [comment]
See https://github.com/Rob--W/cors-anywhere/issues/143#issuecomment-452468128

And use `127.0.0.1` instead of `localhost`.

And do NOT add `proxy_set_header Origin 'https://example.com';`. Doing so turns your server into an open proxy, and makes your website vulnerable to cross-site scripting, which is a major security issue.

**Comment by MrXyfir** [comment]
Thanks! You're amazing.

I'm aware of the vulnerability, it's just for testing since forwarding the header is giving me issues.

**Comment by Rob--W** [comment]
If the `Origin` header is absent due to the fact that the proxy is hosted at the same domain as your app, set the `X-Requested-With` request header in your web application, instead ofadding a fake `Origin` header to all incoming requests.

**Comment by MrXyfir** [comment]
Thanks for the advice, but I'm still having trouble.

```
proxy_set_header X-Requested-With $http_origin;
# doesn't work, and neither does
proxy_set_header Origin $http_origin;
```

Sorry to bug you again, I really need to learn Nginx's configuration better.
