### ISSUE TITLE
Wildcard support for whitelist

### ISSUE THREAD

**Issue by thisismydesign** [Rob--W/cors-anywhere#187]
Love the project. We'd like to make use of wildcards in the whitelist config. Found one mention of this here but not much else: https://github.com/Rob--W/cors-anywhere/issues/67#issuecomment-286089013

Or even better, regex support ;)

**Comment by Rob--W** [comment]
What exacty are you looking for? It's not clear whether you're looking for a way to whitelist origins, or a way to restrict the permitted destinations.

**Comment by thisismydesign** [comment]
Thanks for the quick reply. I'm looking to whitelist origins but I think this could be useful for both. The actual use case is enabling generic developer and GitHub Pages access by something like `localhost*` and `*.github.io`.

**Comment by Rob--W** [comment]
If you use the default [`server.js`](https://github.com/Rob--W/cors-anywhere/blob/master/server.js), then you can use the `CORSANYWHERE_RATELIMIT` environment variable to control access (with literal strings or regular expressions). For its syntax, see https://github.com/Rob--W/cors-anywhere/blob/master/lib/rate-limit.js

**Comment by thisismydesign** [comment]
Hm, right, thanks. However, I would also like to match the ports. As I see the logic there is quite complex, are there any technical issues I'm missing with simply using something like this:

```js
!corsAnywhere.originWhitelist.some(function(whitelistPattern) { whitelistPattern.match(origin) })
```

Besides that, all entries would have to be written as regexes. But I'd be happy to use my own version unless I'm missing something.

As a side note, I would expect to use the whitelist setting for this. The response code is the right one that way and if I understand the rate limit feature correctly you can only set a single setting there so using it for this purpose would already consume that.

**Comment by thisismydesign** [comment]
https://github.com/Rob--W/cors-anywhere/compare/master...c-hive:master#diff-3afac545af08021c9827e4bddf3d8557

https://github.com/Rob--W/cors-anywhere/compare/master...c-hive:master#diff-78c12f5adc1848d13b1c6f07055d996e

In case you're interested in pulling these.

**Comment by Rob--W** [comment]
> I would also like to match the ports.

The rate-limiting code does treats domains with different ports as separate origins. Here are some examples:

```sh
# Accept example.com:1234 only
CORSANYWHERE_RATELIMIT='0 1 example.com:1234'

# Accept example.com:1234 and example.com:5678
CORSANYWHERE_RATELIMIT='0 1 example.com:1234 example.com:5678'

# Same as before, but using a regexp
CORSANYWHERE_RATELIMIT='0 1 /example\.com:(1234|5678)/'

# Accept example.com, with any port
CORSANYWHERE_RATELIMIT='0 1 /example\.com(:\d+)?/'
```

> I would expect to use the whitelist setting for this. The response code is the right one that way and if I understand the rate limit feature correctly you can only set a single setting there so using it for this purpose would already consume that.

The origin whitelist is intentionally kept simple, as a list of permitted origins. If you want to customize the behavior of rate-limiting, then you can use CORS Anywhere as a library, and pass a custom `checkRateLimit` function (with a custom error message, if you wish). Besides the previously referenced rate-limit.js, you can also see other examples of `checkRateLimit`, at: https://github.com/Rob--W/cors-anywhere/blob/4814647a9d21f14858da282387a4295c17f2851d/test/test.js#L577-L607

**Comment by thisismydesign** [comment]
Thanks, I was confused about ports and thought they have to be listed explicitly _1 by 1_.

It's clear now that there's a way to implement this using existing functionality. Perhaps you could point this out the readme as I think it's a useful feature, but in any case, this issue can be closed.

**Comment by jsejcksn** [comment]
Hi @Rob--W: Instead of opening a new issue, I will add these related questions here:

1. If I need to whitelist all subdomains for one domain, and also whitelist several other domains (without subdomains), do I use `checkRateLimit` for the subdomains and `originWhitelist` for the domains, or must I specify everything in `checkRateLimit`?

2. How is the case handled where both `originWhitelist` and `checkRateLimit` have specified values?

I was looking for documentation about wildcard subdomains, and this issue is the only relevant page that surfaced in my searching.

**Comment by Rob--W** [comment]
1. You can implement a custom `checkRateLimit` function that accepts requests from any domain (and rejects others).
2. A request must be accepted by both checks (if set). If `originWhitelist` is set, any request outside the whitelist is rejected. If `checkRateLimit` is set, any request that fails the check is rejected.
