### ISSUE TITLE
Newbie Vue.js user question....

### ISSUE THREAD

**Issue by PaulMcGuinness** [Rob--W/cors-anywhere#188]
I'm trying to use this to get around a number of CORS issues (I'm accessing lots of datasets to populate a dashboard...), and as a standalone it works perfectly!

I just can't seem to build it direct into my Vue.js app (I know it would be a bit of a loop around itself, but it'll work for me...) - whenever I try to include it and instantiate withing mounted{}, I get the following : - 

vue.runtime.esm.js:619 [Vue warn]: Error in mounted hook: "TypeError: __webpack_require__(...).createServer is not a function"

If I console.log() the object, I can see the function, I'm a bit confused.

Any advise greatly appreciated...

**Comment by Rob--W** [comment]
CORS Anywhere is a server-side (Node.js) application. Including it at the client's side has no effect.

If you are trying to use it at the server's side, share a code snippet or a link to the Github repo where your code is hosted. I'll close the issue, but if you post a comment I'll continue to reply.
