### ISSUE TITLE
How to use with a Node service which only offers normalized req.url?

### ISSUE THREAD

**Issue by jsejcksn** [Rob--W/cors-anywhere#193]
[Related discussion on spectrum.chat](https://spectrum.chat/zeit/now/cors-errors-when-using-node-builder-but-not-when-using-micro~a55220d0-0e7f-4acc-abd5-cb30409da239)

When using a "serverless" Node function on ZEIT's now.sh, I have access to `req` and `res` in the function. Here is the original code I tried:

```js
const options = {
  originWhitelist: ['http://localhost:3000'],
  requireHeader: ['origin', 'x-requested-with'],
  removeHeaders: ['cookie', 'cookie2']
};
const cors_proxy = require('cors-anywhere').createServer(options);
module.exports = (req, res) => {
  cors_proxy.emit('request', req, res);
};
```

However, it appears that the supplied `url` property on `req` is normalized, and that I cannot access the original url. An employee suggested this workaround in the function body:

```js
module.exports = (req, res) => {
  cors_proxy.emit(
    'request',
    Object.assign(req, {url: req.url.replace(':/', '://')}),
    res
  );
};
```

but trying that gave me no success. (More details at the discussion linked at the top of this issue.)

**Can you offer a suggestion for this case?** I thought about using a custom header for the destination URL, like below, but would prefer not to since it's very hacky.

```js
module.exports = (req, res) => {
  let url = '/';
  if (req.headers['x-proxied-url']) url += req.headers['x-proxied-url'];
  else url += 'iscorsneeded';
  const reqModified = Object.assign(req, {url});
  cors_proxy.emit('request', reqModified, res);
};
```

**Comment by Rob--W** [comment]
My recommendation on things to try out:

1. Try to find a way to get the original unnormalized URL.
2. If it is not possible, try to ask the (hosting) platform to not normalize the URL.
3. If that is not possible, try to assign `req.url = req.url.replace(^\/https?:\/(?!\/)/, "$&/");` before emitting `req.url` as a fragile work-around.
4. If you really need the original URL, and none of the previous options are feasible, switch to a different hosting provider.

**Comment by jsejcksn** [comment]
Thanks for the suggestions.

**Comment by jsejcksn** [comment]
For anyone else who might come across this: I decided to use a query parameter to hold the destination URL, like so:

```js
module.exports = (req, res) => {
  let url = '/';
  if (req.query._url) url += req.query._url;
  else url += 'iscorsneeded';
  const reqModified = Object.assign(req, {url});
  cors_proxy.emit('request', reqModified, res);
};
```

The methods suggested by Rob were not feasible with ZEIT, and using a static URL with variable header values conflicted with browser caching and concurrent requests due to cache locking.
