### ISSUE TITLE
A website's GET request gives an HTML Response?

### ISSUE THREAD

**Issue by vishnupsatish** [Rob--W/cors-anywhere#194]
I am using an API, which is this: http://youlink.epizy.com/?url=https://www.youtube.com/watch?v=[VIDEO_ID]. For example, if I use the video ID http://youlink.epizy.com/?url=https://www.youtube.com/watch?v=5g9iXlAIgj4 and go to that website, it works. If I do a GET request though, it doesn't work, because of CORS. I tried using CORS Anywhere for my GET request, and instead, it gave me the response text as this: I have JavaScript enabled and I am using an XMLHttpRequest.

`<html><body><script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("bbf486f74d02fd069ca9536beda40f84");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="http://youlink.epizy.com/?url=https://www.youtube.com/watch?v=7iBqEknWOiU&i=1";</script><noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>`

**Comment by Rob--W** [comment]
This is not an issue with CORS. It's the actual response of the website. When you visit that website directly, it executes some JavaScript code that redirects the visitor elsewhere.

**Comment by vishnupsatish** [comment]
So is there any way I can use this API then with or without CORS Anywhere?
