### ISSUE TITLE
Why am I always getting the error: "Missing required request header. Must specify one of: origin,x-requested-with"

### ISSUE THREAD

**Issue by aramhai** [Rob--W/cors-anywhere#196]
**Everything worked just fine until a few days ago.**

Now, every request I make returns the same error:

> Missing required request header. Must specify one of: origin,x-requested-with

for example:
https://cors-anywhere.herokuapp.com/https://www.instagram.com/adidas/

You can try for yourself, every request returns the same error.

I uploaded the code to my server and i still have the same problem.

**Comment by Rob--W** [comment]
The server will intentionally not proxy requests when you directly open the URL in a browser tab.
The "Must specify one of: origin,x-requested-with" response is expected if you open the URL directly in a tab, see #39.

When I perform a cross-origin request using your URL, the response looks like a login page. Probably not what you expect, but not a bug from CORS Anywhere's perspective.
