### ISSUE TITLE
Issue with passing very long Content-Range header to CORS-Anywhere

### ISSUE THREAD

**Issue by JeppW** [Rob--W/cors-anywhere#197]
I'm trying to use CORS-Anywhere to pass a request to a site. The request must have a very long Content-Range header (several thousand characters). When trying to pass this request to https://cors-anywhere.herokuapp.com/, I get a 502 Bad Gateway or a 431 Request Headers Fields Too Large from cors-anywhere.herokuapp.com. Would running my own instance of CORS-Anywhere solve this problem?

**Comment by Rob--W** [comment]
What is the size of your request header?

502 or 431 is not generated by CORS Anywhere, so it seems that you're triggering some limit of the host (Heroku).

If that is indeed the case, then you can get around the restrictions by hosting yourself.

Note that Node.js limits the request header size to 8kb by default; any request whose headers exceed 8000 default to a "404 Bad Request" reply. This limit can be raised with the `--max-http-header-size` flag. For example, to set the limit to 80kb:

```sh
node server.js --max-http-header-size=80000
```

or via an environment variable:

```sh
NODE_OPTIONS=--max-http-header-size=80000 node server.js
```

**Comment by JeppW** [comment]
Thank you for your answer. The issue was with Heroku. Hosting it myself fixed the issue.
