### ISSUE TITLE
setHeaders apparently isn't changing request!

### ISSUE THREAD

**Issue by jshamg** [Rob--W/cors-anywhere#199]
Hi,

I'm not able to change the request headers with the setHeaders option. 
I try to set for testing:
`setHeaders: {
    "x-powered-by": "CORS Anywhere"
  }`

This is the code:
![Screenshot from 2019-09-30 16-37-20](https://user-images.githubusercontent.com/32615911/65888968-b99f2d00-e3a0-11e9-87d0-bde3b756ddde.png)

This is the request:
![Screenshot from 2019-09-30 16-36-33](https://user-images.githubusercontent.com/32615911/65888957-b4da7900-e3a0-11e9-8c6c-3830c168a589.png)

**Comment by Rob--W** [comment]
`setHeaders` sets the request headers at the server's side. The client won't see the headers, only the destination server will see those headers.

**Comment by jshamg** [comment]
Is there a possibility to monitor all the headers and everything?

**Comment by Rob--W** [comment]
If you operate the proxy server or destination server, yes. Otherwise no.

**Comment by Rob--W** [comment]
You could add `console.log(req.headers);` at https://github.com/Rob--W/cors-anywhere/blob/4814647a9d21f14858da282387a4295c17f2851d/lib/cors-anywhere.js#L380

**Comment by jshamg** [comment]
Perfect, thank you Rob. Your tool is awesome. Keep it up!
