### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by NickTacke** [Rob--W/cors-anywhere#202]
Ok, so I'm using CORS-Anywhere to get data from my websites api.
For some stupid reason the api doesn't accept requests but the creator of the API doesn't want to change it.
But I've also made it so it changes the data from the api, but cors-anywhere stores some kind of cache since the data doesn't change.
How would I disable this cache? I don't care it takes longer to load.
Have a great day, Nick.

**Comment by Rob--W** [comment]
CORS Anywhere doesn't cache any data. If you are seeing cached results, it is either your browser or the API that you're querying.
