### ISSUE TITLE
Deploy a custom cors anywhere server with hosting domain

### ISSUE THREAD

**Issue by mustapha1509** [Rob--W/cors-anywhere#205]
Hello,
How can i deploy a custom cors anywhere server with my custom hosting domain like https://cors-anywhere.herokuapp.com/

**Comment by Rob--W** [comment]
The README shows a specific example of setting up CORS Anywhere on Heroku, and there are some questions and answers on this issue tracker for specific hosting providers and/or servers. If you want a different domain or host, look up the corresponding documentation yourself.

You would have to look for a way to run a Node.js application on your server/host of choice, expose its listening server via a public IP and register a domain name that points to your IP.
