### ISSUE TITLE
CORS with cross-domain cookies

### ISSUE THREAD

**Issue by karanmathur16** [Rob--W/cors-anywhere#208]
I was able to successfully configure this proxy to send the header "Access-Control-Allow-Credentials : true" so cookies are now sent successfully in the HTTP GET Request.

The problem is that since the target URL is preceded by the proxy (cors-anywhere.heroku) url, the HOST header in the request changes. So I am not able to send the cookies of the domain of the target URL which is the intention. Since we cannot read/write cookies of another domain. 

If we dont use the proxy, the cookies are sent correctly in the request but then blocked by CORS since the target server does not support CORS.

Can you please help?

Thanks!

**Comment by Rob--W** [comment]
Servers cannot trick the browser into sending cookies that are meant for different domains. When the browser connects to a server (whether a proxy or the destination server), the browser determines the domain and the relevant cookies to share. This is solely based on the domain of the requested URL. The fact that the proxy server forwards the request to a different domain is not relevant for cookies.

"the HOST header in the request changes." is not the cause of the missing cookies. The Host header is changed at the server's side, and the browser and their cookies are not involved at all.

If cookies were to be enabled, then every proxied request would share the same set of cookies. This is a security risk, and therefore strongly discouraged. Besides, even if cookies were allowed, domain and path cookies would not work as expected. You should not use cookies with CORS Anywhere.

**Comment by karanmathur16** [comment]
But sending cookies in the request is how the authentication takes place with the JSESSIONID. I am restricting the allowed domains in the "Access-Control-Allow-Origin" so it only enables sharing on cookies between trusted domains. 

The idea here is to send a GET request from another domain to the target which is normal for RESTful services. In the fetch() request i would need to set the "credentials: 'include' " which is then blocked by CORS since the target server does not support it. 

Do you mean to say, the cookies sent do not depend on the HOST header either? 

With a normal fetch() request with "credentials : include", the cookies do go across to the target server (when not using the proxy).

Also, i am only re-using the code here. Not hosting it on a public domain so the security risks are minimized. Can you please help to suggest a way to send this cookie header with the JSESSIONID token with the above details?

**Comment by Rob--W** [comment]
Is your situation like this?

```javascript
https://example.com/ - main web application
https://api.example.net/ - API endpoint expecting JSESSIONID
https://cors-anywhere.example.org/ - your customized proxy

fetch("https://cors-anywhere.example.org/https://api.example.net/", {
  credentials: "include",
});
```

The browser will read cookies for `cors-anywhere.example.org`, and send that to the server.
The browser cannot be forced to hand over cookies for `api.example.net`, because that is a different domain.

> Can you please help to suggest a way to send this cookie header with the JSESSIONID token with the above details?

What you're asking for is impossible.

**Comment by karanmathur16** [comment]
Yes! This is exactly my situation currently. Thank you for the help.
This is understood clearly now.

Now, instead of using a CORS proxy here, is there any other way to achieve this. Since, the CORS header is the only thing blocking me here.
