### ISSUE TITLE
Cannot proxy without port and host, options.target or options.router, or proxy handlers

### ISSUE THREAD

**Issue by oaksagelew** [Rob--W/cors-anywhere#21]
I'm trying to use this and am encountering an error:
I'm hosting this on Modulus.io, and have set up the Package.json to have `start: node server.js`, with `main` also set to `server.js`. `server.js` is exactly like the file in the repo, except for `HOST`, which is set by Modulus.

Any idea what I'm doing wrong? I can't even get to the point of calling the `doCORSRequest` from the HTML because I can't get the server-side to start. Any help appreciated!

`/mnt/data/1/node_modules/http-proxy/lib/node-http-proxy.js:122
    throw new Error(message);`
          ^
**Error: Cannot proxy without port and host, options.target or options.router, or proxy handlers**
`    at Object.exports.createServer (/mnt/data/1/node_modules/http-proxy/lib/node-http-proxy.js:122:11)`
`    at Object.createServer (/mnt/data/1/cors-anywhere.js:325:27)`
`    at Object.<anonymous> (/mnt/data/1/server.js:7:12)`
`    at Module._compile (module.js:456:26)`
`    at Object.Module._extensions..js (module.js:474:10)`
`    at Module.load (module.js:356:32)`
`    at Function.Module._load (module.js:312:12)`
`    at Function.Module.runMain (module.js:497:10)`
`    at startup (node.js:119:16)`
`    at node.js:929:3`

**Comment by Rob--W** [comment]
It looks like you're using an old (0.1.x ?) version of cors-anywhere (or you have installed a wrong version of the `http-proxy` dependency). Install the latest version of cors-anywhere and try again, e.g. by putting the following in your app's package.json and running `npm install`:

```
"dependencies": {
    "cors-anywhere": "~0.2.2"
}
```

**Comment by oaksagelew** [comment]
Rob,
 
Thank you for a quick reply. Yes, that was exactly the problem, and now fixed. Thanks again – and for a really useful proxy; the re-direct handling in particular is exactly the feature I needed, so thanks for thinking of that and building it in.
 
Lew

**Comment by oaksagelew** [comment]
Rob,
 
Thank you for your quick reply. You closed this issue because you correctly identified the problem and I made the changes, so all is well.
 
But, now another issue: Do you know why the proxy is returning encoded HTML? For example, I’ll proxy a site like macys.com and get this back:
 
%3C!DOCTYPE%20html%3E%3C!--%5Bif%20IE%207%20%5D%3E%3Chtml%20class=%22ie7%20ie%20lte10%20lte9%20lte8%20lte11%22%20lang=%22en%22%3E%3C!%5Bendif%5D--%3E……
 
In the XMLHTTPRequest object, I’ve tried setting the “overrideMimeType” to “text/html”, and even the “responseType” to “document”, but the latter didn’t work. I’m trying to insert the return from the proxy to the source parameter of an <iframe>, to display Websites inside the <iframe>.
 
Is there anything that can be done to get what’s returned from the proxy in a form that can be displayed inside an <iframe>? I’ve tried other proxies and they seemed to work fine. What’s great about yours is that you handle re-directs, whereas no other proxy I’ve found does. But, as I say, when I stuff the return into an <iframe>, all I see is encoded HTML instead of the actual Website.
 
I know this isn’t a question related to issues with the proxy, but if you have any insights, I’d be grateful for your help. Thank you!
 
Lew Hollerbach

**Comment by Rob--W** [comment]
It seems that this site requires cookies to be enabled in order to be functional (see curl below). Cookies are intentionally stripped by CORS Anywhere, causing the request to fail.

```
$ curl -vvv http://www.macys.com/
*   Trying 172.229.176.134...
* Connected to www.macys.com (172.229.176.134) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.40.0
> Host: www.macys.com
> Accept: */*
> 
< HTTP/1.1 302 Moved Temporarily
< Server: AkamaiGHost
< Content-Length: 0
< Location: /
< Date: Sun, 08 Feb 2015 09:34:11 GMT
< Connection: keep-alive
< Set-Cookie: ...
...
< Access-Control-Allow-Origin: m.macys.com
< X-Macys-Device: PC
< 
```

**Comment by oaksagelew** [comment]
Thanks for noticing that, Rob; that escaped my attention because I was trying to understand why the result from the proxy is returned as encoded HTML. macys.com was just an example, but it happens with every site I try to load, cookies notwithstanding, and where the request doesn’t fail.
 
Any ideas on why the HTML is returned encoded?

**Comment by Rob--W** [comment]
CORS Anywhere does not modify the response body in any way, so it's likely caused by an error in your code (or in one of the libraries that you use). Visit the demo at https://robwu.nl/cors-anywhere.html, try any URL and the response body looks all right.

**Comment by oaksagelew** [comment]
Yes, you are – again – quite right. My problem was that I was setting the “src” and not “srcdoc” property of the <iframe> when setting the returned contents of the XHR call, and that’s fixed and now sites are displaying fine.
 
Two additional questions, and I hope these will be the last and I won’t abuse the generosity with which you’ve helped me so far:
 
1.       Why are we stripping out the “Cookie” header? And, what would happen if we didn’t strip this out? I’m thinking now again of the macys.com site, which you pointed out was trying to set Cookies and the request failed because the proxy removes that. I guess cookies don’t make sense in a proxied environment, but would anything really bad happen if we didn’t strip them out?
2.       Some sites use relative paths to access resources such as images and scripts (e.g., a site like gap.com has “/assets/image1.png”, etc. instead of “http://gap.com/assets/image1.png”. How does the CORSAnywhere proxy deal with that? Will it retrieve these resources correctly? It doesn’t if it’s called with an XHR and the “srcdoc” property of the <iframe> is used to load the site content. Short of parsing any URL and injecting the full domain name, would there be any other workarounds for this?
 
Thanks again for all your help – really appreciate it!
 
Lew

**Comment by Rob--W** [comment]
> 1. Why are we stripping out the “Cookie” header? And, what would happen if we didn’t strip this out? I’m thinking now again of the macys.com site, which you pointed out was trying to set Cookies and the request failed because the proxy removes that. I guess cookies don’t make sense in a proxied environment, but would anything really bad happen if we didn’t strip them out?

I strip cookies because otherwise I have to implement a cookie parser that parses the cookies, and modify the cookie such that e.g. path= and domain= are correctly interpreted. Even if one assumes that this is correctly and securely implemented, then there are other issues: Since CORS Anywhere is hosted on a single domain, the browser will enforce a single quota for all proxied websites. This quota could be resolved by adding custom logic to the API, such that the headers are sent/received via a custom header, but that complicates the API a little bit (the user of CORS Anywhere has to implement the cookie jar themselves, and store it somewhere.).

In short: Implementing cookies in a secure way requires some efforts that I am not willing to put in. Pull requests are welcome, but will be subject to a very strict review.

> 2. Some sites use relative paths to access resources such as images and scripts (e.g., a site like gap.com has “/assets/image1.png”, etc. instead of “http://gap.com/assets/image1.png”. How does the CORSAnywhere proxy deal with that? Will it retrieve these resources correctly? It doesn’t if it’s called with an XHR and the “srcdoc” property of the <iframe> is used to load the site content. Short of parsing any URL and injecting the full domain name, would there be any other workarounds for this?

CORS Anywhere is merely a proxy, intended to be used with XMLHttpRequest (but also usable in contexts where CORS can be enabled, such as cross-origin images to avoid tainted canvases). Direct embedding in (top-level) frames is not supported, because that could be a gaping security hole: e.g. if some proxied site stores sensitive data in localStorage, then another proxied site could access this data if direct embedding was supported. CORS Anywhere only provides the response to a request, it does not parse (let alone modify) the response. Therefore relative URLs are not modified, and if you blindly put the response in an iframe, then you can expect sites to break.

CORS Anywhere should not be used to blindly proxy every website, you should only try to proxy and display sites that you can handle; if you blindly display any (untrusted) site at your origin, then any proxied site could compromise the user's security on your website.

**Comment by oaksagelew** [comment]
Got it. Rob, thank you very much for your feedback, help, and advice. Really do appreciate your time. Thanks, and be well!
