### ISSUE TITLE
is cors anywhere using cors-server vps server ip address when redirecting to actual server?

### ISSUE THREAD

**Issue by sulemankhann** [Rob--W/cors-anywhere#210]
Hi, I am using this package to build my cors-server and from that server i am  using some google services and google ban my cors-server ip address so my question is that is this package is not just append Allow request origin header and redirect request to actual server? 

<img width="705" alt="Screenshot 2020-02-02 at 10 34 28 AM" src="https://user-images.githubusercontent.com/29842193/73603890-82d55f80-45aa-11ea-8078-df971f55f1bc.png">

**Comment by Rob--W** [comment]
> is this package is not just append Allow request origin header and redirect request to actual server?

The request is not "redirected" (in which case the client would handle the request), but forwarded (the server makes the request and the response is returned to the client). Naturally, the destination server sees the IP of the server.

**Comment by sulemankhann** [comment]
Oh I see thanks for info! Is there a way to work around it? I mean so the destination server couldn't see the IP of the server. 

Actually i am using some google services in my vps so i though why not i move my application logic to client side this way google won't block because the ip of client will be used to access resource but than i ran to cors issue so i use your package but the same problem have occur again. So can u suggest me a way where my ip is dynamic or i can use client ip address?

**Comment by Rob--W** [comment]
You can only use the clients IP address if you find a way to directly interact with the API (i.e. the API that you use supports CORS), or by being unaffected by the same-origin policy (e.g. by using a client-side application, browser extension or app).
