### ISSUE TITLE
Response {type: "cors" ...

### ISSUE THREAD

**Issue by viccro** [Rob--W/cors-anywhere#213]
I'm having issues with both a heroku deployment and a local instance of CORS-anywhere, and I was hoping that you could tell me that I'm making an obvious mistake. I was able to use a heroku instance for a while, and it suddenly stopped working (rate limiting, maybe?). I then tried to run one with `node server.js`, and am getting the exact same issue (not an error, still a problem!)

```
Response {type: "cors", url: "http://localhost:8080/http://minuteman.overdrive.com/search/title?query=book%20title", redirected: false, status: 200, ok: true, …}
type: "cors"
url: "http://localhost:8080/http://minuteman.overdrive.com/search/title?query=book%20title"
redirected: false
status: 200
ok: true
statusText: "OK"
headers: Headers {}
body: (...)
bodyUsed: false
__proto__: Response
```

Is this some sort of response type that I should recognize and know what to do with? Is there a quick fix, or is there something deeper at play?

Thanks for the help! I'm still new to CORS problems, so it could very well be something obvious.

**Comment by Rob--W** [comment]
I'm not seeing any error in your example. The status code is 200, the response seems fine.

What is the question here?

**Comment by viccro** [comment]
Sorry. I was expecting to get a response from the API I was hitting, but it appears to be subsumed by this cors-type response. I was definitely able to read data from the API for a time, but it has vanished and turned into this response. Is there any way to get at the actual content, past this cors response?

**Comment by Rob--W** [comment]
The response being of type "cors" is not an issue, and normal. You will still be able to read the response because CORS Anywhere adds the necessary response headers.

**Comment by viccro** [comment]
You're right! It was definitely a dumb/new dev problem. I couldn't extract the response, because I was missing a line in processing my fetch response (and it wasn't obvious from the response I was able to console.log). Thanks for your patience.
