### ISSUE TITLE
Request to a particular site fails but works with another solution

### ISSUE THREAD

**Issue by ShaCP** [Rob--W/cors-anywhere#216]
I do an xmlhttprequest to https://boxrec.com/en/proboxer/180 and I get an error after a long waiting time. If I use https://allorigins.win/, it does work. Other sites do work using cors-anywhere.

Errors:
'Access to XMLHttpRequest at 'https://cors-anywhere.herokuapp.com/https://boxrec.com/en/proboxer/90' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource'
'GET https://cors-anywhere.herokuapp.com/https://boxrec.com/en/proboxer/90 net::ERR_FAILED'

**Comment by Rob--W** [comment]
The request to that other server times out. Could be that the other server refuses requests from the proxy.

Not an issue with my server.
