### ISSUE TITLE
The proxy is down?

### ISSUE THREAD

**Issue by kellysb** [Rob--W/cors-anywhere#218]
I'm getting errors on a few of my scripts that use this API. It looks like it went down today. Any help that can be offered here? https://cors-anywhere.herokuapp.com/

**Comment by kellysb** [comment]
It's back!

**Comment by Rob--W** [comment]
In the future, if you report an error, please include the response details. At the very least the status code, preferably also the response headers + body (don't directly open the URL in the browser, as the response to that is different than when fetch/XHR is used).
