### ISSUE TITLE
How to obtain the correct charset?

### ISSUE THREAD

**Issue by petrfid** [Rob--W/cors-anywhere#22]
Hi, Rob, 
your work is excelent, but...
I work with pages with windows-1250 charset and I use jquery get method. Pages are loaded correctly, but with the wrong character set :-(
Do you have any suggestion?
THNX!

Petr

Demo: http://www.finecafe.cz/finecafe/pokus.php
My code: http://www.finecafe.cz/finecafe/tooltip-code.txt

**Comment by Rob--W** [comment]
Override the MIME-type of the response body. E.g. in jQuery:

```javascript
$.ajax({
    url: '....',
    mimeType: 'text/html; charset=windows-1250'
});
```

Or, for those using vanilla JavaScript:

```javascript
var x = new XMLHttpRequest();
x.open('GET', '....');
x.overrideMimeType('text/html; charset=windows-1250');
x.send();
```

**Comment by petrfid** [comment]
Thank you very much, it WORKS! :+1:
