### ISSUE TITLE
"Missing required request header. Must specify one of: origin,x-requested-with"

### ISSUE THREAD

**Issue by Unteraqwx** [Rob--W/cors-anywhere#222]
Hey, I have problem when i want to use your project at localhost,

I have this error : Missing required request header. Must specify one of: origin,x-requested-with

And when my url is redirected, the main page contain cloudfare and then i get this error : 

"Please turn JavaScript on and reload the page.", i don't understand why i get this error while it work at 
https://cors-anywhere.herokuapp.com/link

I get error in console : 503 Service Unavailable
![unknown](https://user-images.githubusercontent.com/22792175/78593789-79d16a80-7847-11ea-976f-2aeed4cd2760.png)

thank's to reply

**Comment by Rob--W** [comment]
> Hey, I have problem when i want to use your project at localhost,
> 
> I have this error : Missing required request header. Must specify one of: origin,x-requested-with

The CORS proxy and the server SHOULD not share the same domain name. If you do put them on the same host and want to use CORS Anywhere, add the X-Requested-With request header to your requests.


> And when my url is redirected, the main page contain cloudfare and then i get this error :
> 
> "Please turn JavaScript on and reload the page.",

This is unrelated to CORS Anywhere. It is an issue with your own application (or possibly the actual response from the proxied request).

**Comment by Unteraqwx** [comment]
Have you an idea to resolve my problem ? i know it's not your API but i don't know why with your link is fine and not with localhost ?

**Comment by Rob--W** [comment]
I don't know. You haven't provided any details that would allow me to make an educated guess.

**Comment by Unteraqwx** [comment]
![Discord_qSQUTRDVDt](https://user-images.githubusercontent.com/22792175/78715350-950ea980-791d-11ea-992f-485ef68526d7.png)

it's error encountered, in page preview you can see this

![unknown](https://user-images.githubusercontent.com/22792175/78715458-b96a8600-791d-11ea-9d57-056b912a1b68.png)

it's because of Javascript is not executed, so we get this error...

**Comment by Rob--W** [comment]
> it's because of Javascript is not executed, so we get this error...

This is normal. CORS Anywhere is just a proxy. I don't have any control over what the remote server sends.

I guess that you would get the same kind of response if you were to visit the same page from Chrome in incognito mode.

**Comment by Unteraqwx** [comment]
Okay but why with your api online it work ? it'same that local server... i can get the good output HTML and i haven't problem, just I am locked after 200 requests and i need for over 400K

**Comment by Rob--W** [comment]
> I am locked after 200 requests and i need for over 400K

This answers why the remote server is locking you out. This very much looks like DDoS, which is why Cloudflare intervenes (on behalf of the destination site).

**Comment by Unteraqwx** [comment]
It's your API which block until 200 requests and it's for this reason i need to have your api at server localhost, you understand ?

**Comment by Rob--W** [comment]
My CORS Anywhere proxy limits request to make sure that as many people as possible can use the server for demo purposes. This limit exists because the server does not have infinite resources.

In your case, the destination server also has its own limit (before Cloudflare intervenes), which is completely independent of my server. It just happens that their limit is apparently higher than my limit, so on my proxy you are getting limited by my limit before reaching the destination server's limit.
This doesn't mean that my server does something magical, it means that you are making an excessive number of requests and that the only way to get your application to work as desired is to distribute your requests more responsibly.

**Comment by Unteraqwx** [comment]
ok, thx for your answer
