### ISSUE TITLE
Error 400 when try request to server

### ISSUE THREAD

**Issue by MrZillaGold** [Rob--W/cors-anywhere#225]
When I try to use such code, an error 400 occurs, I don’t understand what could be the reason, but this is definitely not an axios problem, when using fetch the answer will be the same.

Watching issues axios, I came across the same problem as mine, but they answered that it was a server problem.
https://github.com/axios/axios/issues/2814

If you do not use proxy then this code will work fine

```js
// USE ES6 IMPORT/EXPORT

import axios from "axios";

export default class Test {

    options = {
        endpoint: "https://namemc.com",
        proxy: "https://cors-anywhere.herokuapp.com"
    };

    get(options) {
        const {
            proxy, endpoint
        } = this.options;

        return new Promise(async (resolve, reject) => {
                let res;

                await axios.get(`${proxy ? `${proxy}/` : ""}${endpoint}/profile/${options}`)
                    .then(response => res = response)
                    .catch(error => reject(error);
                
                resolve(res);
        })
    }

}
```

**Comment by Rob--W** [comment]
Look at the browser's devtools and/or the network tab of the devtools. Do you see any more specific response headers / response bodies?

I doubt whether the same code from your comment would work, because you are referencing an undefined variable (`options`) in the template string..

**Comment by MrZillaGold** [comment]
Found what the problem is, I apologize for the concern.

The code above is working, options are passed when the class method is called

![image](https://user-images.githubusercontent.com/42776347/79452069-e8be7880-802a-11ea-8c1c-469fdb6d7675.png)
