### ISSUE TITLE
[ERROR] While trying to initialize CORS-anywhere server

### ISSUE THREAD

**Issue by uo264074** [Rob--W/cors-anywhere#229]
This is what I'm getting:
`TypeError: __webpack_require__(...).createServer is not a function`
 At `.../node_modules/cors-anywhere/lib/cors-anywhere.js:420`
417 | if (options.httpsOptions) {
418 |   server = require('https').createServer(options.httpsOptions, requestHandler);
419 | } else {
 ^ 420 |   server = require('http').createServer(requestHandler);
 421 | } // When the server fails, just show a 404 instead of Internal server error
422 |

**Comment by Rob--W** [comment]
This bug report does not have enough details.

What is your webpack config, and why are you using webpack at all for a Node.js script?
