### ISSUE TITLE
Experiencing issues

### ISSUE THREAD

**Issue by mosesweb** [Rob--W/cors-anywhere#231]
I am trying to use "https://cors-anywhere.herokuapp.com/" inputting my URLs with GET requests but it is inconsistency not working sometimes.

**Comment by Rob--W** [comment]
What is the response that you're getting?

**Comment by cesolutions** [comment]
I think the site is down currently? 
![image](https://user-images.githubusercontent.com/14008341/80512405-a9e9c600-893a-11ea-9e5a-fdc11b116dd2.png)

**Comment by lukassio** [comment]
Ditto, I'm getting the same error as above

**Comment by cesolutions** [comment]
I'm currently trying to spin up my own proxy server. Following this SO article: 

https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe

**Comment by Rob--W** [comment]
I've restarted the server, it's up again. Thanks for sharing those steps @cesolutions .

**Comment by egfx** [comment]
it is currently down

**Comment by cesolutions** [comment]
> I've restarted the server, it's up again. Thanks for sharing those steps @cesolutions .

Following those steps seems to not work. After cloning the repo the command heroku is not recognized. Anyways, the public url seems to be working right now though.

**Comment by Rob--W** [comment]
I've updated the application for compatibility with the latest Node.js versions, and also added some extra validation against invalid URLs. And while I'm at it, I also upgraded the Heroku stack to the latest version.

That should address the issue that resulted in downtime.

**Comment by mosesweb** [comment]
![image](https://user-images.githubusercontent.com/22138330/80874628-d5faa380-8cba-11ea-8783-e9c29c56f832.png)

**Comment by mosesweb** [comment]
![image](https://user-images.githubusercontent.com/22138330/80874872-e743b000-8cba-11ea-9c95-d4336b9083ea.png)

**Comment by Rob--W** [comment]
@mosesweb I applied the blacklist that was lost during the migration. Now resources are shared more fairly among all users again.

**Comment by mosesweb** [comment]
Thank you @Rob--W Rob!

**Comment by alexandrtovmach** [comment]
@Rob--W Hello, `503` again "Application error"

**Comment by egfx** [comment]
Status Code: 503 Service Unavailable

**Comment by Rob--W** [comment]
@egfx I fixed that in #234.
