### ISSUE TITLE
Not allowed remote ip when request a lot time 

### ISSUE THREAD

**Issue by KilalaPhu** [Rob--W/cors-anywhere#235]
i use link website of you for call api send message linework
but when i send some message success some time it will error Not allowed remote ip
i think linework have block your remote ip of you
you can change ip after request or how fix error Not allowed remote ip from linework
![Screenshot_2](https://user-images.githubusercontent.com/54198131/81279085-d57a5800-9080-11ea-9aa2-df688bb678af.png)

**Comment by Rob--W** [comment]
This is not a problem with CORS Anywhere but with your usage patterns. The solution is to not send as many requests.

If the number of requests per IP are limited, then you should look into ways to send the request directly from the client instead of through a proxy.
