### ISSUE TITLE
CORSANYWHERE_WHITELIST for subdomains

### ISSUE THREAD

**Issue by kp222x** [Rob--W/cors-anywhere#244]
How can I support *.example.com?

a.example.com - allowed
b.example.com - allowed

**Comment by Rob--W** [comment]
Wildcards are not supported in `CORSANYWHERE_WHITELIST`. If you have a specific set of origins that you want to support, pass them to `CORSANYWHERE_WHITELIST`, separated by commas.

You can achieve a similar effect with the `CORSANYWHERE_RATELIMIT` option, which is documented here: https://github.com/Rob--W/cors-anywhere/blob/a0309e6c475036b4ba2a04372f8d5b6462bd4825/lib/rate-limit.js#L3-L20 . For example:
```sh
# Allow example.com, or any subdomain to make any number of requests and block the rest:
CORSANYWHERE_RATELIMIT='0 1 /(.*\.)?example\.com/'
```
