### ISSUE TITLE
Deploying own cors server. How to remove rate-limit altogether / increase it?

### ISSUE THREAD

**Issue by varunshivaram** [Rob--W/cors-anywhere#245]
Hi,
I am a system admin. I am trying to deploy our own CORS server using the repository code. But the rate limit is set to 200 requests per hour which is not feasible for the app. How can I either increase the rate limit or remove it altogether in the code.
Thank you for this code base by the way. It really made the work easy.

**Comment by Rob--W** [comment]
A self-hosted CORS Anywhere instance doesn't have any rate limit by default.
