### ISSUE TITLE
Heroku Application error

### ISSUE THREAD

**Issue by mateuspv** [Rob--W/cors-anywhere#246]
Looks like its down:
<img width="1439" alt="Screen Shot 2020-06-15 at 08 30 45" src="https://user-images.githubusercontent.com/4995440/84652737-837bec00-aee2-11ea-9c42-6d46a256aedc.png">

**Comment by Bonjur** [comment]
@Rob--W Please restart server.

**Comment by Rob--W** [comment]
Thanks for the report. The server got overloaded due to abuse. I blocked some offenders and the server seems to be relieved now.

**Comment by mateuspv** [comment]
Thanks so much for the attention here, love the api,
Best
