### ISSUE TITLE
Can't make it work with a specific site

### ISSUE THREAD

**Issue by BobSpiders** [Rob--W/cors-anywhere#248]
I am trying to access a page on the easyJet website via a node.js server. The page normally produces a json object with a set of flight schedules. If I test this page on a regular browser it works. Similarly, it works if I access it with a js script of mine, but only if I run it via a browser with CORS disabled.
Now I'm trying to access it via a node server using CORS-anywhere. If I do so, I receive a different HTML page saying that I "don't have permission to access ... on this server"

These are the relevant portions of the code:

```
var host = process.env.HOST || 'localhost';
var port = process.env.PORT || 8080;
cors_proxy.createServer({
    originWhitelist: [], // Allow all origins
    requireHeader: ['origin', 'x-requested-with'],
    removeHeaders: ['cookie', 'cookie2']
}).listen(port, host, function() {
    console.log('Running CORS Anywhere on ' + host + ':' + port);
});

var cors_api_url = 'http://localhost:8080/';
url = 'https://www.easyjet.com/ejavailability/api/v381/availability/query?AdditionalSeats=0&AdultSeats=1&ArrivalIata=MXP&ChildSeats=0&DepartureIata=LGW&IncludeAdminFees=true&IncludeFlexiFares=false&IncludeLowestFareSeats=true&IncludePrices=true&Infants=0&IsTransfer=false&LanguageCode=EN&MaxDepartureDate=2020-09-02&MinDepartureDate=2020-09-02'

fetch(cors_api_url + url, {
	headers: { 
		'Method': 'GET', 
		'Origin': '',
		'Content-Type': 'application/json' 
}})
```
I have tried to have the server and the client in two different computers on the same network (i.e, using the specific IP address for the server such as 192.168.0.120, and accessing it from another device), and I also tried using a completely different WAN IP address, so to exclude the possibility of my IP being blacklisted.

I also have no luck if I try to use the server on https://cors-anywhere.herokuapp.com/ instead of my own, so I guess that easyJet is, in one way or another, successfully blocking every effort to bypass the CORS policy.

Just to be clear, I am no expert at all, so I might have seriously misunderstood some of the functions/purposes of the tool. What options do I have? Is there anything that I didn't do correctly? Is your app supposed to work with any web server (apart from blacklisting), or are there some site where it doesn't work?

Many thanks for any help

Bob

**Comment by Rob--W** [comment]
This is not an issue with CORS. If I use curl to send a request, then I get the same response.

Odds are that the API endpoint relies on cookies or some other way to identify the client before accepting requests. Use the browser's developer tools to inspect the network traffic and find what you need.

**Comment by BobSpiders** [comment]
Thanks Rob!
