### ISSUE TITLE
Error on Post/Put requests (Firebase Functions)

### ISSUE THREAD

**Issue by sebastiendelorme** [Rob--W/cors-anywhere#249]
Hello,

I'm using cors-anywhere with Firebase Functions (thank you for this useful proxy !).

Based on this ticket: https://github.com/Rob--W/cors-anywhere/issues/160 I created a proxy function:

```
var cors_proxy = require("cors-anywhere").createServer({
    originWhitelist: ["https://mydomain.com"],
    requireHeader: ["origin", "x-requested-with"],
    removeHeaders: ["cookie", "cookie2"],
    redirectSameOrigin: true,
    httpProxyOptions: {
        xfwd: false,
    },
});

exports.proxy = functions.https.onRequest((req, res) => {
    cors_proxy.emit("request", req, res);
});
```

I need to force https protocol, so I'm using for example:
https://my-project.cloudfunctions.net/proxy/apidomain.com:443/foo

GET and DELETE requests are well proxied, but no with POST or PUT requests.
I see data on my request (JSON) but it seems apidomain.com don't receive it...

Do you have any idea to help me?

PS: everything works fine with https://cors-anywhere.herokuapp.com/apidomain.com:443/foo (post, put, get, etc.)

**Comment by Rob--W** [comment]
I can't tell what went wrong without more specific error messages.

**Comment by sebastiendelorme** [comment]
Hello,
I understand, but I have no more specific error message.

My API reply a 400 error (bad request) :
'''
{"error":{"message":"Missing parameters in root object","infos":["first_name","last_name","email","phone_number"],"presentable":false}}
'''

And I send these parameters because when use https://cors-anywhere.herokuapp.com it works.

I will try with an open API to be able to show you a test.

**Comment by sebastiendelorme** [comment]
I haven't found a solution yet.
