### ISSUE TITLE
PSA: Heroku service change at 15 July 2015 may reduce uptime by 25%

### ISSUE THREAD

**Issue by Rob--W** [Rob--W/cors-anywhere#25]
CORS Anywhere is currently hosted at Heroku using the free plan. Currently, this plan offers an uptime of 24/7 if the application is actively used.

As of 1 July 2015, all existing free plans will be "upgraded" to a new free plan that limits the uptime to 18 hours a day (i.e. fo 6 hours a day, CORS Anywhere will be offline). This change has been announced at https://blog.heroku.com/archives/2015/5/7/new-dyno-types-public-beta.

I suggest to self-host CORS Anywhere if uptime is critical.

(To maintain the 24/7 uptime for the existing deployment at `cors-anywhere.herokuapp.com`, 7$ per month needs to be paid. 84$/year for something that doesn't give me any revenue is a bit too much.)

**Comment by Rob--W** [comment]
There was some confusion about the flag date.

The documentation provides a clarification: https://devcenter.heroku.com/articles/traditional-dynos (emphasis mine)

> Applications that use traditional dynos and that do not have paid usage will be migrated to free dynos starting **on July 15th, 2015**. However, **if** you have an application that is using traditional dynos and that has **paid usage for dynos, a database or add-ons, you can choose to keep your app on traditional pricing through January 31, 2016**. You can experiment with the new dynos at any time for these “grandfathered” apps by going to Dashboard and clicking edit on the resources page and choosing the dyno type you want. If you want to switch back to traditional pricing during the grandfathering period you can simply edit the resources for the app.

So, it seems that if I stick to the free plan, the reduced availability becomes effective on 15 July, unless I pay 7$/mo. But if I have any paid feature (e.g. a [2$/mo SMS app](https://elements.heroku.com/addons/blowerio)), I can still use the existing free "traditional plan" until January 2016.

An issue is that Heroku requires a credit card for payment, and does not accept other methods like Paypal...

**Comment by Bilge** [comment]
Does this mean that, even if I were to host this myself using Heroku's free tier, it would be down at undetermined points during the day? Or is that only the case if it's in constant use?

I've never used Heroku before and don't understand the implications of "sleeping" nor do I know how the "dyno hours" are counted. If it sleeps after 30 minutes of inactivity, is there a delay to being woken up? Does it consume at least 30 minutes of "dyno hours" every time it's woken up?

**Comment by Rob--W** [comment]
My public demo appears to still be up 24/7. So this issue is a non-issue. 

From https://www.heroku.com/pricing :

> Sleeps after 30 mins of inactivity

My demo is constantly being used, so it's not affected. When it was, the first request takes a few seconds longer to process, but after that you won't notice the difference.

> Uses an account-based pool
of free dyno hours

This is explained as:

> Verified accounts come with a monthly pool of 1000 Free dyno hours; unverified accounts receive 550. When a Free dyno is active, it draws from the pool; your free apps can run as long as there are dyno hours left in your monthly pool. 

I guess that my account has been verified, because one month has about 24x30 = 720 hours, and my demo is still up 24/7.
