### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by paulakfleck** [Rob--W/cors-anywhere#251]
Hello :)

I'm trying to use the Heroku app but I get this error:

![image](https://user-images.githubusercontent.com/5883100/86542383-bfa3da80-beeb-11ea-92a8-680665c40197.png)

Maybe it's temporary, but I've been having this issue for around 30min. Just wanted to let you know.

Thank you in advance!

**Comment by daves777** [comment]
Hey there, I'm also getting this same error. Hoping its just a temporary thing :)

**Comment by RishabGargeya** [comment]
Also having some issues with the herokuapp, looks like it's down if I'm not mistaken

https://www.isitdownrightnow.com/cors-anywhere.herokuapp.com.html

**Comment by drskidmore** [comment]
I am also experiencing extremely slow response times (well over 10 seconds), but everything loads correctly after a long delay.

**Comment by Rob--W** [comment]
I blocked some blatant abuse ( #252 ). Please comment or open a new issue if it happens again.
