### ISSUE TITLE
Heroku CORS Anywhere Down?

### ISSUE THREAD

**Issue by b0arderman** [Rob--W/cors-anywhere#252]
Is it possible that https://cors-anywhere.herokuapp.com/ is not working properly?

It was working over the weekend for me, but this morning when I tried to access it, i am receiving a CORS error...
Access to XMLHttpRequest at 'https://cors-anywhere.herokuapp.com/' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Even with the demo page:
https://robwu.nl/cors-anywhere.html

Below is a screenshot of the errors.  
Thanks,
Eric

![image](https://user-images.githubusercontent.com/67908609/86595249-134f0c00-bf5e-11ea-8a8c-4ea37c6260be.png)

**Comment by wallena3** [comment]
same

**Comment by Rob--W** [comment]
I fixed this by blocking some high-frequency requests.
