### ISSUE TITLE
Warnings for vulnerabilities in Ubuntu 20.04

### ISSUE THREAD

**Issue by juanamm** [Rob--W/cors-anywhere#254]
The app works correctly, but at the time of installing it, +22 warnings were presented for vulnerabilities, most of which I solved with `--force` in Ubuntu 20.04.
I cloned the project this way:
`git clone https://github.com/Rob--W/cors-anywhere.git`
With this I get the project updated or should I download it manually from here?

**Comment by Rob--W** [comment]
With `git clone` you'll be pulling the latest version, but it won't automatically update unless you run `git pull` again.

**Comment by juanamm** [comment]
> With `git clone` you'll be pulling the latest version, but it won't automatically update unless you run `git pull` again.

Does this mean that the latest version has these vulnerabilities?

**Comment by Rob--W** [comment]
The only non-dev dependency reported by `npm audit` is http-proxy:

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ http-proxy                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ http-proxy                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ http-proxy                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1486                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

As mentioned in https://www.npmjs.com/advisories/1486, the server may crash when the `proxyReq.setHeader` method is used. My library doesn't use this event+method and is therefore not vulnerable.

**Comment by juanamm** [comment]
I re-installed server Ubuntu 20.04 LTS and take the opportunity to copy the vulnerabilities found:
```
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated request@2.79.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

npm notice created a lockfile as package-lock.json. You should commit this file.
added 262 packages from 686 contributors and audited 262 packages in 9.384s

15 packages are looking for funding
  run `npm fund` for details

found 22 vulnerabilities (6 low, 8 moderate, 7 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```
 With `npm audit fix` I fixed 3 vulnerabilities.
The rest I fixed with `npm audit fix --force`

**Comment by Rob--W** [comment]
Do not blindly bump dependencies. As mentioned in https://github.com/Rob--W/cors-anywhere/issues/254#issuecomment-659037020, there is only one non-dev dependency. devDependencies are not used when you use CORS Anywhere, only if you develop it and run tests.

CORS Anywhere uses a specific version of http-proxy because it hooks some internals in order to provide the necessary functionality. There is a chance that bumping the http-proxy version would result in broken functionality, so don't bump it.

This report is a duplicate of #253 by the way, so I'm going to close this as a duplicate of that other issue. Thanks for contributing useful comments.

**Comment by vavsab** [comment]
If there is someone who wants to fork it and just bump `http-proxy` like I wanted to do... You will need to fix [this issue](https://github.com/http-party/node-http-proxy/issues/1530) in `http-proxy` first because it breaks 1 test in `cors-anywhere`. New version of `http-proxy` just crashes when status code is invalid.
Too hard for me. Just gave up this idea 😥
