### ISSUE TITLE
Missing User Token in Header

### ISSUE THREAD

**Issue by Dave-Lindberg** [Rob--W/cors-anywhere#258]
My query for a GET request looks like this: 

```
    axios
      .get('https://cors-anywhere.herokuapp.com/https://api.mindbodyonline.com/public/v6/class/classes',
      {
        headers: {
          'Content-Type': 'application/json',
          'X-Requested-With': 'XMLHttpRequest',
          'Api-Key': 'a-valid-api-key',
          'SiteId': '66835',
          'User-Agent': 'uvac-welcome-screen,uvac-welcome-screen',
          'Authorization': {
            "Username": "_DaveLindberg",
            "Password": "a-valid-password"
          }
        }, 
      }
      )...

```

This results in `{"Error":{"Message":"Invalid user token","Code":"DeniedAccess"}}`

The Support team for the API has confirmed that "Your API-Key is definitely showing in the headers of the request, but that error seems to indicate it isn't being passed once the request reaches our servers." 

Am I missing something that's preventing the header from reaching the endpoint? Thanks!

**Comment by Rob--W** [comment]
Your use of axios is incorrrect. Either pass the token as a string to `Authorization`, or (if you want to use basic auth), use the `auth` key as documented at https://github.com/axios/axios/blame/ffea03453f77a8176c51554d5f6c3c6829294649/README.md#L358-L366

Your use of the mindbodyonline API also looks incorrect. You first have to send a POST request with username + password in the request body to retrieve an authorization token, and then pass it to the Authorization header. I suggest you to take a very good look at the documentation of the API that you're using - https://developers.mindbodyonline.com/PublicDocumentation/V6#authentication

And lastly, I recommend against sending credentials through a third-party proxy. Ask the API provider to support CORS. If they don't want to support CORS, consider self-hosting CORS Anywhere (see the project's README) to have full control over the data and its availability.

This is not an issue with CORS Anywhere - so I'm closing this issue.
