### ISSUE TITLE
Add option to ignore https certificate validation

### ISSUE THREAD

**Issue by jrluis** [Rob--W/cors-anywhere#26]
Hi,

While trying to connect to a web server with self signed certificates, the connection is refused, because the certificates don't validate.

Can an option to ignore the certificate validation be added?

Regards

**Comment by Rob--W** [comment]
The canonical (Node.js) way of disabling certificate validation is by setting the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable to `0`. 

Someone else asked the same question at #16.
