### ISSUE TITLE
Missing required request header. Must specify one of: origin,x-requested-with

### ISSUE THREAD

**Issue by mishra709s** [Rob--W/cors-anywhere#260]
Hello... I am getting "Missing required request header. Must specify one of: origin,x-requested-with" error even if I have setup the herokuapp proxy server. 
The screenshots are attached below along with the code. Please help.
![image](https://user-images.githubusercontent.com/44873259/88539319-aa275980-d02e-11ea-842b-67f5648b0f7d.png)
![image](https://user-images.githubusercontent.com/44873259/88539366-bd3a2980-d02e-11ea-97ed-072d0214a6a4.png)

**Comment by Rob--W** [comment]
https://github.com/Rob--W/cors-anywhere/issues/39#issuecomment-188735645
https://github.com/Rob--W/cors-anywhere/issues/39#issuecomment-387690291

**Comment by mishra709s** [comment]
Sorry for creating a duplicate issue and wasting your time @Rob--W .The issue is resolved.

**Comment by Rob--W** [comment]
You're welcome!
