### ISSUE TITLE
Where to put CORSANYWHERE_WHITELIST variable when setting up demo server on Heroku?

### ISSUE THREAD

**Issue by GamerKingFaiz** [Rob--W/cors-anywhere#261]
Hi! First off thanks for the great resource. I followed the instructions in the [Demo Server section](https://github.com/Rob--W/cors-anywhere#demo-server) of the readme, but I'm not sure where to place this part to whitelist my specific site:
```
export CORSANYWHERE_WHITELIST=https://www.boardgamegeek.com/
node server.js
```

I've tried making an `.env` file with that text.
I've tried adding it to the `Procfile`.
I've tried adding it as a config var as described in the [Heroku tutorial](https://devcenter.heroku.com/articles/getting-started-with-nodejs?singlepage=true#define-config-vars).
I also tried adding it to `originWhitelist` key of the `corsAnywhere` object on line 262 of `cors-anywhere.js`.

I'm sure the answer is super obvious, but I'm too much of a noob to know where this goes. :sweat_smile:

**Comment by GamerKingFaiz** [comment]
Nevermind I was able to figure it out by setting the config var using the following command:
`heroku config:set CORSANYWHERE_WHITELIST=https://boardgamegeek.com/`

I believe previously I had included the `www`, which seems to not work.

**Comment by GamerKingFaiz** [comment]
Ah shoot, I must've spoke too soon. I'm getting 403s for my whitelisted domain.
![image](https://user-images.githubusercontent.com/9065136/88622960-b3c5b700-d058-11ea-95fa-1a4079bb89b7.png)

I tested adding `PORT: 443` to the Heroku config vars and then did a `heroku restart`, but the 403s persist.
This is what my config vars look like now:
![image](https://user-images.githubusercontent.com/9065136/88623068-03a47e00-d059-11ea-96e5-8ca0a7276122.png)

**Comment by Rob--W** [comment]
CORS Anywhere does currently not offer a way to restrict the destination URLs.

The `CORSANYWHERE_WHITELIST` configuration option allows you to restrict the origins, i.e. which pages can use the proxy to read data from other websites.

**Comment by GamerKingFaiz** [comment]
Ah okay! So in my case I should set up my local environment (e.g. http://localhost:3000) and my live domain (e.g. https://betterbggcollection.com), right? Is the `PORT` variable necessary if I already attached the port to the URL above?

**Comment by Rob--W** [comment]
The `PORT` variable should only be set if the proxy server should listen at a specific port.

From your comments so far, it is not clear what you're trying to do. To answer your question, you need to distinguish:

- What is the location of your proxy server. For internal use: local host (e.g. 127.0.0.1) + port, for external use (by the website, see next point): the host of the proxy (e.g. the herokuapp site).
- What is the location (origin) of the website that wants to use the proxy. (can be multiple; pass this to `CORSANYWHERE_WHITELIST` )
- What is the location of the website that you're trying to access over the proxy (can be multiple, CORS Anywhere does currently not offer the ability to filter this)

**Comment by GamerKingFaiz** [comment]
Sorry for not being clear. To address your three points:

* Heroku
* http://localhost:3000 and https://betterbggcollection.com
* The BGG XML API

I was able to get it working by just setting the `CORSANYWHERE_WHITELIST` variable to `http://localhost:3000,https://betterbggcollection.com`.

Thanks for your help, I'll go ahead and close this issue out now!

**Comment by woctezuma** [comment]
For info, there is a web page  at `https://dashboard.heroku.com/apps/HEROKUNAME-HEROKUID/settings`

where you can set config vars:

![Heroku config](https://i.imgur.com/gzJWc6j.png)

I have not tested it yet, but I think that is one way to set the config vars mentioned in the README.
