### ISSUE TITLE
Will cors-anywhere ever rate limit requests?

### ISSUE THREAD

**Issue by GamerKingFaiz** [Rob--W/cors-anywhere#262]
I'm trying to confirm whether this rate limit error is coming from `cors-anywhere` or from the API I'm calling.
![image](https://user-images.githubusercontent.com/9065136/88620614-50855600-d053-11ea-825d-f5192af62682.png)

**Comment by GamerKingFaiz** [comment]
#245 seems to indicate that it will not, so I just want to clarify then if Heroku will ever rate limit or if it is indeed the API I'm calling.

**Comment by Rob--W** [comment]
You're getting a JSON response body with value "Rate limit exceeded.". This doesn't look like anything that CORS Anywhere generates, so it suffices to say that the response that you're getting is from the URL that you're trying to access over the proxy.
