### ISSUE TITLE
The origin "" was not whitelisted by the operator of this proxy.

### ISSUE THREAD

**Issue by fahamakhan** [Rob--W/cors-anywhere#265]
Hey Rob, I am working on a project which requires the resource sharing thing. I am just a newbie and trying to plug your cool tool but every time I make a request it shows me this error
 "The origin "" was not whitelisted by the operator of this proxy."
Please help me.

**Comment by Rob--W** [comment]
I can't provide any help based on this limited description. How does the project look like? I.e. server and client code.

**Comment by fahamakhan** [comment]
Sorry for not providing the context. 
Actually I am working on an iFrame. iFrame doesn't allow to open cross origin sites because of the CSP so what I am doing is I am using your client side code demo.html and converting the response from text to iframe and so far it's working.
But the problem is whenever I try to post data or try to login through the iframe on the opened site it stucks and in console it's saying the conventional error of cors

```
<div id="bottom">
  
</div>

<script>
  var cors_api_url = 'https://cors-anywhere.herokuapp.com/';
  function doCORSRequest(options, printResult) {
    var x = new XMLHttpRequest();
    x.open(options.method, cors_api_url + options.url);
    x.onload = x.onerror = function() {
      x.responseType = 'html';
      printResult(
        (x.response)
      );
    };
    if (/^POST/i.test(options.method)) {
      x.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    }
    x.send(options.data);
  }

  // Bind event
  (function() {
    var urlField = document.getElementById('url');
    var dataField = document.getElementById('data');
    var outputField = document.getElementById('output');
    document.getElementById('get').onclick =
    document.getElementById('post').onclick = function(e) {
      e.preventDefault();
      doCORSRequest({
        method: this.id === 'post' ? 'POST' : 'GET',
        url: urlField.value,
        data: dataField.value
      }, function printResult(result) {
        var iframe = document.createElement('iframe');

// div tag in which iframe will be added should have id attribute with value myDIV
        document.getElementById("bottom").appendChild(iframe);

        // provide height and width to it
        iframe.setAttribute("style","height:100%;width:100%;");
        iframe.contentWindow.document.open();
        iframe.contentWindow.document.write(result);
        iframe.contentWindow.document.close();
      });
    };
  })();
  if (typeof console === 'object') {
    console.log('// To test a local CORS Anywhere server, set cors_api_url. For example:');
    console.log('cors_api_url = "http://localhost:8080/"');
  }
</script>
</body>
```

**Comment by Rob--W** [comment]
CORS Anywhere will only offer the ability to enable CORS, for one request at a time. Your code snippet inserts a response in the body, in unmodified form. While you would receive the initial result (i.e. the HTML), any other requests aren't made through the proxy.

It seems that you're trying to develop a generic proxy based on CORS Anywhere. That is a hard, challenging task, with lots of traps that can cause security issues. I strongly recommend against building such an application, especially without experience, because it is insecure.

This issue doesn't seem to be related to CORS Anywhere itself, so I'm closing it.
