### ISSUE TITLE
Bypass X-Frame-Options

### ISSUE THREAD

**Issue by shuang854** [Rob--W/cors-anywhere#275]
Is there a way to use this in order to bypass the x-frame-options header and allow content to be embedded in an <iframe>? I've tried allowing cookies and removing the header in proxy responses, but nothing I do seems to work properly. For example, installing an extension to remove x-frame-options has allowed me to browse https://www.youtube.com in an <iframe> as if I was on the website. When I use this proxy and strip x-frame-options header, it only kind of works. I've managed to load the website in the <iframe>, but I still run into some issues. Do you have any tips/pointers in what I should do to make this proxy work as if I used a simple browser extension to strip the header?

**Comment by Rob--W** [comment]
What you are looking for is not a proxy that enables CORS for one request, but a way to completely proxy a website and all of its subresources. This is far outside the scope of CORS Anywhere.

If possible, I suggest that you stick with your browser-extension-based approach.
If you want a solution that works without client-side dependencies, then you can look into Service Workers, which allows you to intercept and customize how subresource requests are handled with the "fetch" event.
