### ISSUE TITLE
Cors POST Request not working

### ISSUE THREAD

**Issue by rnagi** [Rob--W/cors-anywhere#279]
I am using the cors-anywhere module on localhost:8080 and it seems like my POST requests are being converted to GET requests.  Please see my request from Chrome developer tools below:  The GET requests seem to be working fine but the POST not so much. Any ideas?

Request URL: http://localhost:8080/test.nexussystems.com/api/pos
Request Method: POST
Status Code: 200 OK
Remote Address: 127.0.0.1:8080
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-credentials: true
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Accept, Authorization
access-control-allow-methods: GET, POST, DELETE, PUT, PATCH, OPTIONS
access-control-allow-origin: *
access-control-expose-headers: cache-control,pragma,content-type,expires,server,x-powered-by,access-control-allow-origin,access-control-allow-credentials,access-control-allow-methods,access-control-allow-headers,date,connection,content-length,x-final-url
cache-control: no-store, no-cache, must-revalidate
connection: close
content-length: 135
content-type: application/json;charset=utf-8
date: Fri, 25 Sep 2020 13:25:35 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
pragma: no-cache
server: Microsoft-IIS/10.0
X-CORS-Redirect-1: 301 https://test.nexussystems.com/api/pos
x-final-url: https://test.nexussystems.com/api/pos
x-powered-by: PHP/7.3.10
x-request-url: http://test.nexussystems.com/api/pos
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJCRU5ERVJTT05URVNUIiwiYXVkIjoidGVzdC5uZXh1c3N5c3RlbXMuY29tIiwiaWF0IjoxNjAxMDQwMzM1LCJhcGkta2V5IjoidG9uNmxLc1J2aDdQQnowRTFOVFRvMHJIWDlCWG5iUHUiLCJleHAiOjE2MDExMjY3MzV9.qbPaymXZm2ma5nzelonQvxvLWi4Zdbl6gC-Fkgy6bqU
Connection: keep-alive
Content-Length: 1198
Content-Type: applicationjson
Host: localhost:8080
Origin: http://aze-d-mriweb01.benderson-dev.com
Referer: http://aze-d-mriweb01.benderson-dev.com/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
{integration_package_name: "JDE", property_id_alt: "5189", vendor_id_alt: "132021",…}
bill_property_id_alt: ""
currency_code: ""
integration_package_name: "JDE"
lines: [{poitem_quantity: 1, poitem_unitprice: 1, glaccount_number: "5313.2",…}]
priority: "urgent"
property_id_alt: "5189"
purchaseorder_budgetoverage_note: ""
purchaseorder_note: ""
purchaseorder_period: "2020-09-01"
purchaseorder_ref: ""
purchaseorder_status: "open"
service_fields: {serviceField1: ""}
ship_property_id_alt: ""
shipping: ""
tax: ""
tax_code_id: ""
universal_field1: ""
universal_field2: ""
universal_field3: ""
universal_field4: ""
universal_field5: ""
universal_field6: ""
universal_field7: ""
universal_field8: ""
userprofile_username: "xxxxxxx"
vendor_id_alt: "132021"

**Comment by Rob--W** [comment]
This is the expected behavior.

In response to HTTP 301, a POST request will be converted to a GET request.
If you'd like to preserve the method and request body, the server must reply with HTTP 308 instead.

If you don't have any control over the destination and still want this to work, then you can disable internal redirects by setting the `maxRedirects` option to `0`.

Oddly, this option is not documented in the README nor does it have any unit tests, but it does work. It's documented inline here: https://github.com/Rob--W/cors-anywhere/blob/a0309e6c475036b4ba2a04372f8d5b6462bd4825/lib/cors-anywhere.js#L260

**Comment by rnagi** [comment]
That did not work.  The API that I am trying to connect to has both a GET and POST method with the same name, but it keeps calling the GET method for some reason.

**Comment by Rob--W** [comment]
Oh right. While setting the `maxRedirects` option to 0 indeed stops CORS Anywhere from following the redirect internally, the browser will still treat the 301 redirect as a redirect where the POST method is converted to GET. There is no generic solution for this.

But in your specific case, you're requesting:
`http://localhost:8080/test.nexussystems.com/api/pos`
and the redirect is to:
`https://test.nexussystems.com/api/pos`

so I think that this is just a generic rule in an attempt to enforce https. If that is the case, then you can get the desired behavior by including the https:-scheme in the initial request:
`http://localhost:8080/https://test.nexussystems.com/api/pos`

**Comment by rnagi** [comment]
Yes adding the https:-scheme did this trick, I had it in there before but I was doing a bit of copy and pasting and must of forgot to update, but thank you that worked great!
