### ISSUE TITLE
How can I set the proxy's 'Host' header to be the target url?

### ISSUE THREAD

**Issue by akarav** [Rob--W/cors-anywhere#282]
My current proxy implementation looks like this:
```
cors_proxy.createServer({
    originWhitelist: [], // Allow all origins
    requireHeader: ['origin', 'x-requested-with'],
    removeHeaders: ['cookie', 'cookie2'],
    httpProxyOptions: {
      xfwd: true,
    },
}).listen(port, host, function() {
    console.log('Running CORS Anywhere on ' + host + ':' + port);
});
```

I have the target url: https://my_target_url.com
And the proxy url: http://corsproxy.com

When I send a request via http://corsproxy.com/https://my_target_url.com, the request's Host header is http://corsproxy.com, but I need it to be https://my_target_url.com

Are there any config options I can change to do this / Is this even possible?

**Comment by iShaVas** [comment]
I have the same issue

**Comment by Rob--W** [comment]
> I have the same issue

That is unlikely. The `Host` header is set to the target. That happens here:

https://github.com/Rob--W/cors-anywhere/blob/70aaa22b3f9ad30c8566024bf25484fd1ed9bda9/lib/cors-anywhere.js#L89
