### ISSUE TITLE
Error 429 Too Many Requests

### ISSUE THREAD

**Issue by niutech** [Rob--W/cors-anywhere#283]
I get the error `429 Too Many Requests`, e.g. for https://cors-anywhere.herokuapp.com/https://raw.githubusercontent.com/JetBrains/lets-plot-kotlin/master/docs/api-reference/plot-api/index.html. Could you please increase the limit for origin https://htmlpreview.github.io? Thanks!

**Comment by Rob--W** [comment]
I'm not going to increase the limit, feel free to self-host CORS Anywhere. Instructions to do so (for free) are at https://github.com/Rob--W/cors-anywhere#demo-server
