### ISSUE TITLE
Missing required request header. 

### ISSUE THREAD

**Issue by gitcior** [Rob--W/cors-anywhere#288]
Hello,
I use XHR to get info from remote server using JavaScript. I got this message today:

"Missing required request header. Must specify one of: origin,x-requested-with" 

All worked fine yesterday. I tried specifying these headers but obviously this didn't help.

Can someone please help / explain? 

Regards

**Comment by Rob--W** [comment]
https://github.com/Rob--W/cors-anywhere/issues/260#issuecomment-664366957

**Comment by gitcior** [comment]
Hi Rob,

Thanks for an answer. I think I might have exceeded 200 requests limit during development.
