### ISSUE TITLE
How to use as a subpath

### ISSUE THREAD

**Issue by Vexcited** [Rob--W/cors-anywhere#291]
Hi,
i have a server Apache that i proxy with Cloudflare.
on it i have a discord bot and cors-anywhere 
my apache port is 80 so cloudflare proxy it
i have cors-anywhere on port 8889 and what i want to do is to proxy this 8889 port to apache with /cors/ subpath
so here is my apache configuration : 
```
<Location /cors/>
    RewriteEngine On
    RewriteRule /cors/(.*) http://127.0.0.1:8889/
</Location>
```
it works but it only show me the help page.
so if i do https://example.com/cors/, it shows me the help page,
but if i do https://example.com/cors/https://anotherwebsite.com,
it shows me the help page too
but if i do without the cors on my local host it works.

i dont think the problem comes from my apache config but it comes from cors-anywhere.
i don't know if there's a var for base url but i tried to modify some things but didn't worked.

i would greatly appreciate any help with figuring out how to use base url with apache. thanks you.

**Comment by Rob--W** [comment]
> I dont think the problem comes from my apache config but it comes from cors-anywhere.

Well, it is definitely an issue with your Apache config. Next time if you run in these kinds of issues, I suggest to replace the underlying application (e.g. CORS Anywhere) with a simple script that simply prints the requested URL/path. That would have shown the issue.

See #201 for more details on configuring Apache.

For others who stumble on this issue and use Nginx, see https://github.com/Rob--W/cors-anywhere/issues/143#issuecomment-452468128
