### ISSUE TITLE
ES6's import syntax

### ISSUE THREAD

**Issue by yvervoort** [Rob--W/cors-anywhere#293]
Hi!

I'm trying to use the NPM module that was published here https://www.npmjs.com/package/cors-anywhere. Since I am working with Wix, I can only import this module using ES6's `import` syntax (CommonJS `require` is not supported). Hence I'm looking to replace the following line: `var cors_proxy = require('cors-anywhere');` and to call the module as follows: `import` _**something**_ `from "cors-anywhere";` to then run the CORS Anywhere server. What should _**something**_ be?

Are there any other changes to be made to the following snippet? How can I initiate the `cors_proxy` object after import?

```
cors_proxy.createServer({
    originWhitelist: [], // Allow all origins
    requireHeader: ['origin', 'x-requested-with'],
    removeHeaders: ['cookie', 'cookie2']
}).listen(port, host, function() {
    console.log('Running CORS Anywhere on ' + host + ':' + port);
});
```

Thanks!

**Comment by Rob--W** [comment]
The equivalent alternative to

```javascript
var cors_proxy = require('cors-anywhere');
```

is

```javascript
import * as cors_proxy from 'cors-anywhere'
```
