### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource CORS BLocked

### ISSUE THREAD

**Issue by sofoniyas-solomon** [Rob--W/cors-anywhere#296]
const ytdl = require("ytdl-core");
const express = require("express");
const cors = require("cors");
const cors_proxy = require('cors-anywhere');
const rateLimit = require("express-rate-limit");

const app = express();

const limiter = rateLimit({
  windowMs: 1 * 60 * 1000, // 10 minutes 20 request
  max: 10 // limit each IP to 100 requests per windowMs
});

//  apply to all requests
app.use(limiter);

var allowedOrigins = ['http://localhost:3000',
  'https://ylight.xyz'];

app.use(cors({
  origin: function (origin, callback) {
    // allow requests with no origin 
    // (like mobile apps or curl requests)
    if (!origin) return callback(null, true);
    if (allowedOrigins.indexOf(origin) === -1) {
      var msg = 'The CORS policy for this site does not ' +
        'allow access from the specified Origin.';
      return callback(new Error(msg), false);
    }
    return callback(null, true);
  }
}));
app.options("*", cors());

const port = 3000;

app.get("/", (req, res) => {
  res.send("Welcome to ylight apis")
})

app.get('/song', async (req, res) =>
  ytdl
    .getInfo(req.query.id)
    .then(info => {
      const audioFormats = ytdl.filterFormats(info.formats, 'audioonly')
      res.set('Cache-Control', 'public, max-age=20000'); //6hrs aprox
      res.json(audioFormats[1].url)
    })
    .catch(err => res.status(400).json(err.message))
)

let proxy = cors_proxy.createServer({
  originWhitelist: [], // Allow all origins
  requireHeader: ['origin', 'x-requested-with'],
    removeHeaders: ['cookie', 'cookie2'] // Do not remove any headers.
});

app.get('/proxy/:proxyUrl*', (req, res) => {
  req.url = req.url.replace('/proxy/', '/'); // Strip '/proxy' from the front of the URL, else the proxy won't work.
  proxy.emit('request', req, res);
});

app.listen(port, () => console.log(`Server is listening on port ${port}.`));

**Comment by Rob--W** [comment]
You have mentioned `curl` in your code, please use curl. Then the problem would be obvious. You should require an `Origin` header to avoid security issues. Without requiring an origin header, your website will be susceptible to arbitrary code execution (moere detail at https://github.com/Rob--W/cors-anywhere/issues/39#issuecomment-387690291 ).

I also recommend you to read the documentation at https://github.com/Rob--W/cors-anywhere#server if you haven't done so.

**Comment by sofoniyas-solomon** [comment]
can you please tell me where the curl is placed - Rob--W

**Comment by sofoniyas-solomon** [comment]
@Rob--W please where did i mentioned curl

**Comment by Rob--W** [comment]
`// (like mobile apps or curl requests)` is right there in the code that you pasted.

Did you even author the code? It is not a good use of your and my time if you copy code without understanding it. When you pass code off as your own and claim that there is a bug in it, I assume that you authored it and that any comments in there are reflecting intentional decisions from you.

With the `curl` command-line program, you can make requests and see the responses, without being affected by the browser's same-origin policy. Sending the request as you intended would have revealed an error message.

`curl` aside, in my last comment I did point out why you're having issues.

**Comment by sofoniyas-solomon** [comment]
so let me remove the curl then it will the cors-anywhere will  allow header??

**Comment by sofoniyas-solomon** [comment]
@Rob--W  so let me remove the curl then it will the cors-anywhere will allow header??

**Comment by Rob--W** [comment]
No... Please read my previous comments and the links. I already explained the problem and provided references to how you can resolve it.

**Comment by sofoniyas-solomon** [comment]
please i am a beginner need help

**Comment by sofoniyas-solomon** [comment]
@Rob--W please i am a beginner need help
