### ISSUE TITLE
Not found because of proxy error: Error: getaddrinfo ENOTFOUND ****** with https://cors-anywhere.herokuapp.com

### ISSUE THREAD

**Issue by a0309nkita** [Rob--W/cors-anywhere#302]
Hi!

I'm working on angular project and from there I'm trying to post some logs to a server, but while hitting that server I got CORS error, and on searching I found that if I append https://cors-anywhere.herokuapp.com with my URL it'll work.

So after adding it my CORS error gone but now I'm getting proxy error like this:- Not found because of proxy error: Error: getaddrinfo ENOTFOUND ..com.

This is my code snippet
const response: any = await axios.post(LOGNESS_LOG_EVENT_URL, event, {
headers: EVENT_HEADERS(bearer),
});

and my LOGNESS_LOG_EVENT_URL is as :- https://cors-anywhere.herokuapp.com/https://********.

Please provide soln to this as I got stuck here.

**Comment by Rob--W** [comment]
I can't help you with this - there are not enough details here. In any case it's not an issue with CORS Anywhere. I suggest that you read up about CORS to solve the issue from your server's end.
