### ISSUE TITLE
http-proxy version has security vulnerability

### ISSUE THREAD

**Issue by chunkybanana** [Rob--W/cors-anywhere#304]
See [this](https://npmjs.com/advisories/1486).

Would be fixed by changing http-proxy version to 1.18.1.

**Comment by Lin2Jing4** [comment]
> Note: as mentioned in https://github.com/Rob--W/cors-anywhere/issues/254#issuecomment-659037020, the security advisory is not applicable to CORS Anywhere.

_Originally posted by @Rob--W in https://github.com/Rob--W/cors-anywhere/issues/253#issuecomment-660671758_

**Comment by chunkybanana** [comment]
Ok, never mind. Thanks!
