### ISSUE TITLE
CORS Error when using self-hosted CORS ANYWHERE?

### ISSUE THREAD

**Issue by Infiniti20** [Rob--W/cors-anywhere#310]
```
Access to XMLHttpRequest at 'https://cors.infiniti20.repl.co/https://create.kahoot.it/rest/kahoots/?query=2020' from origin 'https://kahoot-cheatsheet.infiniti20.repl.co' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
So, why is this happening?
```
var host = process.env.HOST || '0.0.0.0';
var port = process.env.PORT || 8080;
var cors_proxy = require('cors-anywhere');
cors_proxy.createServer({
    originWhitelist: [],
    requireHeader: ['origin', 'x-requested-with'],
    removeHeaders: ['cookie', 'cookie2']
}).listen(port, host, function() {
    console.log('Running CORS Anywhere on ' + host + ':' + port);
});
```
This is the code, but I don't understand why I'm getting the error.

**Comment by Rob--W** [comment]
Your frontend is detecting the "//" in `/https://create.kahoot.it/...` and replacing it with a `/`:

```
$ curl -I 'https://cors.infiniti20.repl.co/https://create.kahoot.it/rest/kahoots/?query=2020' -H 'Origin: https://github.com'
HTTP/2 301 
content-type: text/html; charset=utf-8
expect-ct: max-age=2592000, report-uri="https://sentry.repl.it/api/10/security/?sentry_key=615192fd532445bfbbbe966cd7131791"
location: /https:/create.kahoot.it/rest/kahoots/?query=2020
date: Mon, 25 Jan 2021 17:50:04 GMT
```

The error is unrelated to CORS Anywhere. You should look for a way to disable this URL-rewriting. If that is not possible, then you could try to rely on the feature of CORS Anywhere that it prepends `http://` to the request (or `https://` if `:443` is after the host name) when the scheme is omitted from the start of the destination URL.

**Comment by jensengbg-christian-mosciatti** [comment]
I'm facing the same problem with this URL-rewriting. The service is running as a Firebase function. When I serve it locally it works as expected, but not when deployed, I have to remove `https://` to make it work. @Infiniti20 have you found a solution?
