### ISSUE TITLE
TypeError: env.split is not a function

### ISSUE THREAD

**Issue by pannet1** [Rob--W/cors-anywhere#311]
hi Rob,
I am using your repo as it with just whitelist added.  i have deployed it heroku as recommended.

`//var originBlacklist = parseEnvList(process.env.CORSANYWHERE_BLACKLIST);
var originWhitelist = parseEnvList(['https://goodsite.com', 'https://another.example.com','https://oh.example.com']);

function parseEnvList(env) {
  if (!env) {
    return [];
  }
  return env.split(',');
}

// Set up rate-limiting to avoid abuse of the public CORS Anywhere server.
var checkRateLimit = require('./lib/rate-limit')(process.env.CORSANYWHERE_RATELIMIT);

var cors_proxy = require('./lib/cors-anywhere');
cors_proxy.createServer({
  // originBlacklist: originBlacklist,
  originWhitelist: originWhitelist,`

my app keeps crashing and when i start the server locally i get the following error.
`
/home/sweethome/cors-anywhere/server.js:16
  return env.split(',');
             ^

TypeError: env.split is not a function`

what am i doing wrong.

**Comment by Rob--W** [comment]
Use three backticks to format code blocks. Single backticks can only be used to format code on the same line.

```
var originWhitelist = parseEnvList(['https://goodsite.com', 'https://another.example.com','https://oh.example.com']);

function parseEnvList(env) {
  if (!env) {
    return [];
  }
  return env.split(',');
}
```
^ This code is problematic (and an error in your code, not in CORS Anywhere). `parseEnv` expects a string as input, but you're passing an array. Since you want to end up with an array of origins, just use the array instead of `parseEnvList`:

```diff
-var originWhitelist = parseEnvList(['https://goodsite.com', 'https://another.example.com','https://oh.example.com']);
+var originWhitelist = ['https://goodsite.com', 'https://another.example.com','https://oh.example.com'];

```

**Comment by pannet1** [comment]
Hi Rob,

First and foremost, thank you so much for the wonderful CORS proxy. I figured it out and fixed and now the proxy is up and running in heroku. It is now all clear but initially i adverdantly misread that whitelist requires the list to be in an array. please refer example 2 and 3 under **Server**. 

My requirements are very simple but everyone may not abe able to run a CORS server on the cloud for many reasons. Do you plan to run a public CORS server with a commercial interest.

second, can you eloberate a little bit more on the what happens under the hood when one uses ENV for the lists.

Thank you so much once again Rob.

**Comment by Rob--W** [comment]
> Do you plan to run a public CORS server with a commercial interest.

No, I am not interested. You can self-host if you need one.

> second, can you eloberate a little bit more on the what happens under the hood when one uses ENV for the lists.

Read the code:
- https://github.com/Rob--W/cors-anywhere/blob/528ad7109fa55bdde8055dd035bb16140a29c336/server.js#L6-L25
- https://github.com/Rob--W/cors-anywhere/blob/528ad7109fa55bdde8055dd035bb16140a29c336/lib/cors-anywhere.js#L261-L262
- or the documentation: https://github.com/Rob--W/cors-anywhere/blob/528ad7109fa55bdde8055dd035bb16140a29c336/README.md#server

**Comment by pannet1** [comment]
hi Rob,
on commercial interest, i was just saying, if it did not occur to your mind. if so many people were abusing your heroku offerring, th demand should me more. thats what struck me.

on self hosting, as mentioned earlier, yes, i am running a git clone of yours on heroku on minor tweak on the whitelist.

there was no problem on the ENV list for me to report, just there was no file for me to see what is being obtained. being a total noobie to JS world, that kind was weird for me.

i will thank you on every opportunity. here is one. Thank you so much Rob. Wish you a great year ahead.
