### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by YunisDEV** [Rob--W/cors-anywhere#312]
Hi!
I am using React with Axios to fetch Medium articles. When I am using cors-anywhere, it do not works. 
```js
axios.get('https://cors-anywhere.herokuapp.com/https://medium.com/feed/@yunisdev')
            .then(response => {
                parseString(response.data, (err, res) => {
                    console.log(res)
                })
            })
            .catch(err => {
                console.log(err)
            })
``` 
I have a code like this. It returns an error : `GET https://cors-anywhere.herokuapp.com/https://medium.com/feed/@yunisdev 401 (Unauthorized)`

**Comment by wallena3** [comment]
Pinned issues

**Comment by kthy** [comment]
Trying something similar in Vue 2 with Axios, but I'm getting a `403 (Forbidden)`.

**Comment by boghyon** [comment]
`https://cors-anywhere.herokuapp.com/` is no longer publicly usable. See the pinned issue https://github.com/Rob--W/cors-anywhere/issues/301

**Comment by kthy** [comment]
Right, but I thought it would be usable after doing the challenge?

**Comment by Rob--W** [comment]
@kthy If you saw 403, try again - see the issue (including latest comment from me - I have just updated/restarted the server).

Note: My server does not send the 401 response header. If you see 401, then that's the actual response from the URL that you're requesting.
