### ISSUE TITLE
Install and run your CORS anywhere (like in your web) in a new domain.com on our windows server 2016

### ISSUE THREAD

**Issue by Devselz** [Rob--W/cors-anywhere#314]
Dear @Rob--W , your work is too much appreciable.
We need to implement your cors-anywhere in our own server.
We currently are developing and use a web (say web1) that currently uses your https://cors-anywhere.herokuapp.com/ as a proxy for our CORS with header request to external domains.

Can you assist me or give me a link in order to know how to install your source in order for us to be able to register a new domain.com an duse in say a web2 (where on our queries to https://cors-anywhere.herokuapp.com/ will be replaced to queries to our own hosted web2) so web1 will query cors proxy to web2 to get the response from external websites.

How must or could be implemented in windows server (2016) using IIIS ? if it is required NODE.JS then where to install which folers of your code and how o config run node to start your CORS source in our server

Sorry Im a little newbie in node, altought I have a few other examples of other things setted up with Node (currently installed and running on 2 webs/urls of our server

Many thanks in advance, your project is super helpful.. 

Your  good point is that, using your demo url, we've been able to use custom headers (as wee need custom headers to work in our own setuo of course)

**Comment by Devselz** [comment]
After installed and run node server (well Im using yarn) and try to use the CORS I get:

A potentially dangerous Request.Path value was detected from the client (:)

**Comment by Rob--W** [comment]
Have you seen https://github.com/Rob--W/cors-anywhere#demo-server ? It has sample instructions for setting up on a server. I have also seen instructions for other servers before, but not Windows/IIS, and I myself am not familiar with configuring IIS.

> After installed and run node server (well Im using yarn) and try to use the CORS I get:
>
> A potentially dangerous Request.Path value was detected from the client (:)

I guess that your server filters or normalizes the URL, e.g. treating `:` as dangerous, possibly also replacing `//` with `/`. You should try to disable URL filtering and/or path normalization if possible.

**Comment by Devselz** [comment]
Look at, I installed and followed your docs, then I get (seems) working the server but it dont work.
In my windows 2016 server, I installed your source code, root to: C:\Production\devselz.com\web\ors-anywhere-master

Runing on  the folder: cd "C:\Production\devselz.com\web\cors-anywhere-master\yarn start" I get:

yarn run v1.22.5
$ node server.js
Running CORS Anywhere on 0.0.0.0:8080

That you can see by https://devselz.com/ors-anywhere-master/ and https://devselz.com/ors-anywhere-master/demo.html

but seems it does not work:

just look at the 2 escenarios I set:

SCENARIO #1 (DEFAULT): C:\Production\devselz.com\web\cors-anywhere-master\
yarn run v1.22.5
$ node server.js
Running CORS Anywhere on 0.0.0.0:8080

DEFAULT CODE
https://devselz.com/cors-anywhere-master/https://api.github.com/user
RETURN ME 
A potentially dangerous Request.Path value was detected from the client (:).

SCENARIO #2 : C:\Production\devselz.com\web\cors-anywhere-master-mod1\
I use the same code, but I needed to change the IP host 
on server.js I set:
var host = process.env.HOST || '163.172.111.39'; //163.172.111.39 is the IP of the windows server 2016 with devselz.com
and on web.config to avoid the error "A potentially dangerous Request.Path value was detected from the client (:)." I set:
<system.web>
    <customErrors mode="Off" />
    <httpRuntime requestPathInvalidCharacters="&lt;,&gt;,*,%,&amp;,:,\,?" />
</system.web> 

C:\Production\devselz.com\web\cors-anywhere-master-mod1>start_yarn.txt.bat
yarn run v1.22.5
$ node server.js
Running CORS Anywhere on 163.172.111.39:8080

Now there's no error but just a 404
https://devselz.com/cors-anywhere-master-mod1/https://api.github.com/user

May I need to use rewrite to redirect all after the slash (/) after "https://devselz.com/cors-anywhere-master-mod1" to say locahost or where it is supposedly running ?

**Comment by Devselz** [comment]
On my windows 2016 server: 

SCENARIO 1 DEFAULT
If I run:
http://localhost:8080/
I get the same as in 
SCENARIO 2 (var host = process.env.HOST || '163.172.111.39'; ) 
I run: 
163.172.111.39:8080

Both scenarios gets:

```
This API enables cross-origin requests to anywhere.
Usage:
/               Shows help
/iscorsneeded   This is the only resource on this h...
```
But if I use the url on server local chrome

**Comment by Devselz** [comment]
What I need is to be able to call this working local urls, but externally , ike from other web at other hosted ip (other webserver)
what I need to do to externally go to the http://localhost:8080/ of the windows server 2016 where CORS Anywhere is installed ?

**Comment by Devselz** [comment]
I use a 3rd escenario set to 0.0.0.0 port 8082 and using rewrite IIS:
PATH C:\Production\devselz.com\web\cors-anywhere-master-mod2
cd "C:\Production\devselz.com\web\cors-anywhere-master-mod2\yarn start"
CONSOLE REPORTS
yarn run v1.22.5
$ node server.js
Running CORS Anywhere on 0.0.0.0:8082

It seems to be working on windows server but locally if I run Chrome on the same computer windows server 2016
http://localhost:8082/https://google.com

shows me 
`Missing required request header. Must specify one of: origin,x-requested-with`

So that sign (as my before post comment) may indicate that it is working, but how to access remotely from other server, say from your computer

**Comment by Devselz** [comment]
Setted up rewrite on scenario 3 now I can access the localhost:8282 remotely but I cannot use if I search anything after the last slash /

SCENARIO 3: web.config to allow redirect:


```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
<system.web>
    <customErrors mode="Off" />
    <httpRuntime requestPathInvalidCharacters="&lt;,&gt;,*,%,&amp;,\,?" />

</system.web> 
<system.webServer>
	  <httpProtocol>
		  <customHeaders>
			  <add name="Access-Control-Allow-Origin" value="*" />
		  </customHeaders>
	  </httpProtocol>

   <rewrite>
        <rules>
            <rule name="ReverseProxyInboundRule1" stopProcessing="true">
                <match url="(.*)" negate="false" />
                <action type="Rewrite" url="http://localhost:8082/{R:1}" />
            </rule>
        </rules>
    </rewrite>
    <tracing>
        <traceFailedRequests>
            <add path="*">
                <traceAreas>
                    <add provider="WWW Server" areas="Security,StaticFile,Module" verbosity="Verbose" />
                </traceAreas>
                <failureDefinitions timeTaken="00:00:00" statusCodes="100-999" />
            </add>
        </traceFailedRequests>
    </tracing>
</system.webServer>
</configuration>
```


so see:
https://devselz.com/cors-anywhere-master-mod2/https://api.github.com/user
produces the same result as
https://devselz.com/cors-anywhere-master-mod2/

So what I need to do to resolve ?

**Comment by Devselz** [comment]
SCENARIO 3
Seems that only parses an url with no more paths :
THIS SEEM TO WORK
https://devselz.com/cors-anywhere-master-mod2/google.com

THIS SEEM TO WORK
https://devselz.com/cors-anywhere-master-mod2/api.github.com

THIS NOT
https://devselz.com/cors-anywhere-master-mod2/https://api.github.com

**Comment by Devselz** [comment]
Ohh man.. so happy I would need to make a tutorial

**Comment by Devselz** [comment]
MANUAL: INSTRUCTIONS FOR SETUP CORS ANYWHERE AND HOST ON WINDOWS SERVER IIS ASP.NET NODE.JS

On windows server be sure that you have installed Node and Yarm

Unzip the source code to (say): 
C:\Production\yourdomain.com\web\cors-anywhere-master-mod2/
which translates to: www.yourdomain.com/cors-anywhere-master-mod2/

Add a web.config file and write:
```

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
<system.web>
    <customErrors mode="Off" />
    <httpRuntime requestPathInvalidCharacters="&lt;,>,*,%,&amp;,\,?" />
</system.web> 
<system.webServer>
   <rewrite>
        <rules>
            <rule name="ReverseProxyInboundRule1" stopProcessing="true">
                <match url="(.*)" negate="false" />
                <action type="Rewrite" url="http://localhost:8082/{R:1}" />
            </rule>
        </rules>
    </rewrite>
    <tracing>
        <traceFailedRequests>
            <add path="*">
                <traceAreas>
                    <add provider="WWW Server" areas="Security,StaticFile,Module" verbosity="Verbose" />
                </traceAreas>
                <failureDefinitions timeTaken="00:00:00" statusCodes="100-999" />
            </add>
        </traceFailedRequests>
    </tracing>
</system.webServer>
  </configuration>
```

Create a file to be loaded on start (callit from regedit current computer (not user/ run..
That .bat file will start node to your cors anywhere when server starts (if you want to run do manually)

```
@echo off
for /f "tokens=2 delims=:." %%x in ('chcp') do set cp=%%x
chcp 1252>nul

cd "C:\Production\yourdomain.com\web\cors-anywhere-master-mod2"
yarn start

chcp %cp%>nul

```

Edit server.js
Update line to:
`
var port = process.env.PORT || 8082;

`

In your code, when you need to get a response from a third party not cors enabled website use:
`
var cors_api_url = 'https://yourdomain.com/cors-anywhere-master-mod2/';

`

BUT DO NOT PASS http://or https:// on request so just use say code below, as example to use Github Sign Oauth



```

function loginGitHub1(){
    dzRandomStateString = uuidv4();
    var dzLogSignDHPopup = window.open("https://github.com/login/oauth/authorize?scope=read:user&client_id=" + YOURCLIENTID  + "&response_type=code&state=" + RANDOMSTATESTRING, "Git Hub Login","location=1,status=1,scrollbars=1,resizable=no,width=600,height=500,menubar=no,toolbar=no");
    var eventMethod = window.addEventListener ? "addEventListener" : "attachEvent"; var eventer = window[eventMethod]; var messageEvent = eventMethod == "attachEvent" ? "onmessage" : "message";
    eventer(messageEvent,function(e) {
        if( e.origin.indexOf("https://YOURDOMAIN.COM") >= 0 ){
            if((e.data.code !== null) || (e.data.code !== "undefined")){
                  console.log('origin: ', e.origin); console.log("e.data.code: " + e.data.code); console.log("e.data.state: " + e.data.state);
                  var dzLogSignDHPopup2 = "github.com/login/oauth/access_token?client_id=" + dzLogSignGHClientId + "&client_secret=" +  dzLogSignGHClientIdSecret + "&code=" + e.data.code  + "&state=" + e.data.state;
                  function doCORSRequest(options, printResult) {var x = new XMLHttpRequest();x.open(options.method, cors_api_url + options.url);x.onload = x.onerror = function() {printResult(x.responseText);}; if (/^POST/i.test(options.method)) {x.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');}; x.send(options.data); };
                  function doCORSRequest2(options, printResult) {var x = new XMLHttpRequest();x.open(options.method, cors_api_url + options.url);x.onload = x.onerror = function() {printResult(x.responseText);}; x.setRequestHeader('Authorization', 'Bearer ' + token);x.setRequestHeader('Content-Type', 'application/vnd.github.v3+json'); x.setRequestHeader('Accept', 'application/vnd.github.v3+json'); x.send(options.data); };  doCORSRequest({method: 'POST', url: dzLogSignDHPopup2, data: ""}, function printResult(result) { if(result.indexOf("access_token=") >= 0){token = result.substring(13); token = token.substring(0, token.indexOf("&")); doCORSRequest2({method: 'GET', url: "api.github.com/user?token_type=bearer&scope=read:user", data: "api.github.com/user?token_type=bearer&scope=read:user"}, function printResult(result2) { var obj = JSON.parse(result2); loginGitHub2(obj); console.log("GH user data: " + result2); }); }else{alert("BAD Login or Error connecting to CORS server");}; });
            } }else{ return }; console.log('parent received message!: ', e.data);
    }, false);
};


```

**Comment by Rob--W** [comment]
Thanks for sharing your instructions. I didn't verify them myself, but hope that it may help others. The "BUT DO NOT PASS http://or https://" does suggest that you did still not manage to get around the `:` warning or `//` normalization, which is not ideal. For cases where you don't need `:` or `//`, the method may be good enough.
