### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by AlexWhitehouse** [Rob--W/cors-anywhere#321]
When I use the demo to access `"https://query1.finance.yahoo.com/v8/finance/chart/eth-usd?&period1=0&period2=9999999999&interval=1d"` on my home WIFI it works fine. When I try the exact same thing on LTE it returns a 403 forbidden error.

Any help?

**Comment by Rob--W** [comment]
Have you seen the pinned issue, #301 ?

**Comment by AlexWhitehouse** [comment]
Thanks for the response this seems to be the issue :(
Do you know any easy way to migrate from cors-anywhere to be able to simply extract the data from the above URL?

**Comment by Rob--W** [comment]
301 lists several options including easy alternatives. Self-hosting is the most reliable solution.
