### ISSUE TITLE
where set this in herolu

### ISSUE THREAD

**Issue by geetee24** [Rob--W/cors-anywhere#324]
Where do i set this in heroku?

export PORT=8080
export CORSANYWHERE_BLACKLIST=https://abuse.example.com,http://abuse.example.com
export CORSANYWHERE_RATELIMIT='50 3 my.example.com my2.example.com'
node server.js

**Comment by Rob--W** [comment]
The README links to https://devcenter.heroku.com/articles/getting-started-with-nodejs

which has a section "Define config vars" at https://devcenter.heroku.com/articles/getting-started-with-nodejs#define-config-vars
which provides some details, and also links to a more detailed tutorial at https://devcenter.heroku.com/articles/config-vars
