### ISSUE TITLE
How to add another referer to Cors-Anywhere

### ISSUE THREAD

**Issue by cassahd7** [Rob--W/cors-anywhere#326]
There is a site that works this way
https://My-cors-anywhere-proxy.com/&exampel.com/https://hls-exampel.com/index.m3u8
Please help via code or anything for me to do the same

**Comment by Rob--W** [comment]
You cannot choose an arbitrary value for the request from a website that uses CORS Anywhere.

If you run your own instance of CORS Anywhere, then you can use the `setHeaders` option to set a custom value for the Referrer request header.
