### ISSUE TITLE
What does it mean when cors-anywhere responds with "Empty reply"

### ISSUE THREAD

**Issue by smelehy** [Rob--W/cors-anywhere#327]
I have set up my own RHEL 8.3 server on AWS to run cors-anywhere.  I used the CalTech Scripts to run it.  I'm using curl to test response.

heroku demo server:  
`curl -H "X-Requested-With: XMLHttpRequest" http://cors-anywhere.herokuapp.com/http://google.com`
returns the html just fine - works as intended.

my aws server:
`curl -H "X-Requested-With: XMLHttpRequest" http://my-aws-server-hostname:8080/http://google.com`
returns:  curl: (52) Empty reply from server

I have checked the log files and everything looks fine - no errors.  I watched the connection request with 
` tcpdump -ni any port 8080` .  I can see the requests come in.  

`netstat`  shows corsproxy listening on port 8080

log files I checked:
`tail -f on /var/log/messages`
`tail -f /var/log/corsproxy/corsproxy.log`

`systemctl status corsproxy.service` shows the following
```
Feb 20 23:40:48 ip-172-31-14-40.us-east-2.compute.internal corsproxy-helper[1510]: <30>Feb 20 23:40:48 corsproxy: Ratelimit configuration: "30 60"
Feb 20 23:40:48 ip-172-31-14-40.us-east-2.compute.internal corsproxy-helper[1510]: <30>Feb 20 23:40:48 corsproxy: Required headers: ["X-Requested-With"]
Feb 20 23:40:48 ip-172-31-14-40.us-east-2.compute.internal corsproxy-helper[1510]: <30>Feb 20 23:40:48 corsproxy: Origin whitelist: ["opsdevlist.com"]
Feb 20 23:40:48 ip-172-31-14-40.us-east-2.compute.internal corsproxy-helper[1510]: <30>Feb 20 23:40:48 corsproxy: Origin blacklist: []
Feb 20 23:40:48 ip-172-31-14-40.us-east-2.compute.internal corsproxy[1519]: Ratelimit configuration: "30 60"
Feb 20 23:40:48 ip-172-31-14-40.us-east-2.compute.internal corsproxy[1519]: Required headers: ["X-Requested-With"]
Feb 20 23:40:48 ip-172-31-14-40.us-east-2.compute.internal corsproxy[1519]: Origin whitelist: ["opsdevlist.com"]
Feb 20 23:40:48 ip-172-31-14-40.us-east-2.compute.internal corsproxy[1519]: Origin blacklist: []
Feb 20 23:40:50 ip-172-31-14-40.us-east-2.compute.internal corsproxy-helper[1510]: <30>Feb 20 23:40:50 corsproxy: Server started successfully with PID 1521.
Feb 20 23:40:50 ip-172-31-14-40.us-east-2.compute.internal systemd[1]: Started CORS proxy service.
```
My config.sh file has:
`HOST="0.0.0.0"
PORT="8080"
RATELIMIT="30 60"
REQUIRED_HEADER="X-Requested-With"
`

**Comment by Rob--W** [comment]
`Empty reply from server` is not a response from CORS Anywhere. If a request is rejected by CORS Anywhere, you'll get a response.

Are you sure that your request is routed to the CORS Anywhere application?

Side note, your value for `Origin whitelist` is incorrect. For the syntax, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin

**Comment by smelehy** [comment]
Thank you for the information.  I’ll do some more digging into it, and thanks for the correction on whitelist.

 

Sam Melehy

+1 760 39 7216

San Diego, CA

**Comment by smelehy** [comment]
I was using a third party script to run it and it was failing to run the server when the service started.  This is resolved...
