### ISSUE TITLE
Only at a specific site return "unable to verify the first certificate"

### ISSUE THREAD

**Issue by sangmin802** [Rob--W/cors-anywhere#329]
First of all, please understand that I am not good at English.

For learning purposes, I was using this feature to import specific website information in text format. However, other websites work well, but only one site has an error 'Not found cause of error: error: enable to verify the first certificate'. I'd like to know if the server that distributes the website is blocking this approach or if I'm using it incorrectly.

For your information, we haven't modified the git hub you provided since we forked it.

**Comment by Rob--W** [comment]
You haven't shared the site, so I cannot investigate this. This is most likely an incorrectly configured server.

A similar issue was reported before, and I explained the steps to debug the issue (and work around it in the worst case) at https://github.com/Rob--W/cors-anywhere/issues/99
