### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by melwinlobo18** [Rob--W/cors-anywhere#332]
I'm getting `Client network socket disconnected before secure TLS connection was established` when I try to access a specific API through cors-anywhere. I'm able to **curl** to the site through the VM but I get the above error when I request through cors-anywhere.

I'm not sure what's causing this issue.

**Comment by Rob--W** [comment]
I don't know either, there is not enough information here for me to tell.

Have you tried to write a simple Node.js script that requests the URL, to see if it may be specific to your Node.js version/dependencies?

And when you ran `curl`, did you use the same request (including headers)?

To debug this, you can use Wireshark; start Node.js with `SSLKEYLOGFILE=/tmp/path_for_keylog.log` to log the keys and load this file in Wireshark to decrypt the encrypted traffic. Then you can more easily compare the requests to figure out the difference between a successful request (curl?) and the failing one.
