### ISSUE TITLE
429 (Too Many Requests) when trying to get meta data for YouTube videos

### ISSUE THREAD

**Issue by ClydSpyd** [Rob--W/cors-anywhere#333]
Hello.

Firstly, thanks for the great tool! 

I'm currently having an issue when trying to receive Youtube meta data to use a link previews on a site I'm working on. For this I use a Node Package named 'link-preview-js', which requires a CORS proxy server. 

CORS-anywhere was working just fine initially, prepending the video URLs with the CORS-anywhere demo URL. Then I started to get this 'too many requests' error and so thought perhaps I'd made too many calls (even though I have not made many) and so I cloned the repo and hosted my own CORS-anywhere on Heroku. Strangely enough, I am still getting the error.

It only seems to happen on YouTube videos, as DailyMotion videos give me no error and return the data I need. 

Any idea what may be causing this issue?

Many thanks,
Dave

**Comment by Rob--W** [comment]
Look at the exact response body of the response. That will tell you whether the issue is with the proxy or the actual response from the server (i.e. YouTube).
