### ISSUE TITLE
Suggestion: Logging using handleInitialRequest

### ISSUE THREAD

**Issue by blake41** [Rob--W/cors-anywhere#335]
The latest feature you added "handleInitialRequest" is a great place to hook in for logging.  You can just have your function essentially act as middleware and return false at the end.  Just adding this in case other people are looking for a good place to hook in for logging/debugging.  Might want to add to the readme

**Comment by Rob--W** [comment]
The option is documented in the README (and in the unit test), when the feature was introduced at https://github.com/Rob--W/cors-anywhere/commit/9f1af8243463ab71b63b889fff5606bd908f36cc

What else should I document?

**Comment by blake41** [comment]
Sorry maybe I wasn't clear.  I'm using it for logging/debugging.  I don't see that mentioned in the readme and thought it might be helpful to someone if you added that note.

**Comment by Rob--W** [comment]
Done!

**Comment by blake41** [comment]
Awesome, also apologize if my message came off as complaining, was trying to be helpful.  This is so useful, thanks for creating it.  Was going to use it for a project and worked so well I replaced another proxy i was using for a different project with this one
