### ISSUE TITLE
Not found because of proxy error: Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by bhaskaranbe** [Rob--W/cors-anywhere#338]
When calling GET request using Ajax for other domain API, it returns "unable to verify the first certificate". 

The Option request is getting success (200) in the response.

The CORS is running on port 8080 in the server. our site URL is: https://777sweeps.com/ and CORS url is: https://777sweeps.com:8080/

note: The server running in Google cloud platform.
When we are running in local its working fine.

**Comment by Rob--W** [comment]
There are not enough details to investigate here. Your server appears to work, at least against `https://example.com/`.

A similar issue was reported before, and I explained the steps to debug the issue (and work around it in the worst case) at https://github.com/Rob--W/cors-anywhere/issues/99

**Comment by Rob--W** [comment]
FYI: I've fixed an issue that prevented `NODE_TLS_REJECT_UNAUTHORIZED=0` from working in https://github.com/Rob--W/cors-anywhere/commit/3c87a51664bc625535afcecc4e618009ff41d2ce (after investigating #341)

You have to update your version of CORS Anywhere to the latest (master branch) to take advantage of the feature. I haven't published an update yet.
