### ISSUE TITLE
how to setup cors-anywhere at our server

### ISSUE THREAD

**Issue by vipinv86** [Rob--W/cors-anywhere#34]
Hi, 
Please let me know how can i setup the CORS-anywhere setup at our server, I have downloaded the library files and put on the server, do let me know  the steps.

**Comment by Rob--W** [comment]
If you're happy with the default settings, just start `server.js`. Otherwise edit `server.js` to change some settings (https://github.com/Rob--W/cors-anywhere#server) and then start `server.js` (e.g. using `node server.js`).
