### ISSUE TITLE
3 days ago started getting error: 404  Not found because of proxy error: Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by geetee24** [Rob--W/cors-anywhere#341]
starting 3 days ago:

https://aaaaaa8.herokuapp.com/https://www.comicskingdom.com/sherman-s-lagoon

and getting 404  Not found because of proxy error: Error: unable to verify the first certificate

tried setting NODE_TLS_REJECT_UNAUTHORIZED=0 and restart the app. MADE no difference. same error.

Any advice?

**Comment by Rob--W** [comment]
Fixed in https://github.com/Rob--W/cors-anywhere/commit/3c87a51664bc625535afcecc4e618009ff41d2ce
