### ISSUE TITLE
Images Not Proxied Correctly

### ISSUE THREAD

**Issue by dkaoster** [Rob--W/cors-anywhere#342]
## Problem: Unable to Proxy to the url of an image

If I try to proxy to an image, (https://cors-anywhere.herokuapp.com/https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1200px-Image_created_with_a_mobile_phone.png) for example, I receive a page that has the following error:

`The image “https://cors-anywhere.herokuapp.com/https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1200px-Image_created_with_a_mobile_phone.png” cannot be displayed because it contains errors.`

I'm seeing this when I run cors-anywhere locally as well. Could it be a setting that I missed somehow?

**Comment by Rob--W** [comment]
This is in Firefox, right? have you opened the developer tools? The console shows:

> GEThttps://cors-anywhere.herokuapp.com/https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1200px-Image_created_with_a_mobile_phone.png
[HTTP/1.1 400 Header required 140ms]

The response body is:

> Missing required request header. Must specify one of: origin,x-requested-with

Image requests aren't with cors by default. If you want to enable CORS, set the `crossorigin` attribute on the `<img>` tag (CORS Anywhere only supports `"anonymous"` / `""`).

See https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/crossOrigin and https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin

**Comment by dkaoster** [comment]
Oh, that makes sense - thanks @Rob--W!
