### ISSUE TITLE
Minor error in README.md

### ISSUE THREAD

**Issue by hexleyOlive** [Rob--W/cors-anywhere#347]
Hi,

In the README.md, Example section include "Request examples" this one give the example below :
http://localhost:8080/ - Shows usage text, as defined in **libs**/help.txt

Path libs/help.txt should be lib/help.txt

**Comment by Rob--W** [comment]
Thanks for spotting this. Are you interested in creating a pull request?

**Comment by hexleyOlive** [comment]
Thanks for the proposition, but i'm a only a occasional user of GitHub and not a good dev ;-)

**Comment by inyourface34456** [comment]
I could make a pull request.
