### ISSUE TITLE
LimitInternalRecursion

### ISSUE THREAD

**Issue by hexleyOlive** [Rob--W/cors-anywhere#348]
Hi,

I would to try locally cors-anywhere for tests.
After install, the demo page work (http://myip:8080/demo.html), but each test with external URL fail with an apache error below, any idea about the root cause?

`Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://myip:8080/google.com`

Same error with another URL, example http://myip:8080/http://www.africau.edu/images/default/sample.pdf
I tried to increase the LimitInternalRecursion value, but same result.

Thanks

**Comment by Rob--W** [comment]
This looks like an issue with your Apache configuration, independent of CORS Anywhere.
