### ISSUE TITLE
Proxy bookmarklet

### ISSUE THREAD

**Issue by inyourface34456** [Rob--W/cors-anywhere#350]
Would it be possible to make a proxy in a bookmarklet (using something like a token to prevent spamming)?  I would like to know this so i can make a proxy server without have to setup something like [tor](www.torproject.org/)?  Would it also be possible to make it 'just work' (like, work without any preconfig and things of that nature)?

**Comment by Rob--W** [comment]
This project is not intended to be used as a generic web proxy, but as a tool to allow developers to request public data from sites that don't support CORS.
