### ISSUE TITLE
403 Forbidden Cloudflare "Issue"?

### ISSUE THREAD

**Issue by amg2nd** [Rob--W/cors-anywhere#352]
First off, thank you for taking the time to create cors-anywhere. I know more than a little when it comes to JavaScript and HTML, but I would still consider myself a novice.

I was using a clone of your code on Heroku to pull scripture text from bible.com and reformat it into a more presentable view for my church. It seems bible.com is now using Cloudflare so now even when using your demo, https://robwu.nl/cors-anywhere.html to get https://www.bible.com there is a 403 Forbidden response with Cloudflare html

Is this an issue, is there a way to configure cors-anywhere to work with Cloudflare to still be able to get the text, or is this just Cloudflare working like it's supposed to and the cors-anywhere solution I was using will no longer work for me?

**Comment by christiaan20** [comment]
I had the same issue if you do the request and then press F12 on your browser you should be able to see the response in the network section, it should say something like "The origin "chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop" was not whitelisted by the operator of this proxy." you need to whitelist that origin like shown in the server setup instructions

**Comment by amg2nd** [comment]
@christiaan20 thank you for the suggestion, but I'm not sure that is my issue... that I know of. When using the demo and my clone on Heroku, any other url I try, like https://biblia.com works as expected; 200 OK. At the moment, for dev purposes, I don't have anything white/blacklisted so all origins are allowed. I also do not see that "was not whitelisted" response in the network section/tab or console tab in Chrome. I could rewrite my code to work with biblia.com instead, but I was just wondering if there was a way to get it to work with the Cloudflared bible.com before I started the rewrite

**Comment by Rob--W** [comment]
When Cloudflare is in front of a website and requiring the completion of a challenge, then you cannot use CORS Anywhere since it is a proxy that doesn't persist data/cookies.

**Comment by amg2nd** [comment]
@Rob--W I figured that was probably the case. Thank you
