### ISSUE TITLE
Need help with a post request...

### ISSUE THREAD

**Issue by slayer1ss** [Rob--W/cors-anywhere#356]
Hi, i am trying to make a post request to a domain that sends back a url which contains a custom token per request... I have tried almost everything i can think of and i am about to give up... I would be glad if you can tell me if there is a way to do this or i am just wasting my time... 

Domain i am trying to make the post request is https://lite-1x287006.com/cinema , post request contains {"VideoId":"5493271","Token":null,"AppId":2} in json format. Video ids are dynamic and might be inaccessible when you try... 

When i make the request without proxy i get the response like below and i can download m3u8 file via my browser... 
{"FullscreenAllowed":true,"URL":"https:\/\/edge10.xmediaget.com\/hls-live\/5493271\/1\/mediaplaylist.m3u8?s=2d0323d609fdb10412f66ff28938c8ecefd54c57069e74e282129bfff3ac9dd6&t=1621038525789&ai=2&av=0&ui=0"}

When i use the proxy it responds like below and it doesnt download because verification token is wrong... 
{"FullscreenAllowed":true,"URL":"https:\/\/edge2.xmediaget.com:43434\/hls-live\/5493271\/1\/mediaplaylist.m3u8?s=2c2453c30764206108b4c7c40ef39739ef3e782824446a00630e787ca67ef523&t=1621038525781&ai=2&av=0&ui=0"}

I am guessing it is because of proxy ip is not the same as visitor ip, i tried setting x-forwarded-for manually to make sure it is not because of this but nothing changed... Can you tell me what i am missing please?

**Comment by Rob--W** [comment]
What is the response that you're getting? Are you self-hosting CORS Anywhere? The public demo doesn't allow requests to m3u8 URLs because of prior abuse.

**Comment by slayer1ss** [comment]
Thx for the response, i made a fork of the repo a while back and been using it at heroku. Fork is up to date with the repo and since i am the only one using it i didnt have any limitation problems... 

Problem is that security tokens generated by responding server is changing between proxy and non proxy usage. I am making a post request to remote server basically asking them to give me the m3u8 url, this returning m3u8 url contains a security token to identify visitors and block access if it doesnt match. I dont know how they generate the token or which parameters they use but i am thinking problem is caused because of the ip difference between proxy and non proxy usage...

 Without proxy response is like;
{"FullscreenAllowed":true,"URL":"https://edge10.xmediaget.com/hls-live/5493271/1/mediaplaylist.m3u8?s=2d0323d609fdb10412f66ff28938c8ecefd54c57069e74e282129bfff3ac9dd6&t=1621038525789&ai=2&av=0&ui=0"}

With proxy response is like;
{"FullscreenAllowed":true,"URL":"https://edge2.xmediaget.com:43434/hls-live/5493271/1/mediaplaylist.m3u8?s=2c2453c30764206108b4c7c40ef39739ef3e782824446a00630e787ca67ef523&t=1621038525781&ai=2&av=0&ui=0"}

Basic difference between them is the response data url hostname, doesnt matter how many requests i make if i am not using a proxy response i always get a domain starting with edge10.xmediaget.com , if i am using a proxy that value changes between from edge1 .xmediaget.com to edge5.xmediaget.com , like i said i am only guessing but it seems like they send me data based on proxy ip... 

I tried manually setting x-forwarded-for and user-agent headers to my real data to make sure they are not the problem but that didnt work too... I would be glad if you can tell me what i am trying to do is possible and send me to right direction...

**Comment by Rob--W** [comment]
To check whether the issue is specific to the proxy (and not the IP), host CORS anywhere locally (at localhost) and try that.

If it works, then it may be an issue with the IP address. Now try to proxy all requests; not just the m3u8 resource but also the media resources.

If it didn't work, check whether there are too many or too few request headers - compare the headers of the working and non-working cases.

**Comment by slayer1ss** [comment]
Thx for the response i just install nodejs to my pc and tried to proxy the request locally and it worked so it is clearly because of the proxy ip not being same as visitor ip... Could there be a fix for this should i just give up?

**Comment by Rob--W** [comment]
>  Could there be a fix for this or should i just give up?

Like I said, use the same IP to send both requests.
