### ISSUE TITLE
news.google.com -> 403 Forbidden

### ISSUE THREAD

**Issue by filly82** [Rob--W/cors-anywhere#358]
I guess news.google.com has some extra security because google.com works
It's not a general problem with news.google.com because it works on platforms where CORS is not an issue (native calls)

Anything we (you or I myself) can do about it? I have cors-anywhere on my own server

![grafik](https://user-images.githubusercontent.com/4948973/118955109-b1717800-b95e-11eb-97f7-09af2ce5f8f9.png)

**Comment by TheoOliveira** [comment]
I've tried to use with a api from aws. Same response.

**Comment by Rob--W** [comment]
Not an issue with CORS Anywhere, but something specific to your destination server.
