### ISSUE TITLE
Proxy static files (images, scripts etc)

### ISSUE THREAD

**Issue by mayeaux** [Rob--W/cors-anywhere#359]
I am trying to use this to replicate the functionality of a Chrome Extension I use called `Allow CORS: Access-Control-Allow-origin`. I am doing this so I can access a site on mobile using `ngrok` but where I need certain CORS values to be added.

However, as it's a single page application I need the script, and also the images to come through correctly. For example if I proxy `google.com`, via accessing `http://localhost:8080/google.com`

I receive 404 errors on most of the static files, such as `http://localhost:8080/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png` 

Is there a way to also proxy correctly these static files so I can see a correct page displayed, with the images, scripts etc? Thanks

**Comment by Rob--W** [comment]
It sounds like you're looking for a generic web proxy that proxies subresources too. That's beyond the scope of this project; CORS Anywhere is only meant to add CORS headers to single responses.
