### ISSUE TITLE
Is there a way to only whitelist certain URLs the proxy server can handle?

### ISSUE THREAD

**Issue by prathamesh-gharat** [Rob--W/cors-anywhere#360]
I am trying to use this proxy for internal purposes and want to only allow certain URLs to be proxied through your cors-anywhere. How can I do this?

Please note: This is not about CORS headers. This is a server-to-server use case.

**Comment by Rob--W** [comment]
This functionality is not supported yet, but can be added at https://github.com/Rob--W/cors-anywhere/blob/02f0cbd9291eca55953406acc7f7f08c64d13454/lib/cors-anywhere.js#L80 . An example of an implementation is posted at https://github.com/Rob--W/cors-anywhere/issues/78
