### ISSUE TITLE
cors issue in videojs

### ISSUE THREAD

**Issue by sploit30** [Rob--W/cors-anywhere#363]
Can i play m3u8 video by this url i already fetch cors issue in reactjs

**Comment by Rob--W** [comment]
You can if you self-host CORS Anywhere. m3u8 URLs are blocked on the public demo because of previous abuse.

**Comment by sploit30** [comment]
please explaing it i dont
Have any idea about this...

**Comment by Rob--W** [comment]
See the README for instructions on self-hosting.
