### ISSUE TITLE
How to set the rateLimit

### ISSUE THREAD

**Issue by lqdahv** [Rob--W/cors-anywhere#365]
What should I change?

![QQ截图20210706041049](https://user-images.githubusercontent.com/24808833/124515017-f66b4400-de10-11eb-8169-7cd27f36ee8d.jpg)
 :)

**Comment by Rob--W** [comment]
If you want to use the default implementation of the rate limit logic (i.e. you're using `server.js`), set the `CORSANYWHERE_RATELIMIT` environment variable as shown at the bottom of https://github.com/Rob--W/cors-anywhere#demo-server

If you want to fully customize the rate limiting logic with code, set the `checkRateLimit` function in the call to `createServer` (either by editing `server.js` or by passing it to the function when you're using `cors-anywhere` as a library.

In server.js:
https://github.com/Rob--W/cors-anywhere/blob/02f0cbd9291eca55953406acc7f7f08c64d13454/server.js#L27

Documentation for the options when used as a library:
https://github.com/Rob--W/cors-anywhere#server
