### ISSUE TITLE
a proxy a day..

### ISSUE THREAD

**Issue by mhrisse** [Rob--W/cors-anywhere#37]
Hi!

I have a use-case where I would like to run this package behind a corporate firewall. So I would need the cors-anywhere reverse proxy to go through http(s)://proxy.example.com to fetch from the origin. Is this supported (basically I would want the proxy to pickup the settings in the env variables http_proxy or https_proxy like chrome and other tools do, but setting it explicitly would also be fine.)? Any clues? Your help would be very much appreciated.

**Comment by Rob--W** [comment]
I've added the  `getProxyForUrl` option. The default implementation takes the proxy configuration from the environment variables (using the separately published library at https://github.com/Rob--W/proxy-from-env). Give it a try!

**Comment by mhrisse** [comment]
Awesome, thanks a lot, Rob!
