### ISSUE TITLE
Question: SSL certificate verification

### ISSUE THREAD

**Issue by c4kaci** [Rob--W/cors-anywhere#371]
Hi,

It is possible turn off the all SSL certificate verification ?

Thx
Karoly

**Comment by darshanvithani** [comment]
https://itnext.io/node-express-letsencrypt-generate-a-free-ssl-certificate-and-run-an-https-server-in-5-minutes-a730fbe528ca

**Comment by Rob--W** [comment]
If you want to make your proxy available over HTTPS, then you'd need a certificate.

If you want to disable certificate verification (e.g. if the destination of the proxy has a bad configuration), see https://github.com/Rob--W/cors-anywhere/issues/71
