### ISSUE TITLE
Cors-Anywhere blocks responses that aren't whitelisted

### ISSUE THREAD

**Issue by DevSixl** [Rob--W/cors-anywhere#375]
I want only my website to be able to make a request but when I whitelist my website, cors-anywhere throws a 403 forbidden error because the response origin isn't whitelisted

**Comment by Rob--W** [comment]
"response origin" doesn't make sense. The "Origin" of the request is used for access decisions.

How did you specify the whitelist? An origin should be specified, which is an exact match for scheme + `://` + host name (+ `:` + port if any).

**Comment by DevSixl** [comment]
I used the command `heroku config:set CORSANYWHERE_WHITELIST="https://handle.github.io/"` to whitelist but it passes a 403 error when i try to request a response from another site

**Comment by Rob--W** [comment]
Remove the trailing slash.

**Comment by DevSixl** [comment]
Nope. It seems to work fine if I remove the whitelist but I need a whitelist considering I removed the rate limit and heroku doesn't like open proxies

**Comment by Rob--W** [comment]
Are you sure that you have identified the correct origin?

The Origin is the site that sends a request to a destination through the proxy.

If you set the environment variable and restart the server, then it should work.

**Comment by DevSixl** [comment]
I'm using jquery to get info from the external site but the environment variable should be correct, this is what I get when I use `heroku config`
`=== <heroku app name> Config Vars
CORSANYWHERE_WHITELIST: https://me.github.io/websitename`

**Comment by Rob--W** [comment]
That's not an Origin. I've described the format above.

Read about the format of Origin in more detail at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin

**Comment by DevSixl** [comment]
Oh, but I've also tried setting the whitelist to my github pages link as opposed to the actual website and that didn't work either. I've also tried both without making them strings. Nothing

**Comment by DevSixl** [comment]
I didn't notice this before but now it throws `Access to XMLHttpRequest at 'https://appname.herokuapp.com/https://example.com' from origin 'https://me.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by DevSixl** [comment]
oh, it works now, i forgot to use `heroku ps:scale web=1` to run it

**Comment by Rob--W** [comment]
Take a look at the request and response headers of the request with your browser's devtools (network tab). What's the value of Origin? That's what you should be using as the environment variable. It's also printed in the error that you shared above.
