### ISSUE TITLE
I have an interesting question... here's what I am asking

### ISSUE THREAD

**Issue by Xyncgas** [Rob--W/cors-anywhere#377]
I've seen people using reverse proxy, in a way they kinda wasn't what I was looking for when I am trying to bypass CORs problem. 
Is Cors-anywhere any different than routing the traffic through the server that's running the service? The bandwidth cost is kinda expensive in that case. Or is this service a completely different thing by tricking the origin server in the proxied request to respond directly to the client instead of traficking through this server?
Also, I am wondering if heroku provides this as a service, or it's just codes that can be used on any machine that has nothing to do with heroku.

**Comment by Rob--W** [comment]
> Is Cors-anywhere any different than routing the traffic through the server that's running the service? The bandwidth cost is kinda expensive in that case.

This is the case.

> Or is this service a completely different thing by tricking the origin server in the proxied request to respond directly to the client instead of traficking through this server?

This is not possible.

> Also, I am wondering if heroku provides this as a service, or it's just codes that can be used on any machine that has nothing to do with heroku.

It can run anywhere, Heroku is just an example where the demo server is hosted.

**Comment by Xyncgas** [comment]
understood
