### ISSUE TITLE
[Security] Bump version of http-proxy to 1.18.1

### ISSUE THREAD

**Issue by christianechevarria** [Rob--W/cors-anywhere#380]
NPM reports a security vulnerability when installing cors-anywhere

![image](https://user-images.githubusercontent.com/23618650/134415742-869b5fbf-6536-4c6d-a8a8-56bb17a798f1.png)

**Comment by Rob--W** [comment]
Duplicate of #253, see https://github.com/Rob--W/cors-anywhere/issues/254#issuecomment-659037020
