### ISSUE TITLE
Just deployed NodeJS and cors-anywhere; when I the demo webpage do GET, I get 403 error

### ISSUE THREAD

**Issue by ohaya** [Rob--W/cors-anywhere#381]
Hi,

I just installed Nodejs (17.14.6) and installed cors-anywhere.

I took the demo.html and host it on an Apache on the same machine, under htdocs/cors-anywhere/demo.html.

When I point browser to http://<hostname>:7777/cors-anywhere/demo.html, I get the demo webpage.

So I enter a URL, and click GET, and I get:

GET http://xxx.yyy.com:7777/w...target/index.html
403 Forbidden

See /corsdemo for more info

What is wrong, and also, what is that "See /corsdemo for more info" mean?

Thanks,
Jim

**Comment by ohaya** [comment]
I think that I found the cause of the 403 error.  I had to change one of the lines in the demo.html because it had the author's URL, I think.  

From:

`var cors_api_url = 'https://cors-anywhere.herokuapp.com/';`

to:

` var cors_api_url = 'http://xxx.yyy.com:8080/';`

However, now when I enter a test URL (http://xxx.yyy.com:7777/w...target.html), and click GET, I am getting a different error:

```
GET http://xxx.yyy.com:7777/wavatarget.html
404 Not Found

Not found because of proxy error: Error: getaddrinfo ENOTFOUND xxx.yyy.com
```

I can definitely DNS resolve the xxx.yyy.com hostname, however, that resolution is via the local 'hosts' file and not via a DNS server.

I am running the browser on a workstation, so that I can set up test scenarios with different hostnames (via the hosts file).

**Does that hostname DNS resolution have to actually be done via a DNS server**?

Thanks,
Jim

**Comment by Rob--W** [comment]
> I can definitely DNS resolve the xxx.yyy.com hostname, however, that resolution is via the local 'hosts' file and not via a DNS server.
> 
> I am running the browser on a workstation, so that I can set up test scenarios with different hostnames (via the hosts file).
> 
> **Does that hostname DNS resolution have to actually be done via a DNS server?**

Yes. Answered by https://github.com/Rob--W/cors-anywhere/issues/378#issuecomment-925697830
