### ISSUE TITLE
Local Cors anywere works with GET, but not POST. Returns 200 , but empty response

### ISSUE THREAD

**Issue by StianDev** [Rob--W/cors-anywhere#390]
Hey,

I can send a GET request to "http://127.0.0.1:8080/www.example.no/ws/no/" and it works.
When I send a post request to "http://127.0.0.1:8080/https://example.azure-api.net" or http://127.0.0.1:8080/dibkunnskapapi.azure-api.net:433

It returns code 200. But the response is empty. I get the right data when i use postman through the local Cors anywere, but not in the browser. @Rob--W 

Thanks

**Comment by emad-eldeen** [comment]
same issue here

**Comment by Rob--W** [comment]
Cannot reproduce.
