### ISSUE TITLE
request numbers

### ISSUE THREAD

**Issue by ilz5753** [Rob--W/cors-anywhere#393]
how I can increase request numbers?

**Comment by Rob--W** [comment]
Request numbers?

**Comment by ilz5753** [comment]
requests number
for example 1000000

**Comment by Rob--W** [comment]
I'm not following... What is the relation between your question and this repository/project?

**Comment by ilz5753** [comment]
how I can 1000000 request per 1 min?

**Comment by Rob--W** [comment]
There is no limit by default on your self-hosted instance of CORS Anywhere.

A limit of 1000000 per minute is too broad. It's very likely that you won't reach that number of requests in practice, and even if you did, your server wouldn't have enough resources to handle that volume.

**Comment by ilz5753** [comment]
What do you think I can do?

**Comment by Rob--W** [comment]
Well, phrasing your question in a clear way would be a good start. What are you trying to achieve, and how does that relate to the (rate limiting) functionality of my project?
