### ISSUE TITLE
Add ability to preserve set-cookie on responses

### ISSUE THREAD

**Issue by DovOps** [Rob--W/cors-anywhere#400]
When doing local development against non-cors API endpoints, sometimes they set cookies in the response which may be needed for subsequent requests.  Currently there is hardcoded code to delete set-cookie/2 headers. The proxy should provide an option to preserve these set-cookie response headers, in the event the user configures that they desire this behavior.

**Comment by georgir** [comment]
those headers often (always?) specify a cookie domain which will need to be rewritten from the original to the proxy domain for the cookie to be accepted by browsers

**Comment by Rob--W** [comment]
> those headers often (always?) specify a cookie domain which will need to be rewritten from the original to the proxy domain for the cookie to be accepted by browsers

Not "always". "Sometimes" would be more accurate. And such domain cookies cannot reliably be rewritten.

The linked pull request (#401) was closed for good reasons, I'll do the same with this issue.
