### ISSUE TITLE
Contains a vulnerable version of http-proxy module

### ISSUE THREAD

**Issue by prabushi** [Rob--W/cors-anywhere#402]
`cors-anywhere 0.4.4` version contains the `http-proxy 1.11.1` version which is vulnerable to denial of service attack as described in https://github.com/advisories/GHSA-6x33-pw7p-hmpq.

Possible solution: Update the http-proxy to 1.18.1.

**Comment by Rob--W** [comment]
Not affected. See https://github.com/Rob--W/cors-anywhere/issues/254#issuecomment-659037020

Duplicate of #253.
