### ISSUE TITLE
Redirect issues

### ISSUE THREAD

**Issue by y2k04** [Rob--W/cors-anywhere#407]
There is an issue where the client will request a asset for a website but the proxy will think it as the proxy root instead of the website that is hosting the requested asset.

For example:
By going to https://google.com on the proxy, the website will request the Google logo, but will instead try to request it from the proxy's root instead of Google's root.

`https://************.herokuapp.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png` instead of `https://************.herokuapp.com/https://google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png`

**Comment by Rob--W** [comment]
This proxy should not be used as a generic web proxy. It only adds CORS headers to allow cross-origin reads, and makes no attempt at trying to resolve relative URLs. I suggest to look for alternatives if you need a generic web proxy.
