### ISSUE TITLE
Modifying request origin when hosting at localhost

### ISSUE THREAD

**Issue by alvinwng** [Rob--W/cors-anywhere#41]
I am setting up this proxy at localhost to access a REST API that only allows access from certain IP addresses. When I open a local html file (with file:// in the URL) to make a POST request to the API via cors-anywhere, it appears to the API server that I am from 127.0.0.1, which is not a trusted IP address. Is there any way to change the settings in cors-anywhere to make the request as coming from my actual IP address? Thanks for your advice.

**Comment by Rob--W** [comment]
If I'm not mistaken, you have the REST API backend and CORS Anywhere running on the same computer, and you somehow want that a request from CORS Anywhere to your REST API backend has a source address other than 127.0.0.1, right? That is not possible. I think that the best solution is to allow 127.0.0.1 to access the REST API.

Note that CORS Anywhere includes proxy headers such as `x-forwarded-for` by default (which contains the IP address of the original requestor), so if the REST API trusts requests from localhost (which it should, most likely), then it can use the value of x-forwarded-for whenever the request comes from localhost.

**Comment by alvinwng** [comment]
Thanks for your explanation. I see that CORS Anywhere passes the request to http-proxy, which sets x-forwarded-for. It is actually possible to set this header with something like this:

`proxy.on('proxyReq', function(proxyReq, req, res, options) {
  proxyReq.setHeader('x-forwarded-for', '1.2.3.4');
});`

I think it is a loophole of the API I am using to think that whatever in x-forwarded-for is my actual IP address. But for now, I guess it is better than just setting it as 127.0.0.1, the IP address each machine uses to refer to itself.

**Comment by Rob--W** [comment]
You can also use the `setHeaders` option of CORS Anywhere to set request headers. Example: https://github.com/Rob--W/cors-anywhere/blob/bacbbe0cb0486a92d0430ee63be07cae13e5ce8a/test/test.js#L642-L671
