### ISSUE TITLE
Not found because of proxy error: Error: read ECONNRESET

### ISSUE THREAD

**Issue by de-it-projects** [Rob--W/cors-anywhere#420]
whilest using your plugin for github repo for the proxy server and calling to it with a link to get around the CORS-POLICY-ERROR we find ourself with this error:
Not found because of proxy error: Error: read ECONNRESET

the URL we're trying to use: (this is without using https:// in front of the 2nd link)
https://proxy.[domain].nl/[encoded_url]

if we use https:// on both we get the error:
The URL is invalid: two slashes are needed after the http(s):.

whilest using the Demo version of your plugin (https://cors-anywhere.herokuapp.com/corsdemo) we can send a request with "https://" in front of it and without.
If we remove this whilest using our own proxy we can do a POST but with the request to get results from our POST we get the error shown above 
![2022-04-20_15h36_10](https://user-images.githubusercontent.com/63643619/164243522-7d99e9ab-8751-4362-a3b3-625e7d1b261a.png)

**Comment by Rob--W** [comment]
You need to configure your server to preserve the original request URL. See my reply to #417 including the links at https://github.com/Rob--W/cors-anywhere/issues/417#issuecomment-1094308715.
