### ISSUE TITLE
Can you please merge `docker` files?

### ISSUE THREAD

**Issue by ttodua** [Rob--W/cors-anywhere#425]
I see that [this fork](https://github.com/Rob--W/cors-anywhere/compare/master...openware:master) includes a few additions of docker-files, which make it possible to create it as docker image. can you integrate them?

**Comment by Rob--W** [comment]
There is not a one-size-fits-all for everyone. There are plenty of examples of docker usage, so anyone who wants to use it can customize it according to their needs based on these examples. I've previously stated my position on the inclusion of Docker in the repo at https://github.com/Rob--W/cors-anywhere/pull/137#issuecomment-426784501
