### ISSUE TITLE
TypeError: cors_proxy.emit is not a function [Firebase Functions]

### ISSUE THREAD

**Issue by peter-palmer** [Rob--W/cors-anywhere#430]
I have deployed in Firebase Functions, calling the function by HTTP, but I'm getting this error:

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/58218056/172877138-b011e900-3a64-485c-b7c6-4112cdd6fef4.png">

index.js
```
const functions = require("firebase-functions");
const cors_proxy = require("cors-anywhere");

const options = {
   originWhitelist: [], // Allow all origins
   requireHeader: ["origin", "x-requested-with"],
};

cors_proxy.createServer(options);

exports.corsProxyRequest = functions.https.onRequest((req, res) => {
   req.url = req.url.replace("/corsProxyRequest/https:/", "/https://");
   cors_proxy.emit("request", req, res);
});
```

firebase.json
```
{
   "rewrites": [
      {
         "source": "**",
         "function": "corsProxyRequest"
      }
   ]
}
```

When I make a call...
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/58218056/172877500-7f46c5d6-1125-402e-9330-10bb6990bbf5.png">

**Comment by Rob--W** [comment]
The `emit` method is defined on the return value of `createServer`. But you're trying to use it on the `cors_proxy` object instead.

It looks like your snippet is based on #160, except modified to be broken.
