### ISSUE TITLE
getting an Uncaught (in promise) SyntaxError

### ISSUE THREAD

**Issue by LOGODERKING** [Rob--W/cors-anywhere#470]
If I try to connect my website with my cors-anywhere server i get the following error:
`Uncaught (in promise) SyntaxError: Unexpected token 'T', "This API e"... is not valid JSON`
how can i fix that?

**Comment by Rob--W** [comment]
That response is not emitted by CORS Anywhere itself and is probably an issue with your use of the destination API you are trying to reach through the proxy. Consider using the browser's developer tools to inspect the actual response body (or log the response body before using JSON.parse) to see the actual error message.

If this is an API that adapts its response type based on the request headers, include the `Accept: application/json` request header to signal interest in a JSON response.
