### ISSUE TITLE
add option to add auth header for sites like reddit

### ISSUE THREAD

**Issue by sharan21** [Rob--W/cors-anywhere#479]
this is how it would be like for a simple python request, i want to do the same thing here:
```
import requests
import base64

client_id = 'your-client-id;
client_secret = 'your-client-secret'

# Encode the client ID and client secret
credentials = '{}:{}'.format(client_id, client_secret)
credentials_b64 = base64.b64encode(credentials.encode()).decode()

# Make the request
url = 'https://www.reddit.com/your-endpoint'
headers = {
    'Authorization': 'Basic {}'.format(credentials_b64),
    'User-Agent': 'your agent name'
}
response = requests.get(url, headers=headers)

# Handle the response
print(response.text)
```
any advise on how this can be done and what lines need to be changed? Sorry I suck at js.

**Comment by Rob--W** [comment]
Your question here has nothing to do with this project, thus I'm closing it.

If you are wondering about how to send requests from a web browser, see:
- https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

If you are wondering about how to send http(s) request from Node.js with core libraries, see
- https://nodejs.org/api/https.html#httpsrequestoptions-callback
- https://nodejs.org/api/http.html#httprequestoptions-callback
