### ISSUE TITLE
Getting Error 403

### ISSUE THREAD

**Issue by darkrole** [Rob--W/cors-anywhere#48]
demo.html:81 GET http://example.com/http://google.com 403 (Forbidden)

someone can help me?
tried everything but no success :/

**Comment by Rob--W** [comment]
Can't reproduce, I tried entering both `example.com` and `google.com` in the online demo linked from the README. How exactly did you set up CORS Anywhere?

**Comment by darkrole** [comment]
downloaded de demo i changed the port and api url, check the demo here http://futplayhd.tk/canais/demo.html

**Comment by darkrole** [comment]
im kinda noob on this things haha, i thought if i just copied and open in my website it could work...
i need to launch the server application with nodejs?
can i do that in my host or do i need a dedicated server to do that? like a VPS or something like that?
