### ISSUE TITLE
Are Headers send too ?

### ISSUE THREAD

**Issue by exopole** [Rob--W/cors-anywhere#485]
Hi,

I want to use cors-anywhere to make login request for open id connect so I would like to know if headers are send too. Indeed for the connection I need to add the "Authorization" header.

Thank you in advance

**Comment by Rob--W** [comment]
The header is not automatically added by the browser because credentials are not supported. If you specify the header explicitly, e.g. with the `headers` option of `fetch` or the `setRequestHeader` method of `XMLHttpRequest`, then it will be forwarded.
