### ISSUE TITLE
BUG: Cors-Anywhere is vulnerable to cross site scripting attacks

### ISSUE THREAD

**Issue by InTruder-Sec** [Rob--W/cors-anywhere#498]
## Summary 
The proxy can lead to XSS attack when rendered unauthorized pages. 

## To Reproduce

1. . Prepare an HTML file containing an XSS payload, such as an <img> tag with embedded JavaScript (e.g., <img src="javascript:alert('XSS')">) or a normal javascript with alert tag(e.g., <script>alert(document.domain)</script>).
2. Host the HTML file or image with the payload on an accessible server.
3. You can use the below code to make sure it affects the main domain.
```html
<html> 
<head> 
<title>Hello</title> 
</head> 
<body> Hello world 
<img src="./" onerror="alert(document.domain)" />
</body> 
</html>
```
![image](https://github.com/user-attachments/assets/f314a799-9ccf-4c15-ac54-5320833694c6)

**Impact:** This vulnerability allows an attacker to execute unauthorized scripts

**Comment by Rob--W** [comment]
To prevent this kind of issue, CORS Anywhere requires a request header to be set.

How did you manage to directly load the page as in your screenshot? Can you share the exact steps? Are you using any special additional software or browser extensions?

When I visit https://cors-anywhere.herokuapp.com/example.com/ I get the following expected result:

> Missing required request header. Must specify one of: origin,x-requested-with

**Comment by InTruder-Sec** [comment]
Yes, I am using browser extension to add origin header for 
https://cors-anywhere.herokuapp.com/example.com/

But as mentioned in the description of proxy 
> To prevent the use of the proxy for casual browsing, the API requires either the Origin
or the X-Requested-With header to be set.
It can be disabled for use if needed.

Recently, I was engaged with zelcore using this proxy, wherein they disable the requirement of origin header and direct XSS was possible.

**Comment by Rob--W** [comment]
> Yes, I am using browser extension to add origin header for 
> https://cors-anywhere.herokuapp.com/example.com/

That is a user issue, not a server issue. Ordinary web browsers do not set this header, except in specific situations that are relevant to the use case for which this proxy was designed.

> But as mentioned in the description of proxy 
> > To prevent the use of the proxy for casual browsing, the API requires either the Origin
> or the X-Requested-With header to be set.
> It can be disabled for use if needed.
> 
> Recently, I was engaged with zelcore using this proxy, wherein they disable the requirement of origin header and direct XSS was possible.

That is a problem with that specific fork. The default (and documented) behavior of this repository is to require requests to specify one of these request headers.
