### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by RMstartup** [Rob--W/cors-anywhere#50]
https://cors-anywhere.herokuapp.com/ appears to be down. Therefore when I make a $.get request I receive an error. Because of the $.get error I then receive an No 'Access-Control-Allow-Origin' error as well. Is anyone else experiencing this? Is there a time frame for it to be fixed?

**Comment by Rob--W** [comment]
I have (temporarily?) blacklisted requests to `plus.google.com` and two audio streaming sites because they were responsible for the majority of requests and disrupting the service.

**Comment by rochmirabeau** [comment]
Is https://cors-anywhere.herokuapp.com/ down at the moment?

**Comment by Rob--W** [comment]
@rochmirabeau See #100 . It was, but not any more.
