### ISSUE TITLE
Change the real url for a class

### ISSUE THREAD

**Issue by darkrole** [Rob--W/cors-anywhere#51]
is that possible to change the address after http://mydomain.com/http://realdomain.com 
for something like http://mydomain.com/domain01 or something like that??

Thanks!

**Comment by Rob--W** [comment]
It is not built-in, but it should be very easy to do.

See server.js and https://github.com/Rob--W/cors-anywhere/issues/43#issuecomment-212483004 for examples on customizing; in this case you want to rewrite the URL, so in the above snippet instead of checking req.url and returning, you can do something like `req.url = req.url.replace(/^\/domain01(\/|$)/), 'https://realdomain.com$1'`

**Comment by darkrole** [comment]
i tried but is not working :/

**Comment by Rob--W** [comment]
So what exactly have you tried? I think that the instruction from my previous comment was quite clear, wasn't it?

**Comment by darkrole** [comment]
which part of the code do i need to put it? 
could give me an example please?

my serve.js code is this one:

// Heroku defines the environment variable PORT, and requires the binding address to be 0.0.0.0
var host = process.env.PORT ? '0.0.0.0' : '127.0.1.1';
var port = process.env.PORT || 8090;

// Grab the blacklist from the command-line so that we can update the blacklist without deploying
// again. CORS Anywhere is open by design, and this blacklist is not used, except for countering
// immediate abuse (e.g. denial of service). If you want to block all origins except for some,
// use originWhitelist instead.
var originBlacklist = parseEnvList(process.env.CORSANYWHERE_BLACKLIST);
var originWhitelist = parseEnvList(process.env.CORSANYWHERE_WHITELIST);
function parseEnvList(env) {
  if (!env) {
    return [];
  }
  return env.split(',');
}

// Set up rate-limiting to avoid abuse of the public CORS Anywhere server.
var checkRateLimit = require('./lib/rate-limit')(process.env.CORSANYWHERE_RATELIMIT);

var cors_proxy = require('./lib/cors-anywhere');
cors_proxy.createServer({
  originBlacklist: originBlacklist,
  originWhitelist: ['http://mysite.com'],
  requireHeader: ['origin', 'x-requested-with'],
  checkRateLimit: checkRateLimit,
  removeHeaders: [
    'cookie',
    'cookie2',
    // Strip Heroku-specific headers
    'x-heroku-queue-wait-time',
    'x-heroku-queue-depth',
    'x-heroku-dynos-in-use',
    'x-request-start',
  ],
  redirectSameOrigin: true,
  httpProxyOptions: {
    // Do not add X-Forwarded-For, etc. headers, because Heroku already adds it.
    xfwd: false,
  },
}).listen(port, host, function() {
  console.log('Running CORS Anywhere on ' + host + ':' + port);
});

**Comment by Rob--W** [comment]
That is just a copy-paste of server.js. Have you read my first comment to your issue? I included a link to another issue where I showed sample code for having custom (routing) logic on top of CORS Anywhere.

**Comment by darkrole** [comment]
this is the server.js that im using and its working properly, i just want to change the url, but i cant, ive read the coment and still i dont know how to change it
could u just give me an example on my code please?
its nothing for u, u could have done that in seconds...

**Comment by darkrole** [comment]
no? :/

**Comment by darkrole** [comment]
ok, thanks for ur help!
now when i try to start the server i got this error

```
$ node server
module.js:327
    throw err;
    ^

Error: Cannot find module 'cors-anywhere'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Projeto\cors-anywhere\server.js:14:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by darkrole** [comment]
ok thanks for ur help!
but now when i start the server, nothing happens in the cmd. and doesnt show the server is already started or listen to a port or anything like it does with the other code.

**Comment by Rob--W** [comment]
A slash is missing in front of my sample code. Put a slash before the `https://realdomain.com$1'`.

If you want to get a "server started" message, look at server.js and my sample code. I'm sure that you'll be able to figure out how to modify one line and add 2 more lines to get the desired result.

**Comment by darkrole** [comment]
thank u mate!
now this error came up:
Missing required request header. Must specify one of: origin,x-requested-with

**Comment by Rob--W** [comment]
What are you doing? This server is not intended for use as a direct proxy. These headers are required because I specified them in the default configuration. Although you can remove these from the script file, the end result is that you will have an insecure open proxy...

**Comment by darkrole** [comment]
im just using ur code that u gave me now
look how is it now

```
var cors_proxy = require('./lib/cors-anywhere').createServer({
requireHeader: ['origin', 'x-requested-with'],
  removeHeaders: [
    'cookie',
    'cookie2',
  ],
  // See README.md for other options
});

var fs = require('fs');
require('http').createServer(function(req, res) {
  req.url = req.url.replace(/^\/domain01(\/|$)/, '/http://anysite.com$1');
  // Let the server handle it
  cors_proxy.emit('request', req, res);
}).listen(8090); // Listen on port 8090.
```

**Comment by Rob--W** [comment]
I understand what you want, and the error that you're getting suggests that you are trying to directly visit the URL in the browser. That is not how this proxy should be used.

CORS Anywhere is designed for fetching cross-origin data in scripts (or anywhere where cross-origin resource sharing makes sense). Its security is designed with that in mind, i.e. credentials are intentionally blocked. When you directly visit the proxied URL in the browser, the proxied web page is able to act with the security principal of the server that serves the proxied page. In the worst case, this may lead to unintentional information leakage between proxied sites and/or the server on which the proxy is running.

**Comment by darkrole** [comment]
hmm... i see
but it worked showing the URL :/
so changing the URL wont happen?

**Comment by Rob--W** [comment]
Can you show a complete test case?

**Comment by darkrole** [comment]
add me on skype and ill share my screen with you
skype: juninhoo26

**Comment by Rob--W** [comment]
By show I do not mean show it on a video, but sharing a URL or code repository with what you're trying.

**Comment by darkrole** [comment]
cant send the link that i want to proxy here, somehow github blocks it haha
im trying to use this proxy in a live stream file (m3u8) and when i proxy this link with the code that shows the url it works
but when i use the code that u edited it doesnt work and it returns a 403 error in the player!

**Comment by Rob--W** [comment]
When you get that error, it means that either you're directly visiting the URL from the browser, or the site that fetches the resource is the same site as the proxy. In that case, the CORS proxy is unnecessary (the CORS part of the proxy, that is). A generic non-CORS proxy would be much simpler and suit your needs.

**Comment by darkrole** [comment]
really? haha
do u suggest one?
thank u!

**Comment by Rob--W** [comment]
If you insist on using Node.js, https://github.com/nodejitsu/node-http-proxy

I'm closing the issue now since it's getting a bit off-topic.

**Comment by darkrole** [comment]
i know u already closed it but the link that u sent me its not that i need, however, i solve the problem and now i can use "domain01" instead of the real source link and its working!

the only thing that im having problem now is, when i activate the whitelist i and write the domain that im accessing the proxied link, the server returns 403 like if this origin is not listed.

Could u help me with that no???

Thanks!

**Comment by Rob--W** [comment]
Post your configuration (server.js?), the steps that you followed to get a 403, and what you expected instead.

**Comment by darkrole** [comment]
i want to the source only can be viewed on the :http://mydomain.com/
it was working when i was using the real source link instead "domain01"

here is the code:
```
var originBlacklist = parseEnvList(process.env.CORSANYWHERE_BLACKLIST);
var originWhitelist = parseEnvList(process.env.CORSANYWHERE_WHITELIST);
function parseEnvList(env) {
  if (!env) {
    return [];
  }
  return env.split(',');
}

var cors_proxy = require('./lib/cors-anywhere').createServer({
  originBlacklist: originBlacklist,
  originWhitelist: ['http://mydomain.com/'],	
requireHeader: ['origin', 'x-requested-with'],
  removeHeaders: [
    'cookie',
    'cookie2',
  ],
  // See README.md for other options
});

var fs = require('fs');
require('http').createServer(function(req, res) {
  req.url = req.url.replace(/^\/domain01(\/|$)/, '/http://sourcedomain.com/$1');
  // Let the server handle it
  cors_proxy.emit('request', req, res);
}).listen(8080); // Listen on po
```rt 8080.

**Comment by Rob--W** [comment]
Origins don't have a trailing slash. They look like `http://example.com`.

**Comment by darkrole** [comment]
ooh, ok so fixed it... haha
now is everything working
this CORS anywhere is amazing man!

thanks for ur awesome support.
