### ISSUE TITLE
Viewing in browser works, requesting results in 500

### ISSUE THREAD

**Issue by sergonius** [Rob--W/cors-anywhere#69]
> "I swear I had this working just a minute ago"

I was trying this thing out and it all seemed to work, but somehow i turned a `200` response into a `500`.

```
const tickers = ['NVDA', 'MMM'];

fetch(`http://0.0.0.0:8888/https://www.google.com/finance/info?q=${tickers.join(',')}`)
  .then(res => res.text())
  .then((text) => {
    console.log(JSON.parse(text.substring(3).trim()));
  });
```

The previous snippet does some weird-ass parsing, the one below proves my point without irrelevant errors:

```
const tickers = ['NVDA'];

fetch(`http://0.0.0.0:8888/https://www.google.com/finance/info?q=${tickers.join(',')}`)
  .then((res) => {
    console.debug(res);
  });
```

Visiting `http://0.0.0.0:8888/https://www.google.com/finance/info?q=NVDA` works as expected.

Am I missing something somewhere else? I wouldn't be posting here if it hadn't worked, but in a few minutes difference something broke.

Just in case, here is my `cors.js`
```
const corsProxy = require('cors-anywhere');

const host = '0.0.0.0';
const port = 8888;

corsProxy.createServer({
  originWhitelist: [],
}).listen(port, host, () => {
  console.log(`Running CORS Anywhere on ${host}:${port}`);
});
```

Also, sorry if this is irrelevant to the module, I'm just not sure :-(

**Comment by Rob--W** [comment]
I cannot reproduce this problem. The server does not generate 500 on its own (only when the help file is missing, see https://github.com/Rob--W/cors-anywhere/blob/97c6e53020da622b006842ef112bc721cac0c47d/lib/cors-anywhere.js), so this has something to do with the resource that you're trying to proxy (i.e. Google Finance).

Is the request aborted, or does it complete with status code 500?

**Comment by sergonius** [comment]
It completes with 500, returns me HTML with the classic Google's `There was an error. Please try again later. That’s all we know.`.

This is what I used for the server, I don't think i fiddled with that at all in the process:
```
const corsProxy = require('cors-anywhere');

const host = '0.0.0.0';
const port = 8888;

corsProxy.createServer({
  originWhitelist: [],
}).listen(port, host, () => {
  console.log(`Running CORS Anywhere on ${host}:${port}`);
});
```

**Comment by sergonius** [comment]
The `Allow-Control-Allow-Origin: *` Chrome extension does work for this so I will evacuate from the situation since I need this only locally anyway.
