### ISSUE TITLE
Missing required request header?

### ISSUE THREAD

**Issue by hemanth** [Rob--W/cors-anywhere#7]
[Demo](https://robwu.nl/cors-anywhere.html) says `200 OK` for [this](http://cors-anywhere.herokuapp.com/http://isaacs.iriscouch.com/registry/foo) but the API returns `Missing required request header. Must specify one of: origin,x-requested-with`
Am I missing something?

**Comment by kalwi87** [comment]
hello have same problem here can you tell me how to fix it ? 
http://jsbin.com/cinaliposu/edit?html,js,output

**Comment by hemanth** [comment]
Does http://cors.now.sh help?

**Comment by kalwi87** [comment]
Great its working now! but its possible to make with your api?

**Comment by Rob--W** [comment]
Your jsbin example works just fine for me when I put the cors-anywhere URL there.

Can you put the code snippet here that is not working as intended?

**Comment by kalwi87** [comment]
here is with your api not working
http://jsbin.com/yogugonumo/edit?html,js,console,output

**Comment by Rob--W** [comment]
When I make the request with curl to `https://cors-anywhere.herokuapp.com/http://autoemocion.otomoto.pl/` I get:

> Not found because of proxy error: Error: connect ECONNREFUSED 5.134.209.94:80

When I start a local instance of CORS Anywhere (or use another not-so-well-known deployment of CORS Anywhere at Heroku), the request passes. So I guess that the website you are trying to proxy has blocked access to my well-known public demo of CORS Anywhere.

**Comment by burgerga** [comment]
@hemanth @Rob--W 

I also ran into this header issue while trying to scrape some data in my Angular app. I tried (`this.http` is a `HttpClient` from the `HttpClientModule` in Angular):

```
this.http.get('https://cors-anywhere.herokuapp.com/http://www.ah.nl/allerhande/recept/R-R1187761', {responseType: 'text'})
```

And this works fine, but then I wanted to do this the 'proper' way by using a proxy config, so I wrote a `proxy.config.json`:

```
{
  "/scrape/**":{
    "target":"https://cors-anywhere.herokuapp.com",
    "secure": false,
    "loglevel": "debug",
    "pathRewrite": {"^/scrape" : ""},
    "changeOrigin": true
  }
}
```

And now
```
this.http.get('/scrape/http://www.ah.nl/allerhande/recept/R-R1187761', {responseType: 'text'})
```
gets me

```
Missing required request header. Must specify one of: origin,x-requested-with
```` 
When I change the `target` to http://cors.now.sh/ it works. What is happening? (I am perfectly happy with using http://cors.now.sh/, I just want to understand :smiley:)

**Comment by burgerga** [comment]
@Rob--W 
Thanks for your quick and elaborate reply! What you're saying makes sense, learning something new everyday ;) 
I will have a look at those interceptors.

**Comment by yoavgecht** [comment]
I'm adding to my node express app
res.header("Access-Control-Allow-Origin", "*");
res.header("Access-Control-Allow-Headers", "X-Requested-With");
then trying to redirect 
res.writeHead(302, {'Location': `https://cors-anywhere.herokuapp.com/${doc.long_url}`});

Its not redirecting and in network panel it show 200 ok.
If I put the address manually on the browser it shows
Missing required request header. Must specify one of: origin,x-requested-with

any suggestion?

**Comment by yoavgecht** [comment]
I'm using CORS anywhere as a library.

So in some websites If I put the address manually on the browser it shows
Missing required request header. Must specify one of: origin,x-requested-with
And some websites are loading.

I'm seeing those headers actually added.

in the network panel 3 record is added

GENERAL
Request URL: https://impraise-shooooort.herokuapp.com/api/redirect/2wnhSH
Request Method: GET
Status Code: 302 Found
Remote Address: 34.225.198.210:443
Referrer Policy: no-referrer-when-downgrade

RESPONSE HEADERS:
Access-Control-Allow-Headers: X-Requested-With
Access-Control-Allow-Origin: *
Connection: keep-alive
Date: Tue, 01 May 2018 08:27:37 GMT
Location: https://cors-anywhere.herokuapp.com/https://yoavgecht.github.io/
Server: Cowboy
Transfer-Encoding: chunked
Via: 1.1 vegur
X-Powered-By: CORS Anywhere

and

Request URL: https://cors-anywhere.herokuapp.com/https://yoavgecht.github.io/
Request Method: OPTIONS
Status Code: 200 OK
Remote Address: 52.4.174.33:443
Referrer Policy: no-referrer-when-downgrade 

and finally this

Request URL: https://cors-anywhere.herokuapp.com/https://yoavgecht.github.io/
Request Method: GET
Status Code: 304 Not Modified
Remote Address: 52.4.174.33:443
Referrer Policy: no-referrer-when-downgrade

But redirect is not happening

**Comment by Rob--W** [comment]
Your output looks normal to me. It shows a successful redirect (see the "304" response at the end; this is not generated by CORS Anywhere, but comes directly from the proxied request).

>So in some websites If I put the address manually on the browser it shows
Missing required request header. Must specify one of: origin,x-requested-with

Please read my comment again, in particular my last paragraph.

**Comment by anaskhan2106** [comment]
Hi Rob,
So if I want to use my loacal rest call instead of example.com what to do for that.
Please help me out. Thanks

**Comment by Rits1272** [comment]
same issue("Missing required request header. Must specify one of: origin,x-requested-with") with https://www.food2fork.com/ api
