### ISSUE TITLE
OPTIONS shouldn't always return a 200

### ISSUE THREAD

**Issue by gkoberger** [Rob--W/cors-anywhere#70]
There's this in the code:

    if (req.method === 'OPTIONS') {
      // Pre-flight request. Reply successfully:
      res.writeHead(200, cors_headers);
      res.end();
      return;
    }

https://github.com/Rob--W/cors-anywhere/blob/master/lib/cors-anywhere.js#L250

I understand why it's here (since the proxy enables CORS, we can't just blindly proxy OPTIONS or it'll look like CORS isn't enabled), and agree it should be the default, many APIs use OPTIONS to get metadata about the API or about content. By returning `200` by default, the proxy breaks that usecase.

Would it be possible to at least make this an option to disable this block of code? (Internally, we've changed the code so that if it includes a specific header, it skips that block of code).

**Comment by Rob--W** [comment]
> many APIs use OPTIONS to get metadata about the API or about content

Citation needed.
This server offers CORS, and part of it is replying 200 to OPTIONS requests. If you want to disable OPTIONS requests, then you have to either edit the code as you have done, or put another layer in front of it. Here is an example that changes the behavior for requests to `crossdomain.xml`, you can easily tweak it to reply something else to OPTIONS requests: https://github.com/Rob--W/cors-anywhere/issues/43#issuecomment-212483004
