### ISSUE TITLE
How to Use In ionic2

### ISSUE THREAD

**Issue by Anujmoglix** [Rob--W/cors-anywhere#73]
I am working on Ionic2 . How to use it there?

**Comment by Rob--W** [comment]
Just put the proxy URL in front of your normal API endpoints. E.g. if you previously used `https://example.com/api/` as prefix, start using `https://cors-anywhere.herokuapp.com/https://example.com/api/` instead. Note that if you control the API endpoint yourself, then you should not use CORS Anywhere at all, but properly set up the CORS headers at your own server.

I also found some documentation specific to Ionic, take a look at http://blog.ionic.io/handling-cors-issues-in-ionic/
(I have no experience with Ionic 2, so I can't offer any more help besides this)

**Comment by anujmpec** [comment]
Thanks for your response. I asked my backed team to add headers properly , It is working fine now

**Comment by Anujmoglix** [comment]
Thanks , I fixed it from backend. I asked my API team to add proper header so it works for me,
