### ISSUE TITLE
How to integrate with existing expressjs server

### ISSUE THREAD

**Issue by dcworldwide** [Rob--W/cors-anywhere#81]
Is it possible to integrate with existing nodejs / expressjs server? Do you mind share an example (if there is one). Thanks

**Comment by Rob--W** [comment]
You can have your custom routing, optionally rewrite parts of the request (e.g. `req.url`), and then use `emit('request', req, res);` on the CORS Anywhere proxy instance (the return value of `require('cors-anywhere').createServer`) to forward requests.

Search for "createServer" on the issue tracker for previous answers about creating an internal server:
https://github.com/Rob--W/cors-anywhere/issues?utf8=%E2%9C%93&q=is%3Aissue%20createServer

E.g. https://github.com/Rob--W/cors-anywhere/issues/43#issuecomment-212483004, https://github.com/Rob--W/cors-anywhere/issues/51#issuecomment-255424553,

**Comment by dcworldwide** [comment]
Thanks Rob, will read through those link :)

**Comment by DevanB** [comment]
Any luck @dcworldwide? I haven't figured out how to make this work with an Express server yet. I've tried doing the below, but get "invalid host: proxy" returned when I do that.

```
const originBlacklist = parseEnvList(process.env.CORSANYWHERE_BLACKLIST);
const originWhitelist = parseEnvList(process.env.CORSANYWHERE_WHITELIST);
const cors_proxy = require('cors-anywhere').createServer({
  originBlacklist: originBlacklist,
  originWhitelist: originWhitelist,
  requireHeader: ['origin', 'x-requested-with'],
  removeHeaders: [
    'cookie',
    'cookie2',
    'x-heroku-queue-wait-time',
    'x-heroku-queue-depth',
    'x-heroku-dynos-in-use',
    'x-request-start'
  ],
  redirectSameOrigin: true,
  httpProxyOptions: {
    xfwd: false
  }
});

express.get('/proxy', function(req, res) {
  cors_proxy.emit('request', req, res);
});
```

**Comment by Rob--W** [comment]
@DevanB You need to rewrite the URL before passing on the request. Assuming that you want to support `http://example.com/proxy/http://cross-domain.example.net/path/to/resource`:

```javascript
express.get('/proxy', function(req, res) {
  req.url = req.url.replace('/proxy/', '/'); // Strip "/proxy" from the front of the URL.
  cors_proxy.emit('request', req, res);
});
```

**Comment by Jelledb** [comment]
This works for me:
```
        let proxy = corsAnywhere.createServer({
            originWhitelist: [], // Allow all origins
            requireHeaders: [], // Do not require any headers.
            removeHeaders: [] // Do not remove any headers.
        });

        /* Attach our cors proxy to the existing API on the /proxy endpoint. */
        api.get('/proxy/:proxyUrl*', (req, res) => {
            req.url = req.url.replace('/proxy/', '/'); // Strip '/proxy' from the front of the URL, else the proxy won't work.
            proxy.emit('request', req, res);
        });
```

**Comment by Shion093** [comment]
How to make this work with koa?

**Comment by nathann282** [comment]
@Shion093  I have a similar one

> Cannot remove headers after they are sent to the client

Did you figure out that?

**Comment by khuongdn16** [comment]
Hi, @Jelledb

I'm trying to get this to work on Firebase function as well. Do you mind sharing your settings (firebase.json, functions dir tree and index.js)

Thanks in advance

**Comment by JonathanXu1** [comment]
Could someone share an example with proxying POST requests as well? Many thanks.
