### ISSUE TITLE
Help with a live stream...

### ISSUE THREAD

**Issue by hijuuijj** [Rob--W/cors-anywhere#84]
I'm trying to open this live stream using cors-anywhere:

https://cors-anywhere.herokuapp.com/http://nbc-telemundo.live.sonytv.edgesuite.net/PROD08/sony/NBC_TELEMUNDO/live/master_wired_ads.m3u8

But I get the message "Missing required request header. Must specify one of: origin,x-requested-with"

How to open it?
Thanks in advance.

**Comment by Rob--W** [comment]
If you get the "Missing required request header. Must specify one of: origin,x-requested-with" error, then it means that you don't need to use CORS Anywhere, because the request is not a CORS-enabled cross-origin request. In other words, send a direct request and you should be fine.

**Comment by Rob--W** [comment]
By direct request, don't try to proxy the request, but directly connect to your stream URL.

Note: CORS Anywhere always rejects requests when you directly open a URL in a browser, even if the request would succeed otherwise when requested from within a web page. If you are trying to debug a network issue, use the browser's developer tools, or a network capture (e.g. Wireshark).

**Comment by hijuuijj** [comment]
I have noticed that the stream in http://www.stream2watch.cc/streaming-television/spain/telemundo-live-

is:

https://**cr7h.herokuapp.com**/http://nbc-telemundo.live.sonytv.edgesuite.net/PROD08/sony/NBC_TELEMUNDO/live/master_wired_ads.m3u8

Without https://**cr7h.herokuapp.com** I get the message "Access Denied"
With https://**cr7h.herokuapp.com** seems to be working (the m3u8 is downloaded)

**Comment by hijuuijj** [comment]
In other words: do you know how to open this stream? http://nbc-telemundo.live.sonytv.edgesuite.net/PROD08/sony/NBC_TELEMUNDO/live/master_wired_ads.m3u8

**Comment by marcos78** [comment]
hey hijuuijj, any news about this issue ? please reply me with your facebook profile, thank you.
