### ISSUE TITLE
blocked by some domain ?

### ISSUE THREAD

**Issue by calvinsug** [Rob--W/cors-anywhere#85]
hello, i'm using cors-anywhere, and it works fine until now, suddenly i can't use it to some domain like ultimate guitar, i'm using this code and it used to be work.

`  $.ajaxPrefilter( function (options) {
    if (options.crossDomain && jQuery.support.cors) {
      var http = (window.location.protocol === 'http:' ? 'http:' : 'https:');
      options.url = http + '//cors-anywhere.herokuapp.com/' + options.url;
    }
  });`

my url example is : https://tabs.ultimate-guitar.com/c/calvin_harris/feels_ver2_crd.htm
when i try another url like musixmatch (https://www.musixmatch.com/lyrics/Calvin-Harris-feat-Pharrell-Williams-Katy-Perry-Big-Sean/Feels)
it works fine. Any idea what caused this issue?

**Comment by Rob--W** [comment]
I just tried to load the URL via the demo, and the request works just fine for me.

If this issue still occurs, please add a self-contained example that shows the issue, and include the error message(s) / HTTP responses that you've received.

**Comment by calvinsug** [comment]
oh, i works now! I'm pretty sure on that time, we can't get HTML from ultimate guitar website at that time
