### ISSUE TITLE
https://cors-anywhere.herokuapp.com Unstable

### ISSUE THREAD

**Issue by conblem** [Rob--W/cors-anywhere#88]
The Heroku service is very unstable in the latest few days, any pointers.
Still, thanks for hosting it :).

**Comment by sgornick** [comment]
I've been seeing a problem as well.  I think it was giving HTTP 503, but I am not 100% sure.  I will record it and update here next time I see an issue.

**Comment by Rob--W** [comment]
I have checked a couple of times in the past week and it seemed to work fine (sometimes there are still reports though, e.g. #90).
