### ISSUE TITLE
It is possible that you did not publish the latest code to NPM official website . If really, please publish the latest code .Thanks

### ISSUE THREAD

**Issue by zhusijia** [Rob--W/cors-anywhere#91]

**Comment by Rob--W** [comment]
Is there any particular feature that you want to use that isn't in 0.4.0?

**Comment by zhusijia** [comment]
originWhitelist doesn't support environment variables.

**Comment by Jeffchiucp** [comment]
Yes. I appreciate the support for originWhitelist

**Comment by Rob--W** [comment]
Published as 0.4.1: https://github.com/Rob--W/cors-anywhere/releases/tag/0.4.1
