### ISSUE TITLE
False security

### ISSUE THREAD

**Issue by Bilge** [Rob--W/cors-anywhere#98]
Isn't all the work on rate limiting, whitelisting and blacklisting actually a complete waste of time because it trusts the sender's `Origin` header? That is, bypassing the rate limit is as simple as sending a random `Origin` header value on each request and bypassing the black/whitelist is simply a case of sending a trusted URL? Of course, you would need some way to find the whitelisted URL, but since we're talking about CORS, it implies the trusted `Origin` header is hard-coded in client-side script somewhere, so it would be relatively trivial to figure out.

**Comment by Rob--W** [comment]
The Origin header is automatically set by a web browser, so it cannot be spoofed (though a determined person could use a wildcard subdomain to bypass the rate-limit on a completely public proxy instance (such as my demo server), merely by having many unique origins at their disposal).

Non-browser clients don't need CORS to request data from another origin, so for them the proxy is only potentially useful if they want to proxy a request (e.g. to access a resource that is only available on a local intranet, and the server maintainer has (mistakenly) exposed that internal server through the server that runs CORS Anywhere.
This attack can be mitigated once #78 is implemented.

Besides DoS (proxying is relatively expensive), there are no other real issues.

**Comment by Bilge** [comment]
>The Origin header is automatically set by a web browser

This is something I did not understand. I was setting the header myself, not realizing the browser was overriding it anyway, as it had not occurred to me to try not setting it! Thanks for the clarification.
